### ISSUE TITLE
Requirements to use picker / overview on how it works

### ISSUE THREAD

**Issue by jimmymcpeter** [OneDrive/onedrive-api-docs#1003]
>If your app is a large client-side JavaScript app or uses query string parameters to maintain state, it may not be desirable to use the page launching the file picker as the redirect URI. This requires that your whole app is reloaded inside the popup window, which may cause performance issues. You can specify an alternative redirect URI through the advanced object which is used instead.

I would like to see some requirements or an overview as to how the JavaScript picker works in a large client-side application.  The paragraph above about the redirect is kind of critical to know up front, in my opinion.  I don't have a page I can redirect to, so unless this has an option to show an inline modal window like the [Google picker](https://developers.google.com/picker/docs/), I think I'm out of luck :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#customize-capabilities)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by KevinTCoughlin** [comment]
I'm not sure I follow the ask here @jimmymcpeter. The current documentation walks-thru configuring an AAD application and the Picker SDK within a web project context, https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online.

The "Setting up" section in particular mentions the need to enter redirect URL(s) which is a requirement of AAD (OAuth) based applications:

>Enter one or more URLs where the picker will be hosted on your website. Each page that hosts the picker needs to have a redirect URL provided.
>
>https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online#setting-up

The documentation is open source if you wish to propose changes to it, see https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/index.md.

Can you clarify what you are looking for so that this issue is more actionable?
