### ISSUE TITLE
problem with eTag with if-none-match

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#101]
was requesting for list at root "GET /drive/root/children"

response for first call is

{
@odata.context: "https://api.onedrive.com/v1.0/$metadata#drives('me')/items/$entity"
createdBy: {
user: {
displayName: "ankit agrawal"
id: "1d641cfae05579a4"
}-
}-
createdDateTime: "2013-03-29T13:49:59.26Z"
cTag: "adDoxRDY0MUNGQUUwNTU3OUE0ITExMC42MzU2NjM2NDAwNzkyMDAwMDA"
eTag: "aMUQ2NDFDRkFFMDU1NzlBNCExMTAuMw"
id: "1D641CFAE05579A4!110"
lastModifiedBy: {
user: {
displayName: "ankit agrawal"
id: "1d641cfae05579a4"
}-
}-
lastModifiedDateTime: "2015-05-04T19:20:07.92Z"
name: "root"
size: 9705709
webUrl: "https://onedrive.live.com/?cid=1d641cfae05579a4"
folder: {
childCount: 5
}-
}

-----------------------------------------------

before going for next call, creating one folder in root folder

the response for 2nd call is

{
@odata.context: "https://api.onedrive.com/v1.0/$metadata#drives('me')/items/$entity"
createdBy: {
user: {
displayName: "ankit agrawal"
id: "1d641cfae05579a4"
}-
}-
createdDateTime: "2013-03-29T13:49:59.26Z"
cTag: "adDoxRDY0MUNGQUUwNTU3OUE0ITExMC42MzU2NjM2NDY3ODk1MzAwMDA"
	   adDoxRDY0MUNGQUUwNTU3OUE0ITExMC42MzU2NjM2NDAwNzkyMDAwMDA
eTag: "aMUQ2NDFDRkFFMDU1NzlBNCExMTAuMw"
id: "1D641CFAE05579A4!110"
lastModifiedBy: {
user: {
displayName: "ankit agrawal"
id: "1d641cfae05579a4"
}-
}-
lastModifiedDateTime: "2015-05-04T19:31:18.953Z"
name: "root"
size: 9705709
webUrl: "https://onedrive.live.com/?cid=1d641cfae05579a4"
folder: {
childCount: 6
}-
}

now the eTag are same for both the call, but cTag changed

now using if-none-match with eTag is always returning 304, if also u make any no of changes since eTag is not getting updated.

and in recent update it was told we can use either eTag or cTag with if-none-match, can we clear idea over this???

thank u

**Comment by rgregg** [comment]
If you care about detecting changes for the contents of a folder, you should use the cTag value. Right now the eTag on a folder is only changed when the metadata of the folder itself changes. This is confusing, because things like childCount and lastModifiedDateTime are properties of a folder, but they change in this case and the eTag remains the same.

We're looking into changing how we bump the eTag value to make this work easier, but making it change every time the cTag changes will make the eTag change too frequently to be useful for the common scenario.

Once we have more thoughts about how to handle eTag, we'll update it in the future.

**Comment by ankit-ankuagrawal** [comment]
@rgregg  thank u for the reply...

currently working to bring down the traffic of network by using "if-none-match",

so should i used cTag when calling for list?
