### ISSUE TITLE
FileHandler actions integrated on the OneDrive page

### ISSUE THREAD

**Issue by maurocchi** [OneDrive/onedrive-api-docs#1021]
#### Category
- [x] Question
- [x] Documentation issue

#### Desired Behavior

As described in the OneDrive/SharePoint File Handler [reference](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/define-actions), an action is configured with an URL of a responsible service, i.e.:
```
    {
        "type": "custom",
        "url": "https://url/for/endpoint",
        ...
    }
```

I observed that every action except the preview is managed by OneDrive opening a new browser tab, resulting in a poor user experience.

Is it possible to reach a better experience by using single-page application paradims? As example, by rendering additional widgets on the page or integrating with those from OneDrive (toolbar, sidebar, etc.)?

**Comment by JeremyKelley** [comment]
Hi, thanks for your feedback!

Since the intent of the File Handlers is to route the user off to another service in most cases, the current break-out design of opening in a new tab is the one that we feel most comfortable with.  This prevents the user from being confused about whether they're still inside Office 365.  Thanks again!
