### ISSUE TITLE
pagination for GET /drive/items/id?expand=children

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#103]
presently by using one api call we can get response including parent and childs

GET /drive/items/id?expand=children

but this api call doesnt support for pagination for children.

will be supporting in near time?

**Comment by ificator** [comment]
It is already supported. When you request expansion and the expansion doesn't cover all available items you'll see a "next link" come back for the children:

  children@odata.nextLink=https://api.onedrive.com/v1.0/drives('me')/items('{id}')/children/?$top=1&$skiptoken=Mg

If you follow this link it will provide a way to get the remainder of the children.

**Comment by ankit-ankuagrawal** [comment]
@ificator thank u for the response

the url specified above is used for getting "list", but m talking specific abt api call in which parent and children response comes using expand...

**Comment by ificator** [comment]
The original request returns the parent and the children. If there are more children than will fit in the expanded children we'll return a link that can be used to fetch the remainder of the children. This link, as you've observed, will only return a list of children and we do that since there's really no reason to return the parent again - you already got its metadata the first time and so returning it on each subsequent page read of children would be a waste of bandwidth.

**Comment by ankit-ankuagrawal** [comment]
@ificator thank u for the reply, but the discussion is going in wrong direction

firstly the aim of asking this question is in regards of "saving bandwidth" by using optional header if-none-match 

wanna have discussion over 2 things

1) GET /drive/item/root(any folder)/children
in this request will never have root or any folder information in response because this will return only children and this api call support pagination $top, $nextToken

2) GET /drive/item/root(any folder)?expand=children (currently this does not support pagination)
in this request will have both root(parent) and their children information in response

so whenever have to call next time will be using "if-none-match" but in first point response dont have folder details of cTag so cant use this feature, and will contain all childern information 

while using 2 point can use "if-none-match" so that if cTag are same response should return 304

according to our design api that returns (parent and children in one call) is useful but it does not support pagination so we cant use tht

please make me correct if something wrong

Thank u

**Comment by ificator** [comment]
Thanks for clarification @ankit-ankuagrawal, I can see what you're trying to do. Am I correct in assuming that you only care about immediate children and therefore view.changes won't help here since it cannot be constrained to a depth of 1?

**Comment by ankit-ankuagrawal** [comment]
@ificator ty for the reply...

yes we are concern with "immediate children with there parent folder in response with pagination", view.changes are of no use to us

**Comment by black-snow** [comment]
@ificator What's the status of this issue?

I'm using `GET` */drive/root:/MyFolder?expand=children(select=...)* with potentially more than 200 (or even 1000) children. Must I switch to */drive/root:/MyFolder:/children*?

**Comment by black-snow** [comment]
Why is this being closed?

**Comment by rgregg** [comment]
I closed this out because it's an old issue that hasn't had activity in a months. As @ificator mentioned, you can use ?expand=children(select=...) and page through the results. @ankit-ankuagrawal was looking for something different than just being able to page through the results. To solve that scenario, right now you would need to make two separate calls, one to the root folder and another to the children collection. However, it would be preferable to use the view.delta API instead of the if-none-match headers for that sort of scenario.
