### ISSUE TITLE
Issue with subfolder image search with graph

### ISSUE THREAD

**Issue by barisbikmaz** [OneDrive/onedrive-api-docs#1046]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

The search within subfolders should return also images.

#### Observed Behavior

I have an issue when searching for images scoped on a subfolder and it's children. The same issue does not seem to occur when searching for text files. I've noticed this issue both on OneDrive and Teams drives.

#### Steps to Reproduce

Example: My OneDrive looks like this:

```
Root/
    subdirectory/
        image.png
        textfile.txt
```

If I query:

`/me/drive/items/{id-of-subdirectory}/search(q='textfile')`

my result will contain the file that I'm searching for (with the addition of the subdirectory itself):

```
"value": [
    {
        "id": "id-of-subdirectory",
        "name": "subdirectory"
    },
    {
        "id": "id-of-textfile.txt",
        "name": "textfile.txt"
    }
]
```
But if I query for the image:

`/me/drive/items/{id-of-subdirectory}/search(q='image')`

my result doesn't contain the image (only the subdirectory)

```
"value": [
    {
        "id": "id-of-subdirectory",
        "name": "subdirectory"
    }
]
```
What is the reason for why the image isn't showing up in the search result?
Is there another way to perform searching scoped to a particular subfolder and it's children?

Note: I posted this question some time ago on StackOverflow without any response:
[https://stackoverflow.com/questions/49534903/microsoft-graph-issue-with-onedrive-subfolder-image-search](https://stackoverflow.com/questions/49534903/microsoft-graph-issue-with-onedrive-subfolder-image-search)

**Comment by chackman** [comment]
Thanks for your feedback. Unfortunately this is a known issue that is on our backlog to address.

**Comment by Rismal** [comment]
same issue here.

we have a Business license.
we use an account just to serve images through API from a OneDrive shared folder of another account;
it seemed to be working, until we moved all images directly in the service account, and now search doesn't work properly.

while at first it seemed it didn't find any image at all, after several sample checks i noticed that a few in some folders are returned; i haven't been able to pin down what's so special about these lucky ones:
i double checked app permissions ( though i'm troubleshooting directly with the graph explorer ) and items sharing;
i waited hours and days hoping that maybe they needed to be indexed, but nothing; also i can't find a pattern in created/lastModified DateTime, because no image after December 2019 is returned, but just a few of last year images are.

i managed to get some result for the first time searching just "jpg", instead than by name, but right now while i'm writing i searched again, and no result any more.

in addition, unless i missed something, querying a specific drive and/or folder is pointless, because i've always got results from the whole account, shared files included.

link to duplicated issue
https://github.com/microsoftgraph/microsoft-graph-docs/issues/4209

**Comment by nike171196** [comment]
same issue here...

When listing all files via '/children" in a folder the images are present. Only when i am using the "/search" on the same folder i am not getting any results.

**Comment by barisbikmaz** [comment]
This issue is open since nearly a year. Any progress ?

**Comment by jsomhorst** [comment]
@chackman Any update on this?

**Comment by vikasprabhakar** [comment]
Hi @chackman , I'm also facing same issue. do you have any updates on this?

**Comment by vikasprabhakar** [comment]
I used POST api to search the image files and it is working.
API end point:  
https://graph.microsoft.com/beta/search/query
Method: POST
Body: {
    "requests": [
        {
            "entityTypes": [
                "driveItem"
            ],
            "query": {
                "queryString": "test.png parentLink::"\https://tescoo365dev.sharepoint.com/sites/HUB1/Shared Documents/folder1\""
            }
        }
    ]
}

**Comment by simon-holm** [comment]
Any updates? Having the same issue

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
