### ISSUE TITLE
Slow upload and download speed

### ISSUE THREAD

**Issue by AnnaDubrovina** [OneDrive/onedrive-api-docs#1058]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hello!

We have noticed that download speed is rather slow - nearly 8Mb/s for both native OneDrive application and OneDrive api. Upload speed is much higher for native OneDrive
 application than when api is used: 90Mb/s vs 10Mb/s.
Is it ok or something is wrong and can be improved?

We see this behaviour for Personal account on Windows 10 and use https://graph.microsoft.com/v1.0 endpoint.

Thank you.

**Comment by JeremyKelley** [comment]
Is this issue consistent on multiple machines or is it only in one location?  The fact that it is the same speed on the OneDrive sync client and through the API would tend to indicate that it's a network issue rather than something consistently wrong with the service.  Are you able to verify on multiple machines?

Thanks!

**Comment by AnnaDubrovina** [comment]
I checked another machine - speed is a bit higher. Also I tried another network for the first machine - speed is the same.

Thanks in advance.
