### ISSUE TITLE
[ODB] upload .asmx encounter 404

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1070]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

Hi, folks

I use this request and then encountered 404 http response with .asmx file

`PUT /items/parent_id/children/file_name/content`

I have tested about 3000+ valid file extensions, only .asmx file gets failure.

Thank you.

**Comment by ificator** [comment]
Hi @joewutaiwan, I tried a simple repro on my dev box and couldn't so we'll need a little more detail. Can you provide the `SPRequestGuid` and `Date` headers from the response?

**Comment by joewutaiwan** [comment]
Hi @ificator ,

Thank you for attention!

Here is your  information:

`PUT /_api/v2.0/drives/drive_id/items/root/children/f.asmx/content?%40name.conflictBehavior=replace `
`Host: xxx-my.sharepoint.com`

```
< HTTP/1.1 404 Not Found
< SPRequestGuid: 645fdf9e-e04a-8000-8f0b-e6f24eefb81a
< request-id: 645fdf9e-e04a-8000-8f0b-e6f24eefb81a
< Date: Thu, 23 May 2019 08:23:08 GMT
```

Thanks!

**Comment by ificator** [comment]
Thanks @joewutaiwan, got a repro. I misread your repro and was testing with `.aspx`... oops!

The workaround for your scenario is to use colons:
```
PUT /_api/v2.0/drives/drive_id/items/root:/f.asmx:/content?%40name.conflictBehavior=replace
```

A glance at the logs suggests the issue with `/children/f.asmx` is pretty low level and so I'd definitely use the workaround instead of trying to taking a dependency on us fixing the underlying issue.
