### ISSUE TITLE
{code=nameAlreadyExists, message=The specified item name already exists.}

### ISSUE THREAD

**Issue by saibaskaran57** [OneDrive/onedrive-api-docs#1098]
Hello there,

We recently faced an issue with OneDrive Business API where we received the following error message:
`{code=nameAlreadyExists, message=The specified item name already exists.}`

This was replicated when we uploaded parallel files with the same name under the same folder.
So for example in parallel, 
ActionA -> uploading file Test.txt
ActionB -> uploading file Test.txt

ActionB will fail because ActionA is still uploading the same filename and write operation is still kicking in. Therefore, there's a conflict. 

For actions as such, is there a better way of handling parallel uploads given that there are possibilities where users perform this common actions when we have multiple users under the same organization updating the same file?

Also, a suggestion, is there a possibility to provide unique code for this operation, so that as a consumer of the api we can handle it?

Do let me know you thoughts.

**Comment by JeremyKelley** [comment]
Hello,

Using the Resumable Upload API you can specify the conflict behavior.  Please take a look at the docs here: https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0

Let us know if that works in this scenario.

**Comment by saibaskaran57** [comment]
Hi @JeremyKelley,

Thank you for the updates. 

We will look at this on Resumable Upload API. However, is there a mitigation we can handle with the current One Drive Api?

Thanks.

**Comment by rakeshnbhavsar** [comment]
Hello MS Graph API Support Team,

Scenario: Uploading file abc.xlsx from local machine to SharePoint sub directory path where file with same name and extension abc.xlsx is already exists. Trying to replace/overwrite it.

I am trying to upload simple few KB abc.xlsx and or text file into SharePoint using MS Graph API .NET SDK using below line of code and it works fine if I upload file to SharePoint Site and Drive **ROOT** location, however same line of code is failing when I was trying to upload same file at SharePoint sub directory path where file with exactly same name and extension already exist. I am getting below error. Exactly same exception we have observed into File Upload into OneDrive function as well.

Exception1: "Code: nameAlreadyExists Message: A file with the same name is currently being uploaded. Change the filename and try to save again."

Exception2: "Code: nameAlreadyExists Message: Name already exists"

Exception3: "Code: timeout Message: The request timed out." - This we have handled using retry logic with along with Thread.Sleep(5000);

Line of code has an issue: Kindly suggest why it is intermittently throwing such exception or suggest better approach to do smooth file upload with consideration of large file upload too.

string fileToUploadPath = "D:\Test\";
string fileName = "abc.xlsx";
string destinationSPPath = @"<SharePoint Sub Directory relative path>"; //e.g. @"Test"

var diSearched = await graphClient.Sites[siteID].Drives[driveID].Root.ItemWithPath(destinationSPPath).Request().GetAsync();
if (diSearched != null)
{
	var fileItem = new DriveItem
	{
		Name = fileName,
		File = new Microsoft.Graph.File(),
		AdditionalData = new Dictionary<string, object>()
		{
			{ "@microsoft.graph.conflictBehavior", "replace" }
		}
	};

	bool isSPDirFound = false;
	DriveItem diChildren = null;
	try
	{
		// NOTE: Below linke was working earlier and suddenly throwing "Name Already Exist" exception, hence adding ItemWithPath approach
		diChildren = await graphClient.Sites[siteID].Drives[driveID].Items[diSearched.Id].Children.Request().AddAsync(fileItem);
		isSPDirFound = true;
	}
	catch (Exception ex)
	{
		// ECEPTION: ""
	}

	// Use properties to specify the conflict behavior in this case, replace
	var diUploadProps = new DriveItemUploadableProperties
	{
		AdditionalData = new Dictionary<string, object>
		{
			{ "@microsoft.graph.conflictBehavior", "replace" }
		}
	};

	UploadSession uploadSession = null;
	if (diChildren == null)
	{
	    // NOTE: Below line of code is working fine while uploading abc.xlsx at given SP ROOT as well as SubDir path though file with same name present at that location. However sometime this line of code also throws "Name Already Exist" exception. How to handle this?
		uploadSession = await graphClient.Sites[siteID].Drives[driveID].Root.ItemWithPath(destinationSPPath + "/" + fileName)
			.CreateUploadSession().Request().PostAsync();
	}
	else
	{
		uploadSession = await graphClient.Sites[siteID].Drives[driveID].Items[driveItemToUpload.Id]
			.CreateUploadSession().Request().PostAsync();
	}
	
	using (FileStream fileStream = new FileStream(fileToUploadPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
	{
		var largeFileUploadTask = new LargeFileUploadTask<DriveItem>(uploadSession, fileStream);		
		bool isResumeUpload = false;
		try
		{
			uploadResult = await largeFileUploadTask.UploadAsync();
			isStatus = uploadResult.UploadSucceeded;
		}
		catch (ServiceException se)
		{
			// Resume or retry uploads that fail due to connection interruptions or any 5xx errors, including:
			// 500 Internal Server Error, 502 Bad Gateway, 503 Service Unavailable & 504 Gateway Timeout
			if ("500".Equals(se.StatusCode) || "502".Equals(se.StatusCode)
				|| "502".Equals(se.StatusCode) || "502".Equals(se.StatusCode))
			{
				isResumeUpload = true;
			}
			else
				throw (se as Exception);
		}

		// Resume upload
		if (isResumeUpload)
		{
			Thread.Sleep(2000);// Litle wait to get Network get up
			try
			{
				uploadResult = await largeFileUploadTask.ResumeAsync();
				isStatus = uploadResult.UploadSucceeded;
			}
			catch (ServiceException se2)
			{
				throw (se2 as Exception);
			}
		}
	}
}

Kindly suggest a root cause as well as better approach!

Thank you and regards,
Rakesh
