### ISSUE TITLE
ODB: Unable to query root folder for changes (regression?)

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#1099]
Queries for certain OneDrive Business Accounts are failing

Query -
https://graph.microsoft.com/v1.0/me/drive/root
returns:
```
{
    "@odata.context": "
https://graph.microsoft.com/v1.0/$metadata#users('3704e25d-f6ce-4952-8deb-6cf0d067a4a7')/drive/root/$entity
",
    "createdDateTime": "2016-09-20T17:58:36Z",
    "id": "01ICHZFV56Y2GOVW7725BZO354PWSELRRZ",
    "lastModifiedDateTime": "2019-07-10T11:44:14Z",
    "name": "root",
    "webUrl": "
https://adamatthews-my.sharepoint.com/personal/adam_computa-doc_co_uk/Documents
",
    "size": 384582269460,
    "parentReference": {
        "driveId": "b!a-
oNn_Mnm02gMc86rSUI27vOcAGlo8BAhT7CxagLgF2oTC6OgbRmSaXoOirrlVDs",
        "driveType": "business"
    },
    "fileSystemInfo": {
        "createdDateTime": "2016-09-20T17:58:36Z",
        "lastModifiedDateTime": "2019-07-10T11:44:14Z"
    },
    "folder": {
        "childCount": 5
    },
    "root": {}
}
```

However querying the 'items' fails:

https://graph.microsoft.com/v1.0/drives/b!a-oNn_Mnm02gMc86rSUI27vOcAGlo8BAhT7CxagLgF2oTC6OgbRmSaXoOirrlVDs/items/01ICHZFV56Y2GOVW7725BZO354PWSELRRZ
returns:

```
{
    "error": {
        "code": "UnknownError",
        "message": "404 FILE NOT FOUND",
        "innerError": {
            "request-id": "e494b1b5-8d2c-4d38-9422-1ed864e1877d",
            "date": "2019-07-10T22:24:39"
        }
    }
}
```

#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

The item query should return objects - but is returning a 404. Other test accounts used return data without issue - so this may be an account issue as well.

#### Observed Behavior

OneDrive responds with a 404 error - when it should return with valid data that exists.

#### Steps to Reproduce

Perform queries as per above. Output generated via MS Graph Explorer.

Further details listed here: https://github.com/abraunegg/onedrive/issues/580

**Comment by ificator** [comment]
The error is suggesting the endpoint that Graph is hitting doesn't exist... which is definitely strange.

There *is* a difference between the hosts that Graph its for `/me` vs `/drives` and so that may offer an explanation, albeit one that doesn't make a whole lot of sense. The `/me` endpoint ends up hitting the personal site host (e.g. https://adamatthews-my.sharepoint.com), which is obviously working fine. If I hit that endpoint myself I get a 403 response. On the other hand the `/drives` endpoint ends up hitting the tenant host (e.g. https://adamatthews.sharepoint.com). If I hit that endpoint myself I get a 404 response and *not* a 403. This suggests that there is no tenant root site configured, and that's causing issues with the remainder of the API.

**Comment by abraunegg** [comment]
@ificator 
Thanks Brad - I think this is an account issue. As this is a Business account with support, will get the user to log a support ticket.

**Comment by abraunegg** [comment]
@ificator 
Closing this issue as this was due to the user having deleted the site. Once restored, worked as expected.

**Comment by ificator** [comment]
Thanks for letting us know!
