### ISSUE TITLE
[Question] API usage & limitations

### ISSUE THREAD

**Issue by The-Lion** [OneDrive/onedrive-api-docs#115]
I am not sure if this is the right place to ask these questions, but as I want to release a simple CMS plugin that is using the OneDrive API, I want to be sure about the limitations. If this isn't the right place, please just let me know. 

I read the [OneDrive API Terms and Conditions](https://dev.onedrive.com/terms-of-use.htm) and [Usage and Authorized Applications guidelines](https://msdn.microsoft.com/library/dn673539.aspx) but still have the following questions:

1. How are the API requests capped? Is it, for example, by the number of requests made by the app per day or the number of requests per user? Or is it a combination of both? The Google Drive API  allows you to make calls on behave of individual users (identified by adding `?quotaUser=userID` to calls) in order to prevent individual users from using up the API quota. Is something like that possible, or isn't it necessary?

2. Is it possible to monitor the number of API requests that are made by the registered App?

3. Are there any bandwidth limitations for downloading/uploading files via the API?

Thank you!

**Comment by rgregg** [comment]
Hi @The-Lion:

This is a great place to ask :).

1: API requests are limited on a per user / per application basis. That means each individual user of an app has his/her own throttle measure per application. Thus, a user could be capped in one application but free to continue using other applications. Likewise, one user of an app could hit the cap while another user can continue to use the app without problems. We measure API calls per day and the limit is set pretty high (high enough we don't expect any typical application to have a problem here). We don't publish the numbers because we reserve the ability to change them dynamically based on load on the service and don't want people designing a solution based around the limits. This throttle is returned as an HTTP 429 with a Retry-After header that indicates when you should attempt the request again.

2: We don't have a way to do this today. It's a good suggestion that I'd recommend you add to our user voice page. We know providing that information would be helpful to developers to evaluate their usage of the service and see what's happening for users of their applications.

3: In addition to API call limits there are also bandwidth limitations based on content going in/out of OneDrive. It's rare that an app would encounter these limits, although apps that attempt to migrate a large quantity of data in/out of OneDrive can encounter them. This throttle is returned as an HTTP 509 Bandwidth Limit Exceeded.

**Comment by The-Lion** [comment]
Thanks @rgregg for your quick reply, I really appreciate it! It would indeed be very useful to have some way to monitor the usage of the App.Unfortunately, I don't have any votes left on UserVoice, so I can't add a new suggestion...

**Comment by saguiitay** [comment]
Sorry for hijacking this thread, but could you discuss the proper way of handling the 509 Bandwidth Limit Exceeded error code?

For 429, I can just make another request after waiting the Retry-After delay...

**Comment by landall** [comment]
> Hi @The-Lion:
> 
> This is a great place to ask :).
> 
> 1: API requests are limited on a per user / per application basis. That means each individual user of an app has his/her own throttle measure per application. Thus, a user could be capped in one application but free to continue using other applications. Likewise, one user of an app could hit the cap while another user can continue to use the app without problems. We measure API calls per day and the limit is set pretty high (high enough we don't expect any typical application to have a problem here). We don't publish the numbers because we reserve the ability to change them dynamically based on load on the service and don't want people designing a solution based around the limits. This throttle is returned as an HTTP 429 with a Retry-After header that indicates when you should attempt the request again.
> 
> 2: We don't have a way to do this today. It's a good suggestion that I'd recommend you add to our user voice page. We know providing that information would be helpful to developers to evaluate their usage of the service and see what's happening for users of their applications.
> 
> 3: In addition to API call limits there are also bandwidth limitations based on content going in/out of OneDrive. It's rare that an app would encounter these limits, although apps that attempt to migrate a large quantity of data in/out of OneDrive can encounter them. This throttle is returned as an HTTP 509 Bandwidth Limit Exceeded.

does a GET api with extending children  count as one call?

**Comment by ificator** [comment]
Yes
