### ISSUE TITLE
App registration is not up to date

### ISSUE THREAD

**Issue by olofrobertson** [OneDrive/onedrive-api-docs#1158]
App registration has moved in to Azure. Corresponding settings that should be done under Platforms header is hard to find. //Olof

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02010cc-2715-86ca-b3fe-e4f92e934fdb
* Version Independent ID: 27b3e16e-f80f-32f4-0e4f-69cfcd1cf769
* Content: [Create an app with Microsoft Graph - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/getting-started/app-registration.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/app-registration.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by yosun** [comment]
FYI, this is issue still ongoing. Also, there is Azure downtime currently on trying to register a new app key and adding permissions.  https://www.reddit.com/r/AZURE/comments/f6f19u/experiencing_authentication_issues_additional/

**Comment by mmacy** [comment]
Several articles contain outdated app registration steps and need to be updated to reflect the current state of [App registrations](https://aka.ms/appregistrations) in the Azure portal:

```
docs/controls/file-pickers/js-v7/index.md
docs/controls/file-pickers/js-v72/index.md
docs/file-handlers/register-manually.md
docs/rest-api/getting-started/authentication.md
docs/rest-api/getting-started/app-registration.md
docs/rest-api/getting-started/app-registration-server.md
```

For example, there is no longer a **My applications** UI element, nor an **Add an app** button in the new app reg experience:

<pre><font color="#8AE234"><b>marsh@ubu</b></font>:<font color="#729FCF"><b>~/repos/onedrive-api-docs</b></font>$ grep -rin --include=*.md &quot;My applications&quot;
<font color="#75507B">docs/rest-api/getting-started/app-registration.md</font><font color="#06989A">:</font><font color="#4E9A06">23</font><font color="#06989A">:</font>3. Find **<font color="#EF2929"><b>My applications</b></font>** and click **Add an app**.
<font color="#8AE234"><b>marsh@ubu</b></font>:<font color="#729FCF"><b>~/repos/onedrive-api-docs</b></font>$ grep -rin --include=*.md &quot;Add an app&quot;
<font color="#75507B">docs/controls/file-pickers/js-v7/index.md</font><font color="#06989A">:</font><font color="#4E9A06">38</font><font color="#06989A">:</font>2. Click **<font color="#EF2929"><b>Add an app</b></font>** and enter a name for your app.
<font color="#75507B">docs/controls/file-pickers/js-v72/index.md</font><font color="#06989A">:</font><font color="#4E9A06">32</font><font color="#06989A">:</font>2. Click **<font color="#EF2929"><b>Add an app</b></font>** and enter a name for your app.
<font color="#75507B">docs/rest-api/getting-started/app-registration.md</font><font color="#06989A">:</font><font color="#4E9A06">23</font><font color="#06989A">:</font>3. Find **My applications** and click **<font color="#EF2929"><b>Add an app</b></font>**.
</pre>

As well, the old `https://manage.windowsazure.com` portal is long-deprecated, and all links/steps should updated to reflect the [Azure portal](https://portal.azure.com) and its steps/content:

<pre><font color="#8AE234"><b>marsh@ubu</b></font>:<font color="#729FCF"><b>~/repos/onedrive-api-docs</b></font>$ grep -rin --include=*.md &quot;manage.windowsazure.com&quot;
<font color="#75507B">docs/rest-api/getting-started/aad-oauth.md</font><font color="#06989A">:</font><font color="#4E9A06">93</font><font color="#06989A">:</font>**Note** The redirect URI must match one of the redirect URI that you specified in the [Azure Management Portal](https://<font color="#EF2929"><b>manage.windowsazure.com</b></font>/).
<font color="#75507B">docs/rest-api/getting-started/aad-oauth.md</font><font color="#06989A">:</font><font color="#4E9A06">229</font><font color="#06989A">:</font>**Note**  The redirect URI must match the the redirect URI that you specified in the [Azure Management Portal](https://<font color="#EF2929"><b>manage.windowsazure.com</b></font>/).
<font color="#75507B">docs/rest-api/getting-started/app-registration-server.md</font><font color="#06989A">:</font><font color="#4E9A06">66</font><font color="#06989A">:</font>1. Sign in to the [Microsoft Azure Management](https://<font color="#EF2929"><b>manage.windowsazure.com</b></font>/)
<font color="#75507B">docs/rest-api/getting-started/app-registration-server.md</font><font color="#06989A">:</font><font color="#4E9A06">72</font><font color="#06989A">:</font>   lower-right corner. This brings you back to the [Azure Management Portal](https://<font color="#EF2929"><b>manage.windowsazure.com</b></font>/).
<font color="#75507B">docs/rest-api/getting-started/app-registration-server.md</font><font color="#06989A">:</font><font color="#4E9A06">77</font><font color="#06989A">:</font>5. Close the browser and open the [portal](https://<font color="#EF2929"><b>manage.windowsazure.com</b></font>/) again.
<font color="#75507B">docs/rest-api/getting-started/app-registration-server.md</font><font color="#06989A">:</font><font color="#4E9A06">88</font><font color="#06989A">:</font>To authenticate your app, you need to register your app with Azure AD, and provide some details about your app. You can register your app manually by using the [Azure Management Portal](https://<font color="#EF2929"><b>manage.windowsazure.com</b></font>/),
<font color="#75507B">docs/rest-api/getting-started/app-registration-server.md</font><font color="#06989A">:</font><font color="#4E9A06">105</font><font color="#06989A">:</font>When you register your app in the [Azure Management Portal](https://<font color="#EF2929"><b>manage.windowsazure.com</b></font>/),
<font color="#75507B">docs/rest-api/getting-started/authentication.md</font><font color="#06989A">:</font><font color="#4E9A06">39</font><font color="#06989A">:</font>OneDrive for Business uses [Azure Active Directory](https://<font color="#EF2929"><b>manage.windowsazure.com</b></font>/) to authenticate users and applications.</pre>

Finally, as noted in #1358, manifest editing is now possible by using Azure portal UI (and that one might also need an update to use Microsoft Graph instead of Azure AD Graph).

### Recommendation

What I recommend instead of including all the steps in your articles is leveraging the Microsoft identity platform [app registration quickstarts](https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app) as appropriate, specifying just the OneDrive-specific settings the customer should configure.

For example, here's how I've done so in one quickstart that leverages the steps in another:

https://docs.microsoft.com/azure/active-directory/develop/quickstart-configure-app-expose-web-apis#register-the-web-api

> To provide scoped access to the resources in your web API, you first need to register the API with the Microsoft identity platform.
> 
> 1. Perform the steps in the **Register an application** section of [Quickstart: Register an app with the Microsoft identity platform](https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app).
> 1. Skip the **Add a redirect URI** and **Configure platform settings** sections. You don't need to configure a redirect URI for a web API since no user is logged in interactively.
> 1. Skip the **Add credentials** section for now. Only if your API accesses a downstream API would it need its own credentials, a scenario not covered in this article.
> 
> With your web API registered, you're ready to add the scopes that your API's code can use to provide granular permission to consumers of your API.

Happy to participate in PR reviews as you get these updates in, please feel free to add me as a reviewer or @ mention me directly.

Cc: @JeremyKelley @rgregg

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
