### ISSUE TITLE
limitation to upload files

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1186]
#### Category
- [x] Question
- [ ] Documentation issue

Hi all,

I saw many changes in "Upload" and "Upload large files" document.

> Upload
> This method only supports files up to 4MB in size.

1.  Is it a recommended number? Because it was used to be up to 100 MB.**

> Upload large files
> A byte range size of 10 MiB for stable high speed connections is optimal.

2. This one only provide recommended size of each part, but what is the maximum size we can upload to Onedrive?
3. Now it is at least 15 GB, but it was 10GB before (as I remembered).

Thank you for help!

**Comment by chackman** [comment]
Since these are different API's (one is PUT to file, other is uploading via a chunked upload session), they will have different limits.  We recommend the latter - chunked upload session - for larger files.

File size limits depend on the service and subscription.  I'm providing a link to the OneDrive for Business Service Description, which also links to other limits applicable to OneDrive.
   https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description
Note: limits can change, please refer to the latest information on our support pages.
