### ISSUE TITLE
[Question] OneDrive for Business

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#119]
hi, I got several question about OneDrive for Business

1.Does it exist a correct way to establish the oAuth flow with OneDrive for Business?
   I knew there is a document taking about this, but, unfortunately, it doesn't work
   https://dev.onedrive.com/auth/aad_oauth.htm
   when I followed this flow, I even couldn't get the token.
   it seems need more information like resource = https://onedrivedev.sharepoint.com at "Step 2.     Redeem the code for access tokens" part

2.where is the token connect to, when I got it form "https://onedrivedev.sharepoint.com".
   it shows some information about company admin account, but I could find the working directory at office 365 business account.

3.where is the token connect to, when I got it form "https://{tenant}-my.sharepoint.com/_api/v2.0/".
   It even couldn't pass the Authentication, when I request to the service, https://{tenant}-my.sharepoint.com/_api/v2.0/drive. 
   The return code is {"error":{"code":"-2146232832, Microsoft.SharePoint.SPException","message":"\u6a94\u6848 |0 \u4e0d\u5b58\u5728\u3002"}}

4.Until now the most successful way is to get token from https://onedrivedev.sharepoint.com and Authenticate with the RootUri https://onedrivedev.sharepoint.com/_api/v2.0/ .
  But i still receive some error, when I use the view.changes API.
 Doesn't it support yet?

5.In sum up, the final purpose for me is to get access with the OneDrive storage in office 365.
   I wonder to know whether it is too early to use this API and flow.
  Or it still be developing stage, and you do not recommend me to do this.
  I am appreciated for your help

Sincerely,
Joe

**Comment by ankit-ankuagrawal** [comment]
@joewutaiwan can u help me out with some queries...

**Comment by rgregg** [comment]
We need to improve the AAD auth docs, for sure. I've got a work item to get those updated to make this more clear. The process is definitely complicated compared to a standard OAuth flow for a single service or how Microsoft account works.

Here's the high-level overview of the steps you need to complete to use OAuth 2 with AAD to get an access token for OneDrive for Business:

1: Initial OAuth authorization through login.windows.net/oauth2/authorize?client_id={clientId}&scope=MyFiles.Write&response_type=code&redirect_uri={appUrl}
 This returns back to you an authorization code.
 
2: Redeem the authorization code for an access_token and refresh_token for the Office Discovery Service
POST to login.windows.net/common/oauth2/token with the following form parameters:
client_id, client_secret, redirect_uri, code, grant_type, and resource=https://api.office.com/discovery/
 
Note: You need to have the value of resource be exactly “https://api.office.com/discovery/” with the trailing /, otherwise the access token you get back won’t be valid.
 
 
 
3: Store the refresh_token securely for later. Even though you specify the resource for the discovery service in the request, the refresh_token value you receive is good for any service you’ve been authorized to access by the user. That means this refresh_token will get you into the OneDrive for Business, you just need to redeem it with the proper resource value later.
 
4: Use the access_token from #2 to make a request to the discovery service to find the OneDrive for Business URL:
GET https://api.office.com/discovery/v1.0/me/services
Authorization: Bearer {access_token}
 
This returns JSON data that provides the URL for the OneDrive API end point as the “serviceEndpointUri” value and also the “serviceResourceId” value which you need to request an access token to use the API. For example, you’ll get back something like this:
 
{
  "@odata.context": "https:\/\/api.office.com\/discovery\/v1.0\/me\/$metadata#allServices",
  "value": [
    {
      "@odata.type": "#Microsoft.DiscoveryServices.ServiceInfo",
      "@odata.id": "https:\/\/api.office.com\/discovery\/v1.0\/me\/services('MyFiles@O365_SHAREPOINT')",
      "@odata.editLink": "services('MyFiles@O365_SHAREPOINT')",
      "capability": "MyFiles",
      "entityKey": "MyFiles@O365_SHAREPOINT",
      "providerId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
      "providerName": "Microsoft",
      "serviceAccountType": 2,
      "serviceApiVersion": "v1.0",
      "serviceEndpointUri": "https:\/\/microsoft-my.sharepoint.com\/_api\/v1.0\/me",
      "serviceId": "O365_SHAREPOINT",
      "serviceName": "Office 365 SharePoint",
      "serviceResourceId": "https:\/\/microsoft-my.sharepoint.com\/"
    }
  ]
}
 
 
5: Redeem refresh_token for an access_token that works with the OneDrive API:
Similar to #2, you’ll do a POST to login.windows.net/common/oauth2/token, and provide all of the properties necessary to redeem the refresh token for a new access token. This time around though, set the resource parameter = {serviceResourceId} value from the discovery service.
 
6: Use the newly acquired access_token to actually make an API call.
Now you have an access_token value you can use to make API calls. You can use the serviceEndpointUri value from the discovery service, although you’ll need to modify the URL since it’s returning the v1.0 service (serviceApiVersion = “v1.0”). When we release v2.0 as the primary version, we’ll return both versions in the “value” array from the discovery service, so you’ll want to detect which version you’re working with and modify (or not) the URL accordingly.

**Comment by joewutaiwan** [comment]
@rgregg thank you, it work so fine!
@ankit-ankuagrawal hello, may I help u?

**Comment by mikechiu1012** [comment]
hi @rgregg 
there's another API listed here:
http://dev.office.com/unifiedAPIs

It looks like being simpler than using discovery API to get the service endpoints.

Does this API will release soon?
If yes, I wish there is well-defined doc. to show how to setup the scope relative in AAD.
thank u!

**Comment by ankit-ankuagrawal** [comment]
@joewutaiwan ty for the help, urgent help required

how u register the app with windows azure, i think somewhere doing wrong?

have company office365 subscription with this domain "mdm03.onmicrosoft.com"

1) after login in office365, clicking on admin, then Azure AD, after redirecting to azure, login again with the same cred of company 

2) then clicked on active directory -> new(left side bottom) -> custom create the following screen popup

![azure ad](https://cloud.githubusercontent.com/assets/11455759/7878074/9fb4dbce-0600-11e5-83f8-81831df853b0.png)

it does not drop down menu to select existing directory so without couldnt forward the process

and ty so much

**Comment by joewutaiwan** [comment]
@ankit-ankuagrawal 
hi, have you tried this page?
Associate your Office 365 account with Azure AD to create and manage apps
https://msdn.microsoft.com/office/office365/HowTo/setup-development-environment#bk_CreateAzureSubscription

After that, u can add new app belongs to the associated Office 365 account.
Hope it will help.

Joe

**Comment by ankit-ankuagrawal** [comment]
@joewutaiwan i tried got little success... stuck again to the one point...

can we have chat session, so tht can directly talk with the issue

ty

**Comment by joewutaiwan** [comment]
@ankit-ankuagrawal 
Can git-hub have chat session?
Or you have any alternatives?

**Comment by ankit-ankuagrawal** [comment]
dont know abt github but we can have on other...

like skype, fb, gmail in which ur comfortable

**Comment by joewutaiwan** [comment]
@ankit-ankuagrawal 
I think e-mail communication is good choice.
Give me your e-mail on git-hub and delete it later.

**Comment by ankit-ankuagrawal** [comment]
k

ankit.ankuagrawal@gmail.com

ty

**Comment by opicko** [comment]
I am having a problem mapping your 4 steps to APIcalls? It very confusing having an API but all the documentaion refers to URIs?

can you reword the following four steps to the specific API calls required?

1: Initial OAuth authorization through login.windows.net/oauth2/authorize?client_id={clientId}&scope=MyFiles.Write&response_type=code&redirect_uri={appUrl}
This returns back to you an authorization code.

2: Redeem the authorization code for an access_token and refresh_token for the Office Discovery Service
POST to login.windows.net/common/oauth2/token with the following form parameters:
client_id, client_secret, redirect_uri, code, grant_type, and resource=https://api.office.com/discovery/

Note: You need to have the value of resource be exactly “https://api.office.com/discovery/” with the trailing /, otherwise the access token you get back won’t be valid.

3: Store the refresh_token securely for later. Even though you specify the resource for the discovery service in the request, the refresh_token value you receive is good for any service you’ve been authorized to access by the user. That means this refresh_token will get you into the OneDrive for Business, you just need to redeem it with the proper resource value later.

4: Use the access_token from #2 to make a request to the discovery service to find the OneDrive for Business URL:
GET https://api.office.com/discovery/v1.0/me/services
Authorization: Bearer {access_token}

**Comment by rgregg** [comment]
@opicko Can you start a new issue? This one is has been closed for a while and your question seems unrelated.

**Comment by sshilpashetty** [comment]
Hi rgregg,
I am having problem to get authorization code .
I followed step 1 and i got code.
In step 2 I got error as
Error Description :8ball: 

{
  "error": "invalid_request",
  "error_description": "AADSTS90014: The request body must contain the following parameter: 'grant_type'.\r\nTrace ID: 999ec0d4-80d0-4bc2-8471-1de9f1a44429\r\nCorrelation ID: ae00f94c-f307-4bdc-8465-11ca027343c5\r\nTimestamp: 2016-06-07 13:58:55Z",
  "error_codes": [
    90014
  ],
  "timestamp": "2016-06-07 13:58:55Z",
  "trace_id": "999ec0d4-80d0-4bc2-8471-1de9f1a44429",
  "correlation_id": "ae00f94c-f307-4bdc-8465-11ca027343c5"
}



My request is  "https://login.microsoftonline.com/common/oauth2/token?client_id=6c317738-25a7-4da8-a196-b2ab54c9e540&redirect_uri=http://localhost&client_secret=RTEWAghjrTERAfzHXb2nxzy&code=M066ebbed-f351-822f-dc77-5255d76ad23e&grant_type=code&resource=https://api.office.com/discovery/"

Could yo please let me know where exactly parameters are wrong ?

**Comment by dipendrashekhawat** [comment]
Hey @sshilpashetty, You need to make the POST request to https://login.microsoftonline.com/common/oauth2/token with all the parameters in request BODY. 

I was also getting the same error and really struggled for 2 days. With the help of google chrome extension - Postman, I was able to figure out this issue and it worked.

![onedriveforbusinessaccesstoken](https://cloud.githubusercontent.com/assets/16378936/16980597/629233e0-4e84-11e6-951a-a1f807bdd151.PNG)


![onedriveforbusinessaccesstoken1](https://cloud.githubusercontent.com/assets/16378936/16980661/c0f8a0b8-4e84-11e6-9a2b-3d24878276de.PNG)

**Comment by onurece** [comment]
I'm doing exactly as above, getting an "The 'resource' request parameter is not supported." error. What do you think is the problem?

Here is the complete response.
![capture](https://cloud.githubusercontent.com/assets/13201380/26638355/d55d674a-4619-11e7-82f0-caab2662a383.PNG)

And here is my request
![image](https://cloud.githubusercontent.com/assets/13201380/26638482/222eb952-461a-11e7-8753-add82e32afd4.png)

**Comment by rgregg** [comment]
@onurece You're calling the `v2.0` endpoint for AAD authentication, which no longer uses the resource parameter and doesn't support access to the Office Discovery service. You can either switch to using the original OAuth endpoint (/common/oauth2/token) or you can continue using the v2.0 endpoint but make calls to [Microsoft Graph API instead](https://graph.microsoft.com).
