### ISSUE TITLE
Undocumented fileSystemInfo

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-api-docs#120]
When I query a resource, I notice that the a field called "fileSystemInfo" is returned. But there is not documentation about it.

```
'fileSystemInfo': {
  'lastModifiedDateTime': '2014-08-10T19:02:12.143Z', 
  'createdDateTime': '2014-08-10T17:56:04.69Z'
}
```

What's the difference between the ctime/mtime contained in fileSystemInfo and the ctime/mtime directly under the resource JSON?

**Comment by rgregg** [comment]
The documentation for fileSystemInfo is coming soon. Those dates are the client-provided creation and last modified dates, where as the dates on the item itself are the service-stamped dates for creation and last modified. Clients can (and should) write these properties when creating or updating a file so that the timestamp on a file remains consistent between the device and the service.

**Comment by rgregg** [comment]
I've published the docs for the [FileSystemInfo facet](https://github.com/OneDrive/onedrive-api-docs/blob/master/facets/filesysteminfo_facet.md)
