### ISSUE TITLE
Does onedrive refresh token expire?

### ISSUE THREAD

**Issue by youseke** [OneDrive/onedrive-api-docs#124]
I can't find an official explanation anywhere but my refresh token suddenly didn't work.
Does onedrive refresh token expire under some conditions?
Although I noticed that every time I use refresh token to get an access token, a new refresh token was returned by onedrive. Should I use the new one or just keep using the original one since there is no difference?
Hope someone can help me.
Best regards!

**Comment by rgregg** [comment]
Refresh tokens can expire, but won't expire for at least 6 months. You should always store the new one you get back whenever you redeem a refresh token, since we'll update the token to extend the expiration date based on when you did the redeem. By storing the new token, you ensure that as long as the user comes back to your app at least once every six months, they won't need to sign in again.

There are other things that can invalidate a refresh token though, including:
* User changes the password on their account
* User revokes permissions to the app

When one of these situations occurs, you'll find the refresh token is invalid when attempting to redeem it and will need to launch into the login and authorization flow again.

**Comment by youseke** [comment]
Thanks for your kind reply. It helps me a lot.
Although in my case, the refresh token has just been used for 2 months and neither password nor permissions have been modified. 
Sorry for being persistent but are there any other restrictions such as usage count or the number of issued refresh tokens?
Hope someone can help.
Best regards!

**Comment by rgregg** [comment]
There aren't any other hard limitations that would cause the token for Microsoft Account to get expired. There are limitations on refresh tokens issued by Azure Active Directory for OneDrive for Business. You should expect that the refresh token will become invalid and support a flow that gets the user back to signing into their OneDrive.
