### ISSUE TITLE
image which has GPS tags, not returning location data

### ISSUE THREAD

**Issue by udayveluvali** [OneDrive/onedrive-api-docs#1293]
![exifdata](https://user-images.githubusercontent.com/30835014/83195862-8c399780-a158-11ea-9338-efc690f2ba35.jpg)
I am trying to retrieve the location information stored in EXIF for the attached image using graph API. I am able to get all the metadata and content but not the location information. Is there anything I am missing. The response is still 200 Ok. 
https://graph.microsoft.com/v1.0/me/drive/items/item-id

**Comment by ificator** [comment]
@udayveluvali are you using a consumer or business account?

**Comment by udayveluvali** [comment]
I am using a business account.

**Comment by ificator** [comment]
Business accounts unfortunately have some feature gaps when compared to what a Consumer account can do with respect to image metadata. I'd suggest making sure there's an idea on our [UserVoice](https://onedrive.uservoice.com/forums/913708-onedrive-developer-platform) forum so that we know what pieces of metadata to prioritize.
