### ISSUE TITLE
[Question] - One Drive For Business Delta Token Expiry

### ISSUE THREAD

**Issue by saibaskaran57** [OneDrive/onedrive-api-docs#1311]
Hello there,

I have a question in regards to One Drive For Business delta token expiry duration. 

From the documentation, it is stated that it is 7 days for directory & education objects.
https://docs.microsoft.com/en-us/graph/delta-query-overview

However, it's not clear on what's the delta token expiry duration for One drive For Business.

Could you help to advise on the question above?

Thank you,
Baskaran

**Comment by chackman** [comment]
There is no published expiration for drive items because the delta token does not expire on a set timeframe. Instead, for delta on Drive Items, we recommend that client applications handle the `410/Gone` HTTP response code and refresh the token accordingly; further explanation is on this page: https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http#response-2
