### ISSUE TITLE
delta API does not return driveItem property 'deleted'

### ISSUE THREAD

**Issue by 1sooing** [OneDrive/onedrive-api-docs#1412]
I'm using Graph API v1.0 and was to get deleted list in my drive.
I'm using onedrive personal.

I found that
**- API feature that accessing to recycle bin is not provided yet.**
**- the way which can get the 'deleted' facet and enumerating it is only via delta API.**

And I'm trying to get 'deleted' facet using delta API like,
`/drive/root/delta `

but it just returns all the item in my drive(only currently existing items)
Even there is no deleted items in delta return after I delete files. Tried many times
as far as I know, there isn't filtering query feature to delta API.

So, is there any way to get deleted facet or files in onedrive API
or the way to get list of deleted items?

Thanks with best regards

**Comment by JeremyKelley** [comment]
Hello,

Depending on what you're doing this may be by design.  When you call the Delta API for the first time with no change token it will only return the current items in the drive which would not include the items that are in the recycle bin.

If you're calling Delta with a change token you should see a deleted facet (and soon an OData annotation) indicating that the item was removed if it was deleted since the last time you made the delta call.

Adding a recycle bin API is on our backlog but does not currently have an ETA.
