### ISSUE TITLE
[Question] Is there any to speed up the view.change API ?

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#142]
Hi, since I use the change api and retrieve 1000 counts of data from onedrive every time, I need a lot of time to complete the whole connection cause there are hundreds of thousands files under the monitoring folder.

I think if there is a way that no need to re-connect but get data from the first connection(maybe it's like long-polling?).

Thanks a log!

**Comment by rgregg** [comment]
Hi mike, you should only need to get the 1000s of items for the first iteration of a call to view.changes. Are you caching the nextLink / token between calls so you can request to see only the items that have changed since the last time you made a call to the API?

We don't have a method for being notified when changes exist (like what long polling would provide) but we're looking into options and should be shipping webhooks in the near future. However, with either of these, you'll need to make sure you have the right call pattern to view.changes.

**Comment by mikechiu1012** [comment]
hi rgregg, thanks for ur reply!

yes, I have kept the token and nextLink in my program.
But the question is the first time to request the change.

My way is to create a whole drive's snapshot by the change API, and request change API periodically to compare the difference.
Since I need to create the snapshot of whole drive, it will takes much times.
For example, if there are 100k files in the drive, it takes 100 times requests. 
if each request takes 10 sec. to finish all the data transferred, it needs 1000 secs to complete the snapshot. 
Most of the scenarios it take much time due to many factors like unstable network, poor devices status..., etc.

And why I need the snapshot of whole drive, that is, the change API will only return "destination" of the changed items.
For instance, one items name "a" and be renamed as "a.rename", the change API will only return the items of "a.rename" but not old items "a".
It we need to result the action is rename but not delete a and upload a.rename, we need to compare with the snapshot.

Other change API like Amazon Cloud Drive, there is no need to request every time, it takes less than 1 mins to finish 100k files' snapshot.
In Dropbox, as the case I mentioned above, dropbox will return both a and a.rename.

Thanks for all ur effort!

**Comment by OneDriveAutomation** [comment]
Can you provide more details on the scenario you are trying to accomplish? I'm not sure why you need to know both the previous file details (say, before the rename) and the current file details (after the rename). You should be able to use just the post-change values to maintain proper state, using the item ID as the key.

It looks like the Cloud Drive API works exactly the same as ours, which would require paging through 100,000 items. Are you saying the API just returns faster than ours, or are you doing something different that doesn't require you to page through 100,000 items?

Thanks, I want to understand this scenario and how we can make sure we have a good solution for your scenario.

**Comment by rgregg** [comment]
Can you provide more details on the scenario you are trying to accomplish? I'm not sure why you need to know both the previous file details (say, before the rename) and the current file details (after the rename). You should be able to use just the post-change values to maintain proper state, using the item ID as the key.

It looks like the Cloud Drive API works exactly the same as ours, which would require paging through 100,000 items. Are you saying the API just returns faster than ours, or are you doing something different that doesn't require you to page through 100,000 items?

Thanks, I want to understand this scenario and how we can make sure we have a good solution for your scenario.

**Comment by mikechiu1012** [comment]
hi rgregg, thanks for ur quickly reply.

The main scenario is I want to sync the folder between local and cloud and I want to do less API calls if the action like rename/move/copy.

For instance, a file 10G name "a" and I rename it in the cloud as "a.rename".
I got the change status information of a.rename.
If I have no idea about a.rename, I will download a.rename from cloud and that may takes time and I will keep two file 10G in my local device.
Like u mentioned, I use the item ID as the key, but before that, I need to know the item's previous status and I do this by the first change call (since I will get all the items status).

Well, I think it's ok the API works now and I just want to reduce the time for me to get all the IDs of items.
thanks~

**Comment by rgregg** [comment]
Thanks for the details Mike. I've been experimenting with this tonight, and using the `select=` query string parameter can help reduce the size of the payload you're receiving and speed up the sync response. I also recommend using Deflate or GZip encoding (by passing the Accept-Encoding header) to have the responses by compressed so there are less bytes over the wire.

We're also working on rolling out a change soon that will not return @content.downloadUrl if you have a select statement unless you ask for it, which can reduce the size of the view.changes response by a huge amount (1000 items goes from ~200kb to 15kb). Once that change has shipped, you should be able to sync 100k items metadata in 3-4 minutes instead of 8-10 minutes.

**Comment by mikechiu1012** [comment]
hi rgregg, thanks for ur reply in detail, I got it!

**Comment by rgregg** [comment]
My sample app is available here, if you want to look at what I was doing: https://gist.github.com/rgregg/2a5580d8b3523ffb6f1f

**Comment by mikechiu1012** [comment]
hi rgregg, thank u! 
I will refer the sample and try to reduce the size by user "select" query first and use compressed encoding header if need!
