### ISSUE TITLE
OneDriveSdk Download BadRequest

### ISSUE THREAD

**Issue by Albertos78** [OneDrive/onedrive-api-docs#143]
Hello, I have a problem with an app I developper with OneDriveSDK. All was working well, but from very few days I can't download binary file like png, I get a bad request for example with https://api.onedrive.com:443/v1.0/drives/6xxx28adfxxxxx6/items/6xxx2Ddsdxxxxxx/content
and request uri is like
https://public.bn1304.livefilestore.com/xxxAccessTokenxxx/1.png response is :

StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Date: Sat, 20 Jun 2015 17:54:59 GMT
  Connection: close
  Content-Length: 324
  Content-Type: text/html; charset=us-ascii
}}

What can I do ? thanks

**Comment by ificator** [comment]
Can you tell us the number of characters in the "xxxAccesstokenxxx" segment? We've had a [similar issue](https://github.com/OneDrive/onedrive-api-docs/issues/106) reported in the past that was correlated back to the segment being >256 bytes and a proxy server somewhere in the path to OneDrive not liking it.

If that turns out to be the case for you the good news is that we're currently evaluating changes to how our URLs are generated, and this issue is definitely factoring in to that process.

**Comment by Albertos78** [comment]
It is 281 characters, all the original string from uri is 334 chars.
Like the precedent problem when I copy past the original string from uri in apigee I have no problem. Responce is OK
thanks !

**Comment by Albertos78** [comment]
I have made some tests. because I have two files in the same folder (appfolder) 1 xml and 1 png. When  I download xml : no problem. When I download png : error 400.
So in the construction of the download uri of the png file I have test to replace the base download uri which do not work with these of the xml file which seems to work. The result is I have no error, but the png file seems to be corrupted (could not verify at this time).

work:
https://7kovqq.bn1304.livefilestore.com/xx259charsxx/1.xml

error400:
https://public.bn1304.livefilestore.com/xx281charsxx/1.png

tested:
https://7kovqq.bn1304.livefilestore.com/xx259charsxx/1.png : no error

**Comment by ificator** [comment]
What you'd actually be downloading with the `xx259charxx/1.png` is the XML file with the PNG's name. The large blob of characters is actually the identification of the file among other things - the legible name on the end is only a nicety to help identification of what the URL might represent at a glance.

**Comment by Albertos78** [comment]
yes I saw that when I downloaded the file... :( 
I have made many test with new files ( text, images, etc), other folder (not the appfolder I use). And it works the first time I use another folder with some 'old' backup files I have copied. I downloaded both xml en png. the 2 url had an indentification part (blob part) =259 chars.
But once I updated the file (to try viewchanges), I could'nt download them anymore netheir xml or png. the 2 url had a indentification part = 281 chars.
Like I said I made many test, and I cannot understand how to make my downloads work now (all was working well 1 or 2 weeks ago..)... is there a solution ? 
Not use OneDriveSdk ?Because the url is given as a response from servers... 
Am I alone with this problem ? I am in France.
Thanks a lot, my WP8.1 app do not work anymore.. :(

**Comment by ificator** [comment]
You aren't alone, but we also haven't heard that many complaints about the issue either. What we do know is that somewhere along the line there's a proxy server that has a maximum segment limit of ~260 characters, and as a result it's outside of our ability to mitigate. What we can do, and are doing, is make changes to the system so that we generate URLs that do not run in to this problem. We can't comment on timelines for changes like this, but it's something we are actively investigating.

I'll mark this as a bug and keep it active so that other people can find it (and comment as necessary).

**Comment by Albertos78** [comment]
ok many thanks. And, even temporaly is there any solution ? I think there is another mean to download a file with id ?

**Comment by saguiitay** [comment]
I'm actually facing a similar issue with the following URL:
https://public.bl3301.livefilestore.com/y2mf3y0oaDJV8s5qptK9eFfxoo72F_HqRwTSmGOgcwhVM2onrefJTc34pRP4abEYcSAxYO_L7QElCfaC2j_HO4IpQrPHf7nlGMuAfRB4sB1Bhap_az6SAKtiJeSMEdDMQiSXnPqgjfA3GUTQQj0rHMBpc2xdlafg8_ltodIyubzqsY9iraFKjPl8Fo8V93lB4iGkj-D3b4WVFnCAnIOiTymcg/Document with spaces.tmp

Notice that the token here is only 218 characters...

**Comment by chelishchev** [comment]
I've got the bug with URL to download content of file. Segment has 282 characters. 

Could you show workaround?

**Comment by Albertos78** [comment]
It's sad but I don't have any workaround...Don't know when the correction will bi avaible.

**Comment by Albertos78** [comment]
Is this problem resolved with updates and new sdk ? thanks

**Comment by rgregg** [comment]
Closing out old issues. If this is still a problem, please reopen and provide more details.
