### ISSUE TITLE
license problem once user is unscribe for using OneDrive Business

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#145]
there is serious problem in regards of security...

have one user "testuser1@mdm05.onmicrosoft.com"

did the following steps...
step 1: initially the user has subscription to use onedrive for business, logged in (using advanced rest client) and had accessToken and refreshToken and was able to access resources

step 2: after some time removed the subscription of the user (using admin account), so that he would not be able to use onedrive for business 

step 3: after some time, when tried to get login using web browser, message displayed "not subscribe to use this service"

*** step4: already had accessToken and refreshToken (step 1), but to my surprise still can get valid new valid accessToken when requesting (also new refreshToken is valid), in reality the refreshToken should get invalid when demanding new accessToken using existing refreshToken

Note: its more than 1 week for me to remove the subscription of the user, still can access it

this is huge security problem...

**Comment by rgregg** [comment]
Hi Ankit,

Can you actually make API calls using the access token and access data in the users OneDrive for Business?

Sent from Outlook<http://taps.io/outlookmobile>

_____________________________

**Comment by ankit-ankuagrawal** [comment]
@rgregg 
can make api calls and access data...

if required can give tokens...

couldnt access from web browser 
![odfb](https://cloud.githubusercontent.com/assets/11455759/8334854/c2607202-1ab7-11e5-8a2b-0b00f3f15c31.png)

**Comment by rgregg** [comment]
Just to make sure I understand, you've removed the license from this user through the Admin control panel. You expected that because the license was removed, the user would no longer have access to their OneDrive data. If you sign into the OneDrive for Business website, you get an error that the user doesn't have a license to use OneDrive for Business. However, using the API you can still access the OneDrive data.

If that's the case, this sounds more like a license issue than a security issue. The user is still a valid user in your directory and the account isn't disabled, they just don't have a license to use OneDrive for Business. We should be enforcing that when a user's license is removed or expired that the API no longer provides access to services that they don't have a license for. I've opened a bug to investigate.

**Comment by ankit-ankuagrawal** [comment]
@rgregg 
ty for the reply... for me the security issue was that user can use data if also unsubscribe, and admin will be in wrong state that the user no longer can access data

**Comment by ankit-ankuagrawal** [comment]
@rgregg still can receive new accessToken and refreshToken

and can access data through accessToken

**Comment by rgregg** [comment]
It is expected that you'll be able to request new tokens. The user is not disabled.

We're investigating how we handle license enforcement on the API side. We've added this item to our backlog and will be evaluating options and determining the right fix over the next month.

**Comment by rgregg** [comment]
For now this is *by design* -- to ensure that users who have accidentally been de-provisioned are not blocked, we don't block access to their content.

For security reasons, if you need to lock someone out of their account, it's best to disable their account, not just remove their license.
