### ISSUE TITLE
Scope wl.offline_access name/desc confusing

### ISSUE THREAD

**Issue by black-snow** [OneDrive/onedrive-api-docs#160]
Relating to the original issue: https://github.com/OneDrive/onedrive-explorer-android/issues/51

Imho the name as well as the description of the scope *wl.offline_access* is confusing. Here's what the docs say about the scope:
*"Allows your application to receive a refresh token so it can work offline even when the user isn't active. This scope is not available for token flow."*

This, of course, contains what the scope is actually used for (receving a refresh token) but the offline part is quite confusing (at least to me and one other person). What does "the user isn't active" mean? How is the API supposed to "work offline"?
I'm using the OneDrive API from an android application. The typical flow here is to have a setup activity where the user follows the oauth flow to connect to the service. Then later you consume the API somewhere else. Thus you need a refresh token.

A better description might be something like "required when you need to reconnect to the OneDrive API at any time without the user having to log in again".
Concerning the name, I'd recommend to add an identical scope with a name that fit's the use case better (and deprecate the old one in a future version). Better names might be something like:
*keepalive, refreshable, silent_reconnect, non_interactive, ...*

Thanks for reading

**Comment by rgregg** [comment]
Thanks @black-snow. I'll pass this along to the Microsoft Account team.

**Comment by rgregg** [comment]
I did some digging into this, and the term Offline Access is pretty standard for this flow, although I agree it is confusing. The Open ID Connect specification uses the same terminology and several other software companies (Google, Facebook, Salesforce, etc) use similar terminology to indicate that your app will be able to have access to the user's data/account when the user isn't present.

It's probably more confusing in the context of OneDrive, because a system that has a lot to do with syncing files locally and taking content offline already has a meaning for the word, but in this case it's talking about user authorization and allowing the app to have the user's authorization to work when they're not present (when the user is offline, instead of the computer/device).

**Comment by black-snow** [comment]
Well then. Having answers on SO and on github confused people like me should be able to figure it out with some minor overhead.

Thanks for the investigation.
