### ISSUE TITLE
parentReference does not have "path" when viewing changes

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#162]
Compare the results of this two calls:
1. https://api.onedrive.com/v1.0/drive/items/root:/test.txt?select=parentReference
2. https://api.onedrive.com/v1.0/drive/items/root:/test.txt:/view.changes?select=parentReference

The `parentReference` returned in the second call is missing the `path` property.

**Comment by ificator** [comment]
This behavior is technically by design.

One of the tenants we wanted for how view.changes worked was that all the metadata for the items returned from it were cacheable, and consequently we needed to guarantee that a change to any of that metadata would result in the appropriate item being returned in the next view.changes call.

The path of an item is not included in this set of metadata due to the fact that renaming a folder does not result in any of its descendants being returned on the next sync - just the folder itself. As a result, if we were to return paths on the items, and they were cached by clients, they would inevitably become stale when an ancestor was renamed.

We should make sure this is behavior is called out in our documentation though.
