### ISSUE TITLE
irmEncryptFailedToFindProtector error response when download file

### ISSUE THREAD

**Issue by how123480** [OneDrive/onedrive-api-docs#1635]
#### Category
- [x] Question
- [ ] Documentation issue
- [x] Bug

Hi,
I try to download a file by api
```
GET /items/{item-id}/content
```
and I get the error code like this
```
{"error":{"code":"resourceModified","innerError":{"code":"irmEncryptFailedToFindProtector"},"message":"The resource has changed since the caller last read it; usually an eTag mismatch"}}
```

It seems like the error on server side. What is the root cause of this error?

Furthermore, I'm wondering if there is any query option to bypass this error and force download?
Or, do you have recommanded way to handle this kind of error ?

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
This could be due to the file not being published, it could be checked out, or there could be running operations on the file. There is no special query to bypass this. Resolving this would be based on the situation with the particular file. Publishing it may resolve this, adjusting running workflows, or taking other actions. Many results in search indicate possible resolution depending on scenario.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
