### ISSUE TITLE
File Picker v7.2 Access Token & Current Account Mismatch Error

### ISSUE THREAD

**Issue by cangokceaslan** [OneDrive/onedrive-api-docs#1643]
I generated refresh token & access tokens from graph api and then I installed file picker v7.2 over the system. We generated access tokens using refresh token for file picker. We realized file picker doesn't care about accounts whose access token is generated. It returned file ids of selected files in any account which is currently sessioned on OneDrive. After getting the ids, we couldn't reach files because it is in different account.

I think this is a critical bug or mistake.

**Comment by ThomasMichon** [comment]
Thanks for your feedback on this issue. The issue you bring up, where there could be a mismatch in the selected account between your App and the File Picker, was a critical design flaw in the 7.2 SDK. Due to this, we built a new version of the File Picker SDK, version 8.0, which ensures that the token you generate from your app is what is used in the Picker to obtain data for the user.

When your App opens the File Picker in the popup window, we currently just use the sign-in cookies from the last time the user signed in directly to OneDrive, or we prompt the user to choose an account. You're right that there's no guarantee that this account aligns with the account your App used to obtain a token. The reason for this discrepancy was that the Picker's implementation was not set up to be able to leverage the token from your app to make requests.

There is one issue in the current update to the File Picker 7.2, where the button to "Switch account" went missing. We're working on restoring this. The "Switch account" button could at least let users fix their signed-in account within the popup, but ultimately the best solution is to use the new 8.0 SDK.

**Comment by patrick-rodgers** [comment]
Hello, the v7.2 Picker is no longer receiving updates, when possible please [migrate to the v8 picker](https://aka.ms/onedrive/file-picker), you can ask [questions for v8 picker in this issues list](https://github.com/OneDrive/samples/issues).
