### ISSUE TITLE
Delay in view.changes catching new changes?

### ISSUE THREAD

**Issue by ddurdle** [OneDrive/onedrive-api-docs#180]
I've been receiving inconsistent behaviour for view.changes recently.  I'll upload a batch of files, call view.changes on the root folder, providing the last known good change token, and I will get that there are no changes.  I would have to wait 30-60 mins and keep rerunning with that token until finally I get a list of changes for the files I just uploaded. 

I don't see any mention about this method being delayed.

**Comment by ificator** [comment]
Hi @ddurdle, are you seeing this behavior when calling with a business account, or a consumer account?

**Comment by ddurdle** [comment]
Consumer account.

I'll do some more testing today.  I can't pinpoint when it started happening, but I noticed somethind not right in the last 3 days.  Yesterday I did some troubleshooting and started manually making the call to see the results.  That's when I noticed the issue.

Will report back when I have more test results.

**Comment by daspek** [comment]
Hi @ddurdle, were you able to reproduce this issue?

**Comment by ddurdle** [comment]
Yes, I'm able to continually replicate the issue, but I'm still trying to track down under what circumstances I'm witnessing a delay.

What I'm doing is syncing files into my OneDrive using a script.  After the sync is done, I normally re-run, first doing a fetch on view.changes, paginating through the list of changes and saving this info locally, then I rerun through the files I just synced, verifying that the files were successfully received.  If it doesn't detect the file in view.changes, it assumes it failed and reattempts uploading. 

What I notice is if there is no significant gap between the sync finishing and a view.changes performed, then the files uploaded are not showing up in view.changes, so I end up reuploading them all.  If I don't catch it, I end up reuploading everything again.

For instance, this morning, I caught this behaviour going on.  I killed the job, reran the view.changes and sync, and it had finally captured the changes from the original run, so on the 2nd attempt at a rerun, it skipped through files already uploaded.  I also filed another discrepancy issue as I noticed in the documentation, if you do not override @name.behavior, it should fail on subsequent create item, rather than replace.  But I'll take that conversation offline in this issue.

So, really my question is, is there a delay between uploading a file and it showing up in view.changes?

**Comment by daspek** [comment]
There shouldn't be a delay. Once a file upload succeeds, we return its metadata in the response as an indication that it succeeded, and to let you know its server-assigned id. At that point it should show up in view.changes immediately. (By the way, we just released view.delta as a replacement for view.changes. It's almost identical, except with slightly cleaner paging and error handling. [Check it out](https://dev.onedrive.com/items/view_delta.htm).)

How exactly are you correlating between a file on the server and a local file? Are you looking for photo/image metadata, by chance? If so, that might explain it. After a file is uploaded, we asynchronously do some media processing to extract metadata, do object detection, ocr scan, etc. If you're looking for that metadata (rather than just, say, filename or id), then it may show up later and that may explain what you're seeing.

What kind of app are you building? Not the cause of your issue, but the algorithm you describe above could possibly lead to some race conditions. You say that you only consider an upload successful if you see it echoed back in a view.changes response. But it's possible for the upload to succeed and for the user to notice that it succeeded on onedrive.com and start making changes (or delete it), all before you get back your view.changes response. Usually an infinitesimally small window, but possible if something crashes between the upload and the view.changes requests, etc. Anyway, the expected way to cope with this is to "trust" the file metadata returned by the server in response to your upload, and not wait for the subsequent view.changes. But again, this isn't the cause of your issue.

If you're not depending on async metadata processing and you're still seeing a delay that you can reproduce, let me know and we'll dig further.

**Comment by ddurdle** [comment]
I have a directory of files which I would consider for archiving.  The script uploads the files, one by one, first to Google Drive, then to OneDrive.  Prior to uploading, I do a check for all changes beginning with the last token stored locally from the last run.  When uploading a file it will check in a local cache of my OneDrive account if the concatenation of the filename + file size is already in my OneDrive local cache db.  If it hits a match in the local db cache, it skips the file.

In my view.changes fetch, I search and use the following data for each record returned:

@content.downloadUrl
name
resid
size
sha1Hash

If for some reason the sha1Hash isn't being returned right away, then it could be failing to pickup the record.  I don't use any other metadata.

The day I originally posted the issue, what I did was capture the view.change token being given to the script, and ran the same call through the online API and confirmed it was getting no results and a hasMoreChanges = false.  I continued to do things like search for the file on the OneDrive site, confirmed it was there, etc.  I kept checking the token, until finally, it started returning results, include the last batch of files that were recently uploaded.

I prefer to fetch the changes just prior to a batch job upload run rather then collect the data during the upload.  I'll have different instances on different machines, so if I don't collect all changes, I'll be missing submissions made by other batch runs running elsewhere.

I have the ability to capture the HTTP during the runs, which is what I've been doing recently, to try to narrow in on the problem.

Last night, for instance, I had a 100 file upload which finished.  I ran the view.changes, which captured no changes, and then went ahead and started reuploading the 100 files.  I could see the files were there in OneDrive this morning when I checked.  I killed the script this morning when I witnessed it was "doing it again", and immediately reran it, it by this time, saw the 100 files from the first run, and skipped those 100 files during the uploading.

**Comment by ddurdle** [comment]
I should also note, I do the similar file name + file size check again the Google equivalent of view.changes, and I've never had the issue where the file wasn't reported in the changes summary (so no duplicate uploads).

**Comment by daspek** [comment]
Definitely interested in what you find in your HTTP captures. I also emailed you with some other diagnostic stuff you can try that'll help us narrow down the problem.

**Comment by ddurdle** [comment]
I caught the problem, but having a hard time getting a working solution.

The first batch upload will most often need to create the subfolders for which the files reside in.  In my testing, I do see the view.changes coming back with the files, but it is also coming back with the folder creations.  That's throwing off my regular expression.  On the test case I'm looking at, I have a view.changes with 162 returned entries, but it detects only 29 unique ids.  I'm storing ids in my local cache db, so it's not saving the proper file information to the correct id.  It should be trivial to fix, but I haven't cracked the regular expression yet.

I'm using the select=@content.downloadUrl,name,id,size,file so I'm not really expecting folder results to be included.  Either I hadn't noticed them before or I was getting lucky.

It explains why on subsequent runs the information gets updated properly, because when it starts reuploading the files, the folders already exist, so they are not re-created, so the view.changes only contains file information.

**Comment by ddurdle** [comment]
I've resolved the issue.  I encountered the true source of the problem and opened another issue.
