### ISSUE TITLE
view.changes returns wrong parentReference after move file to existing file

### ISSUE THREAD

**Issue by Hagi3** [OneDrive/onedrive-api-docs#181]
Using OneDrive personal (not business) website UI, and move file to the other folder where the same name file already exists, then click "Replace". (equivalent to `mv test3.txt testfolder`, where testfolder/test3.txt already exist)

After that, view.changes call returns something like below. The first entry seems correct. But the second entry's parentReference points to the destination folder. I can truck by item's id, but if I could use parentReference.id, things become easier.

```
{
  ...
  "name": "test3.txt",
  "id": "FCA..........CD0!648"
  ...
  "parentReference": {
    "driveId": "fca..........cd0",
    "id": "FCA..........CD0!639"
  },
  "file": {    ...  }
},
{
  ...
  "name": "test3.txt",
  "id": "FCA..........CD0!649"
  "deleted": {},
  ...
  "parentReference": {
    "driveId": "fca..........cd0",
    "id": "FCA..........CD0!639"
  }
}
```

**Comment by ificator** [comment]
This is how the API is expected to work. Essentially it returns the **current** state of all items that have been modified since the call to `view.changes`. The expectation is, as you mentioned, that clients will keep knowledge about the items (such as the previous parent) and can look that knowledge up by `id` when notified of a change.
