### ISSUE TITLE
Recommended fragment size

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#196]
In "[Uploading large files on OneDrive](https://github.com/OneDrive/onedrive-api-docs/blob/master/items/upload_large_files.md#best-practices)" under best practises, it is recommended to use 10 MB as optimal fragment size and, in general, to use sizes that are a multiple of 320 KB.

I think the correct units should be M**i**B and K**i**B in this case.
Also, just out of curiosity, what's the reason behind that 320 ? I've never seen it used before.

**Comment by daspek** [comment]
You're right, it should be MiB and KiB. We'll update the docs to be more clear.

Great question about the 320... Weird story. We have something internally that uses an 80KiB buffer for esoteric reasons, so things perform slightly better when you align to 80KiB. Since that's an unusual number, we recommend the slightly-less-weird 320, because it's the LCM between 80 and the more conventional 64. Then, in the future when we make the 80 thing use 64 instead, we can change our docs to recommend multiples of 64KiB without degrading performance for anyone using 320.

**Comment by skilion** [comment]
Thanks for the insight !

**Comment by daspek** [comment]
@skilion sorry for the delayed update. The docs have been clarified. Thanks for your feedback!
