### ISSUE TITLE
File/Folder determination by key presence?

### ISSUE THREAD

**Issue by JaredBanyard** [OneDrive/onedrive-api-docs#201]
Do you really have to look for a key to not be null (file or folder) to determine it's type?

**Comment by rgregg** [comment]
Yes. Our data model follows a "facet" approach to describe what an item is. While it might seem like a file system would have a straightforward concept of "file" and "folder" as unique object types, OneDrive has more capability than that. For example, a OneNote notebook that is stored in OneDrive might be a "folder" in some sense and a "file" in others. Similarly, a photo might be a "photo" or a "file" or an "image" depending on the context you want to use.

Our facet data model ensures you can support items that behave the way you want them to behave. For example, if you want to display only photos (images that were taken with a camera) you can look for items that have a non-null photo facet. You can be sure that any item you get back will have thumbnails and photo metadata and built your experience accordingly.

Similarly, if you are looking "folders" you can just as easily enumerate all items that have a "folder" facet on the item, since you know they have the properties you're looking for.

**Comment by JaredBanyard** [comment]
The reason that this is frustrating is that using a JSON interpreter like GSON will require objects to have every possible key in it that then need manual null checking to determine type.

**Comment by rgregg** [comment]
Yes, that's true. You need your native objects to include all of the properties that you expect to want to use. It sounds like you're expecting to have a "Files" and "Folders" class in your app. 

We don't have separate classes for files and folders because JSON doesn't really have classes as a concept. If we tried to simulate that in JSON it would be harder to properly deserialize the JSON since you would need to map a single collection in JSON to multiple native classes.

You can follow that model a couple of different ways, although you're right that there is a little more work involved. You could use server-side filtering to only return items with a particular facet on it (`?filter=folder%20ne%20null`) and then use GSON to map those into a native class that has the properties you expect folders to have, but then you have to make multiple API calls to get files + folders. 

You could also do similar filtering client-side to map the Items we return into files or folders and pass those classes back into your program.

**Comment by JaredBanyard** [comment]
Actually no it will be one object with just a type on it (since so many fields are the same).  The object will then have a reference list of its children and its parent parsed out that are also stored.  That way I can easily traverse using the same object.  I have already done this with the ShareFile and Box API in the same UI using interfaces for the navigation methods.

**Comment by rgregg** [comment]
You could easily do that as well with OneDrive. You would just write code into the native class you deserialize into that would provide a "Type" property and do the null-checks to return the right type, something like 
```
String type() {
  if (this.File != null) {
    return "file"
  } else if (this.Folder != null) {
    return "folder"
  };
}
```

Alternatively you could write something like `bool isFile() { return this.File != null; }` as well. Neither of those seem that difficult to enable.

**Comment by JaredBanyard** [comment]
Yeah I know how to check for null.  My goal was to not have extra code for deserializing that depends on null checking so that I could automatically parse.

**Comment by rgregg** [comment]
I'm closing this out since it seems like we're at a dead end. GSON can easily deserialize the JSON to a single class file, like it sounds like you are looking for. From there you can either augment that class to provide the additional interface for a type property that you're looking for, or you can use the null checks throughout your code.
