### ISSUE TITLE
500 error (timeout) in GetItems response

### ISSUE THREAD

**Issue by trendtom** [OneDrive/onedrive-api-docs#222]
Hi there,

I've been seeing this 500 error response intermittently today, both from the API and the web UI in the GetItems (https://skyapi.onedrive.live.com/API/2/GetItems) request:

```
{
 "error": {
  "code":6,
  "debugMessage":"A task timed out.  Please try again.",
  "message":"Sorry, something went wrong. Please try again or refresh the page.",
  "stackTrace":"e5119dd245c101d22:+yGFSVizuXQuegtBbKC24znaXiH2k\/lAJTlPVdATkLKdodZJsJAeaDIdJBmWkLXB4mD0T6eE3+j5+0mbKQU7SLZzKmTgvYJIsOEJ+Y4F51tN9o2k\/OVRNeGJ\/EnqZfN0fFR1fYvCjTRdZ2fbZiZEz8PruNgrCAvE4BDKGwKciylAeBXCL2KI3kaSFyn7QBOuSZjEmXEP6q5baKz1WmqKUm+NElpDcPFF+8jsZMozvGciUEtsP5Y3+lfcQ1WXhs2Pr6ilBGYGNrtbXAC98OSb0Asz3T9XQq5GukvKcBsTOS1gdPU7fVEcH7mJ8Ib90k\/xAZIPsOsKif9G26GVhC+WQPHjAI0nnixoYi46TpOitPKkYysX+AHNwa+raxYVCicp8rCMz2ZqLcncumlCypEkJdL+\/ADWjcOMbbY49YkZPk1\/xsCJtKE8K\/4NKe9Ndn2O2imf5b6xu2k0n0SUQFdan+57QhOg8+01tVJviSw21c9i3rW70QvsiksLKRi3xhArX8efHJQ2qqRsvkJtZRv28Ngy1YYitX7aQpOiZrp1+d\/8R\/OvP9\/JEKirx5D+dXAi6cv80wFEwnlQW3j3VXJVnAmceFkNoLbOYEuvYKCFShDT7Ta6hyA9ADq\/eX\/eUw1uxmCrrU05iBVgTF+RVu2Q0zF+uWwgOKwOYbQbSKWm4S\/J9UV\/CihfoXpPDKHJ3QTxIWni58yaJcfc9Fm+kkLvQhIMLcJSibfGQ3zYJj8AIH9074NcEY6Ybx9wY9DPAZJ2\/2cwGGYq61gUBo03OGS\/1Q=="
 },
 "transactionId":"52ea55ca-3ff4-46ea-ad6d-f0c2ac852424.Unknown1"
}
```

In the web UI, I've seen it happen on the root folder and in application folders too.

For some folders it's happening every time, on the root folder it varies.

Some response headers that may be relevant (for the above JSON error):

```
X-AsmVersion:UNKNOWN; 19.29.0.0
X-Content-Type-Options:nosniff
X-ExperienceId:cbb36d3b-6592-4561-9c14-c65ea12a4c08
X-Imf:96a41046-57ca-4cb4-9f35-36b5734471e4
X-MSNSERVER:BY3302____PAP127
X-QosStats:{"ApiId":2501014,"ResultType":5,"SourcePropertyId":25,"TargetPropertyId":0}
```

**Comment by daspek** [comment]
Hi @trendtom, there was an issue earlier today that increased latency and caused timeouts for some users. It should be resolved now. Let us know if you're still seeing issues.

**Comment by trendtom** [comment]
Thanks @daspek - so far I've not seen any further cases today. Will run some more tests then close the issue if things look stable.

**Comment by Santhosini** [comment]
This issue seems to be happening.
Getting a 500 response error for past two days.

**https://skyapi.onedrive.live.com/API/2/GetItems** 

{"error":{"code":103,"debugMessage":"The given canary was not valid.","isExpected":true,"stackTrace":"6e0d716691d635f42:zVCkWx+WIP\/8xepxq6\/8c2RH4LQYAsgEb1g+Bh5Z96HZMkpNLJO3U4UCp8LYeXJGS4m2qr7hnEvx8E98Dc\/SgYcs+W6eaeUOybmMw4Oos3Im1kqUdodTZpuyCKAQ7ZPq3Q6MHrjOFLky0W\/YGX\/Mhm0yiWzrlqpZe8Vips78JILwsph8MRSfwlkHCmdBCNSyca15FnSBCJ819k38ZlbRsI\/PUQzGzNBFYYmqYQuq7Bws8pmBUrTlY3nW9v3BvXWU\/izxjB4LAnNNtigueQs6WIS3z6\/ZgQBLxj0JnSKgx\/555c3uQp7lQ3vY8idp2HSBRrkiwwB8A4hQ85zP8kmQNy6Tn34zPW5BceFldNN31qBe7ECNa8mI4sl5DHoIeEGRwd\/DmCZ4YM70z0N7m2Ht9xtYACSGCQy+Q5KVst4p0hCL9dXe9gP06qfdUyjTp6MX4OhWgve4qJsBlVyM\/wxGJQ2ToQjCEfE9MUwFNkUX6Rqq\/1xVrUmMbZHOtS8shxhyHuFkMZn63hDYeKxNSQO0VaFFjhIfyTQUC2j+4g0mrm0Os7RLZ8xfnCQBsfkcvGsG5idsIdlR43gL\/NHItIZLYEa5NuTOFdwJwczcQCuGr1UYxftEj68q8MSK27yariTciRw\/MyS4x7YxEdlJKqb6lUX8RMPVGEEfwE+w\/Ow6+9vlFfgmXyFtj3rlf4jwklh3"}}
