### ISSUE TITLE
Accessing API through site url with app-access tokens

### ISSUE THREAD

**Issue by desmondyeung** [OneDrive/onedrive-api-docs#224]
Hello I'm using a OneDrive for Business account and am hitting issues accessing a drive through a site URL (e.g. `https://[tenant]-my.sharepoint.com/personal/[username]/_api/v2.0/drive/...`) with app-access tokens.

I don't have any issues using a user-access token to access this resource

```
GET https://[tenant]-my.sharepoint.com/personal/[username]/_api/v2.0/drive/
Authorization Bearer: [user-access token] 

HTTP Status: 200
...
```

However when using the app-access token it appears to try to resolve the logged-in user's site despite explicitly requesting another site through the URL.

```
GET https://[tenant]-my.sharepoint.com/personal/[username]/_api/v2.0/drive/
Authorization Bearer: [app-access token] 

HTTP Status: 500
message: "User 'i:0i.t|00000003-0000-0ff1-ce00-000000000000|app@sharepoint' doesn't exist in UPA by UPN or SID, and user with this SID was not found in AD."
```

It doesn't appear to be an auth issue I am able to hit other resources with the app-access token, just not the `/drive` resource.

```
GET https://[tenant]-my.sharepoint.com/personal/[username]/_api/v2.0/drives/
Authorization Bearer: [app-access token] 

HTTP Status: 200
{
  "@odata.context":"https://[tenant]-my.sharepoint.com/personal/[username]/_api/v2.0/$metadata#drive",
  "value":[]
}
```

Am I doing something wrong? Any help would be appreciated.

**Comment by townie** [comment]
+1

**Comment by katahir** [comment]
Hi Desmond,
Sorry to hear you have been having some trouble accessing /drive endpoint using an app-only token. You are right in assuming that when a call comes from the personal site, we shouldn't try to resolve the logged-in user's personal site. This was a bug in the code and we have fixed it. Going forward, we will try to resolve the logged-in user's personal site, only if the request was made from the personal site host. The fix should be out in Prod by mid December.

P.S.
Making a request to the personal site host using an app-only token will result in an error since there is no user identity in the token and we have no way of resolving the user's personal site.

**Comment by ificator** [comment]
App-Only tokens have been supported for quite some time now so I'm going to close this. Please reactivate if you're still seeing issues.
