### ISSUE TITLE
view_delta token expiry

### ISSUE THREAD

**Issue by zyxophoj** [OneDrive/onedrive-api-docs#231]
Hi,

We found out the hard way that delta.tokens received from view_delta do not last forever.  It looks like they stop working about 30 days after we get them.  Bug or feature?

Is there any way to get round this?  For example, we can call view_delta with top=0.   If we do, we get the same token back.  Does this reset the clock?

-Mark

**Comment by daspek** [comment]
Hi Mark, I'm sorry you ran into this snag. It's expected behavior, though. The tokens need to have a finite lifespan in order for us to clear out info about deleted files. Let's say you got a delta token today, deleted some files, and didn't come back with that token to see what's changed for 5 years. In order for us to still report that those files got deleted, we'd need to keep track of them for all that time. To avoid that, and to let us get rid of deleted files for good after some time, the tokens have to expire.

The [delta docs](https://dev.onedrive.com/items/view_delta.htm) talk about what to do to get back into sync if your token expires. If those steps don't work for your app, let us know more about what you're doing and we'll see if we have any ideas.

Calling view.delta again does give you a refreshed token, but the system assumes that when you call it, you're intending to sync down changes. Calling with top=0 all the time won't force the system to hold on to deleted items longer than the tombstone retention period.

**Comment by zyxophoj** [comment]
>The delta docs talk about what to do to get back into sync if your token expires. If those steps don't work for your app, let us know more about what you're doing and we'll see if we have any ideas.

OK, let's start with that.

What we want to do is get a list of changed files since "last time we asked".  We actually don't care about deletes, it's changed files and new files that we want to know about.

We can certainly detect the ResyncRequired error and start again from the beginning.  It's just that we'd rather avoid doing that if possible.  And it seems silly.  We'd do a view_delta, starting from the beginning of time, then strip out all changes that happened before the last time we asked.  All because it's not possible to just ask directly for changes since a certain date (except via a token obtained on that date, which may stop working)

So.. if we do view_delta until we get the last page and a token back with it, how long will that token last for?  Is there a lower bound on the lifetime of a token received in this way?  If there is, then what is it?

We'll still need the full view_delta procedure from time to time, to recover from outages or accidentally deleting all our data or whatever, but it would be nice not to have to use it routinely.

-Mark
