### ISSUE TITLE
Upload data to append to an existing file

### ISSUE THREAD

**Issue by TayNelson** [OneDrive/onedrive-api-docs#242]
This is a feature request. It would be brilliant for functionality to be added to allow users to upload content to be appended to an existing file.

The endpoints for this could function similar to how those for upload sessions do.

Some of the differences would be:
* The endpoint would need to check the existence of the file being appended to
* `@name.conflictBehavior` would not have an effect

Here's an example purely for the purpose of describing how it _**could**_ work:

<pre>
POST /drive/root:/{path_to_item}:/upload.create<b>Append</b>Session
POST /drive/items/{parent_item_id}:/{filename}:/upload.create<b>Append</b>Session
</pre>

<pre>
HTTP/1.1 200 OK
Content-Type: application/json

{
  "uploadUrl": "https://sn3302.up.1drv.com/up/fe6987415ace7X4e1eF866337",
  "expirationDateTime": "2015-01-29T09:21:55.523Z",
  "nextExpectedRanges": <b>["12345-"]</b>
}
</pre>

This will facilitate the intermittent uploading of large files, as described in #240.

An alternative approach could be to allow users to join files together, as requested in #241.

**Comment by daspek** [comment]
Good idea, and thanks for the detailed write-up. I think an 'append' session could be tricky because if the base file got modified by someone else while the append was still happening, then all the progress against the append session would basically be throw-away. I like your other idea more of, "here's some existing files, please stitch them together." We'll think about how best to solve this... In the meantime, like I said in the other comment, please consider adding this on [UserVoice](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) so that others can vote too.
