### ISSUE TITLE
Folders with the RemoteItem facet don't have a FolderFacet

### ISSUE THREAD

**Issue by saguiitay** [OneDrive/onedrive-api-docs#284]
Steps to reproduce:

  * AccountA shares a folder with AccountB
  * AccountB adds the shared folder into his OneDrive account.
  * Retrieve the list of folders (in the drive) of account B

You'll notice that the shared folder appears in the list of children of the drive correctly. It also has the `remoteItem` facet correctly. However, being a folder, I would expect it to have the `folderFacet` as well.

Instead, in order to know whether the item is a folder or a file, I need to check if the remoteItem facet has a (sub) folderFacet.

**Comment by rgregg** [comment]
Hi @saguiitay. This is the designed behavior. We did that in part for backwards compatibility reasons, because we didn't want apps that were designed to understand how items with a folderFacet work to get confused when they encountered a remoteItem. As such, items with a remoteItem facet have a limited set of additional information on the item itself. You can query for whether the item is a folder or file though by looking into the remoteItem proprety of the remoteItem facet. (item.remoteItem.remoteItem) and look to see if there is a folder or file facet.
