### ISSUE TITLE
onedriveforbusiness discovery return empty value?

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#292]
Hi, 

I noticed that my application is unable to get the endpoint url this morning.

So I tried to use curl to make sure what happended with following command
```
 curl  https://api.office.com/discovery/v2.0/me/services  --header "Authorization: Bearer my_access_token"
```

And I got the response with a empty value?
```
{"@odata.context":"https://api.office.com/discovery/v2.0/me/$metadata#allServices","value":[]}
```

Is server updating or patching something?

**Comment by rgregg** [comment]
I'm looking into what's going on here. Thanks for opening this issue.

**Comment by verybada** [comment]
@rgregg 
I registered a new trial account yesterday and I found a weird message from subscription page.
```
You don't have a license to use Office 365 with the user ID assigned to you by your work or school. Ask your admin to assign one to you. If you're an admin, you can assign one to your account.
```
But this account still in trial, it shouldn't be block right?

**Comment by mikechiu1012** [comment]
I suffer such situation from Sat.(+8:00) too.
{'value': [], '@odata.context': 'https://api.office.com/discovery/v2.0/me/$metadata#allServices'}

I try to use several accounts to do auth, but I got the same result.

But it works now (with no flow changed.)
My account is not trial and I got no information about server status.
Is there any place I could monitor or be notified about auth server situation?
Thanks.

**Comment by rgregg** [comment]
As more scenarios are coming online with the [Microsoft Graph API](https://graph.microsoft.io) we're transitioning from using the discovery service API to services just using Microsoft Graph API directly and avoiding the extra round-trip.

You can use Microsoft Graph to query for the user's OneDrive for Business location, using this request:

GET https://graph.microsoft.com/v1.0/me?$select=mySite

While will return a payload including the user's ID and the mySite URL. This is a more robust alternative than the discovery service.

Additionally, you can use the Graph API to access nearly all of the OneDrive API capabilities as well, which lessens the need to know the OneDrive for Business site URL in the first place.

I realize this may not be the answer you're looking for, but it's our recommended approach now.

**Comment by mattGuima** [comment]
Hi,

I know the ticket is closed but I just wanted to add to the discussion. Thanks for that reply rgregg by the way. The mysite selector is not actually well documented as an alternative to the discovery service in the Graph Api documentation, so this post was a big help to me.

I wanted to add though that using the mysite selection works on the graph api, however, it's a bit awkward to retrieve the actual tenant's url since what it returns it's the full url to the user's personal site so something like https://tenant-address/username/personal/site or something like that. It's nothing that some string.Replace() and string.SubString() mixed with some string.IndexAt() can't solve, but still, would be better if Graph Api could return that information clean in the result object much like the Discovery Service. 

Also, unfortunately, as much as I wanted to use the Graph Api instead of the OneDrive API it's still not fit for purpose for application like mine which need to do upload since it only supports 4MB uploads and there is no chunk upload. So in the end I had to get the user's tenant's via Graph Api but use OneDrive Api for everything else, which is a shame.
