### ISSUE TITLE
File Picker redirect_uri restriction is a big pain point

### ISSUE THREAD

**Issue by arekkas** [OneDrive/onedrive-api-docs#294]
The [file picker SDK](https://dev.onedrive.com/sdk/javascript-picker-saver.htm) is basically missing the point of integration with any serious web application because

- the developer can't test the file picker SDK on a local environment, see #11
- OneDrive requires the source URL to be static. All dynamic source URLs, e.g. `/collections/{id}`, can not be used as it is not possible to pre-register every "flavour" as redirect url in the* "Microsoft account Developer Center"*.

You can read up on frustrated developers encountering these issues [on stackoverflow **from 2014**](http://stackoverflow.com/questions/29973283/onedrive-filepicker-the-provided-value-for-the-input-parameter-redirect-uri-i#_=_) and across this repository.

These limitations render the file picker SDK useless for any use case.

I also tried the new v6.0 SDK but that seem to conflict with my client id: `AADSTS70001: Application '3645e8ff-35d6-xxxxxxxxxxxxxxxxxxxx' is not supported for this API version.`. Obviously, there are no resources on why this is or how this can be resolved. And I'm not the only one:

1. [check this](http://stackoverflow.com/questions/33232754/azure-ad-authentication-using-node-js-passport-returns-not-supported-for-this-a)
2. [this](https://social.msdn.microsoft.com/Forums/en-US/791d29aa-4fc4-4d57-9ff5-d94c0558e0fd/aadsts70001-application-574c1791d632418091e438094a8a3a77-is-not-supported-for-this-api?forum=WindowsAzureAD)
3. [or this](http://stackoverflow.com/questions/22456947/service-bus-for-windows-server-the-api-version-is-not-supported) unresolved question
4. or do a quick search on [Google](https://www.google.de/search?q=microsoft+application+not+supported+for+this+api+version)

I am sorry if this post feels like a rant, but this is one of the most frustrating developer experiences I had during the last month and the most frustrating in comparison to all other leading cloud drive providers, including dropbox and google drive amongst others.

If I am mistaken, please point me at the resources that resolve this. One week of digging through developer resources I am still left confused with all the different Web SDKs / APIs and missing well explained steps to implement the most basic things.

**Comment by rgregg** [comment]
Hi @arekkas!

Thanks for the genuine feedback. We're certainly trying to make the developer experience easier, but we still have some places where things are broken. The "app is not supported for this API version" appears to be an error coming from the Azure Active Directory API, so I'll pass this feedback along to the team that owns it. However, I wouldn't expect this issue to be encountered when using our JS Picker SDK since it only calls the OAuth end point for AAD. If you can get a trace ([Fiddler](https://www.telerik.com/download/fiddler/fiddler4) is our favorite tool) of a scenario where you get this error message we can debug what's going on a lot easier.

In the time since we've answered and closed #11, the team that owns identity has actually enabled localhost URLs to be used as redirect URLs for registered apps. If you've registered an app in Azure Active Directory, you can use register redirect URLs for both localhost and your domain in the same application. For Microsoft Account registered apps, you can only register one or the other (so you'll need to use separate app IDs for localhost testing and for production, which is a good idea anyway).

The feedback about the redirect URL for the file picker not support dynamic URLs is something we're addressing for the next update. We'll allow the developer to specify a custom redirect URL that doesn't have to be the page hosting the file picker to make sure that it can be supported on more dynamic pages than the current SDK allows.

We're also working to incorporate [Microsoft Graph API](https://graph.microsoft.io) and [App Model v2.0](https://azure.microsoft.com/en-us/documentation/articles/active-directory-appmodel-v2-overview/) into the next version of the JS file picker SDK to streamline the authentication story and only require a single app registration (instead of needing two client_ids to support AAD + MSA). We're working to get this next version out as a refresh to the current preview over the next couple of weeks.

Again, thank you for sharing your voice and helping us find the places that we can do better.

**Comment by arekkas** [comment]
I @rgregg thank you for responding to this issue so timely and honest. I will take a closer look at Azure AD as I'm currently using a Microsoft Account app and I will try to figure out why localhost fails as redirect URL on my end - I guess it has to do with declaring a variety of ports (3000, 4567, ...) on localhost as redirect endpoints.

I am very glad that these kind of issues are taken seriously and am happy to be able to contribute in making the developer experience easier. Please let me know if I can help other than pointing at issues I stumble upon.

I will deep-dive into Azure AD and the other things you mentioned and come back with hopefully positive news once I am able to get everything working as it should.

**Comment by arekkas** [comment]
I didn't have the time to go through AD yet and I'm not confused if AD costs money for the use case described above.

I was however able to get the redirect stuff working by registering one app per port. Thanks for pointing this out!

**Comment by rgregg** [comment]
AAD is free, although you need either a free trial subscription for Azure or a pay-as-you-go subscription. As long as you only use the Azure AD feature, you wouldn't be billed, but I'm glad you were able to get things registered using different ports.

**Comment by arekkas** [comment]
Perfect, thanks!

**Comment by txix** [comment]
@rgregg Is there any ETA on the dynamic URL support of redirect URI's?

**Comment by danilogiulio** [comment]
redirect URL for the file picker not support dynamic URLs still not working. Even option:

advanced: {
    redirectUri: "https://contoso.com/filePickerRedirect.htm"
  }

does not work at all. Any update?
