### ISSUE TITLE
Duplicate items from view.delta when paging

### ISSUE THREAD

**Issue by desmondyeung** [OneDrive/onedrive-api-docs#295]
I'm seeing this behavior using a OneDrive for Business account, haven't tested it with OneDrive Personal.

What I observe is that if I change an Item, all of it's parent folders up to root also appear in the response.

A bit of a contrived example, but if I modify 'Nested Document1' and 'Nested Document2' and set the page size to 1 with the following hierarchy:

```
root
  => Top Level Folder
      => Nested Document1
      => Nested Document2
```

When I make the request ```GET /drive/root/view.delta?$top=1```

The first page actually contains 'Top Level Folder' and it's parent 'root'
```['Top Level Folder', 'root']```

Then requesting the '@odata.nextLink', the second page contains 'Nested Document1' and it's parent up to 'root'
```['Nested Document1', 'Top Level Folder', 'root']```

Again when requesting the '@odata.nextLink' to get the last page it contains 'Nested Document2' and it's parent up 
```['Nested Document2', 'Top Level Folder', 'root']```

Is this the expected behavior?

**Comment by townie** [comment]
+1

**Comment by rgregg** [comment]
Yes, this is by design. With view.delta, we always return all of the items in the hierarchy above the modified items to ensure that you have all of the items required to place that item into the correct place in the hierarchy. If you ask for a page size of 1, we return one "changed item" and then all of the parent items of that item. There is definitely overhead in doing it this way, but it helps to ensure the integrity of the data set you generate from the results.
