### ISSUE TITLE
OneDrive personal and business use same api but give different response

### ISSUE THREAD

**Issue by raccoon4me** [OneDrive/onedrive-api-docs#298]
Hi everyone, 

i have a django app that have for ambitions to sync in backend all the items i have in the drive.
For business, i call view.delta on root and i get at once all the files:
 their id : item["id"]
and their path: item["parentReference"]["path"]

Doing the very same with personal account, assuming the same api should work the same way, but no, 
there is no such item["parentReference"]["path"] for example:

"parentReference":  {
        "driveId": "c3b79f20e3bd7378",
        "id": "C3B79F20E3BD7378!103"
      },

Would i be possible to harmonise the API across all the products ?

Kind regards

**Comment by rgregg** [comment]
@raccoon4me: Our goal is certainly to have the same API behavior across all of the services that OneDrive API works with. However, OneDrive, SharePoint, and OneDrive for Business are all separate services and from time to time the behavior may be different between them.

The documentation is the source of truth for what to expect to work consistently across all end points.

In this case, the documentation specifically calls out that **path** isn't available when using view.delta:

> The parentReference property on items will not include a value for path.

I know that doesn't make it better though. However, using path and view.delta together is a recipe for data loss and sync issues. You need to use the item IDs to make sure that you properly record all changes and don't lose track of operations like moving a file or folder, which may cause inconsistent path data to be reported.

**Comment by raccoon4me** [comment]
Thanks a lot rgregg for your answer, nevertheless, 
if there is no path in the json respomnse, and i want to synchronize only one folder with the following structure:

/a/b/c/d/{file1, file2, file3}

If i want to synchronize everything in folder a (id="a1")
All the files in the "d" directory {file1, file2, file3} have for parents, not the id of the root folder a, BUT  the id of the directory "c", and i have no idea what is the id of the "c" directory since all i know is the id of the "a" directory.

And no, i don't want to use the view.delta per path, as in onedrive business is not available, so there is no way i can use the same method for business account and personal accounts as they do not share the same response :/.

**Comment by daspek** [comment]
@raccoon4me:
If I understand correctly, you're just trying to sync folder 'd' and ideally you would call view.delta directly on 'd', but since OneDrive for Business only allows you to sync at the root, you want to call view.delta on the root for both services. Since you're still only interested in changes under 'd', you want to know which view.delta changes are safe to ignore. In OneDrive for Business you're doing this by looking at the 'path' property, which isn't available in OneDrive for Consumer.

This approach mostly works, except if a file moves from 'd' into 'b', it will show up with the new path, and you won't realize that it got removed from 'd' unless you also remember its `id` and notice that its path got changed. This means your app must remember `id`s. This is what @rgregg is referring to when he says that using `path` alone without analyzing `id`s can cause data loss.

Since you need to use `id`, you don't really need the path at all. As you sync, you need to keep track of the `id`s that get returned and build up the item hierarchy, including the 'd' folder you care about. When you're done, you will know the `id` of 'd' and all of the items under it. You can then throw away any `id`s that aren't in the hierarchy you care about. When you call view.delta later to get changes, you can ignore any items whose `id` or parent `id` doesn't match one of the ones you care about.

I hope this helps.
daron

**Comment by raccoon4me** [comment]
@daspek 

Thanks a ton for having taken time to give me such a precise answer, really much appreciated :)

Nevertheless, I'm not just trying to sync folder 'd', at the opposite, I trying to sync folder 'a', so every single file from folder 'a'. Indeed when my users login, they can subscribe to folder ONLY at root directory, so I give them the choice of selecting all the folder they have in the rot directory. In this case 'a'.
So syncing 'a' will also include b, c and d of course. So my guess is that if a user move the file from 'd' to 'c' I'm still saved thanks to the path

But I just realize thanks to your answer that it might happen a corner case:
 if the user move file from a,b,c,or d to an another folder of the root directory that the user didn't subscribed to, ideally I should delete it in my backend but deletion only occurs when I got the delete key in the Response of view.delta, mhm I need to send this stuff to testers Monday first hour.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
