### ISSUE TITLE
NuGet package?

### ISSUE THREAD

**Issue by saguiitay** [OneDrive/onedrive-api-docs#30]
Is there a plan to create a NuGet package for the new API?

**Comment by jsinh** [comment]
Haven't heard of it from the team yet anywhere, but I have initiated a [work-in-progress repo](https://github.com/jsinh/onedrive-dotnet) for it. Soon to see [first multiple platform supported](https://github.com/jsinh/onedrive-dotnet/milestones) publish to NuGet and grow over time.

Meanwhile awaiting for more info from official team

**Comment by rgregg** [comment]
We know how important SDKs are and we're working on building official OneDrive SDKs for the new API. However, we didn't want to hold up the API release because we didn't have SDKs ready yet. We're working with the [VIPR tool](https://github.com/microsoft/vipr) to generate well designed and easy to use SDKs for our service.
