### ISSUE TITLE
eTag changed after uploaded.

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#308]
Hi there, 

I suffered a weird problem.
after I upload a file to /first_folder/target_file
I got the metadata returned with etag: aNTRERkRBOUQ5Q0U0RkRFRCE0NTA1MzEuMA

then I call api to retrieve metadata for target file, 
I got the metadata returned with eTag:aNTRERkRBOUQ5Q0U0RkRFRCE0NTA1MzEuMw

Two eTags are different.

I do nothing between two API calls.

Here target file is a picture in jpg format.
I got the same issue if the target file is mp3.
I think about media type files, server does something on them?

I do the same thing on regular plain text file, the eTag does not changed, however.

Is this a bug or there is something automatically applying on JPG/media type files?

Thanks.

**Comment by mikechiu1012** [comment]
hi, is there any update ?

**Comment by ificator** [comment]
This is expected behavior, and the reason why is pretty close to what you've inferred.

There are a class of files (photos and audio files are good examples) that contain metadata that will be exposed by our API. To avoid performance issues on upload we accept the files without doing any processing and return as fast as possible, however there is background work scheduled to pull the metadata from the binary and persist it back in the metadata so it can be returned by the API. Since this process updates the metadata it will result in a new ETag value so that clients can tell that there's new state available.

As a result of the ETag change the following will also happen:
1. `view.delta` will return the file the next time it is invoked with a previous delta link
2. A notification will be sent via webhooks if a subscription is present

**Comment by mikechiu1012** [comment]
OK, I see.

I am just a little confused cause we need to compare if item changed or not, but now its differed between eTags returned after upload and metadata.

Now I tend to not use eTag to compare but check mtime, size or hash...etc.
Or is there any suggestion about this?
Thanks.

**Comment by ificator** [comment]
If you're checking size/hash it sounds like you're only interested in detecting changes to file content - is that correct? Assuming it is, you could look at using the CTag, which will only change on content changes.

**Comment by miwarin** [comment]
Hi.
I changed the remote content. However, after that, cTag was not included in delta. delta contained an eTag. 

Has the onedrive implementation changed?
