### ISSUE TITLE
What is the hard limit of "top" per response?

### ISSUE THREAD

**Issue by shuson** [OneDrive/onedrive-api-docs#319]
First thing first, the document [optional-query-parameters](https://github.com/OneDrive/onedrive-api-docs/blob/master/odata/optional-query-parameters.md) mentions:
>The number of items to return in a result set. The OneDrive API may have a hard limit that prevents you from asking for more items per response.

Could you explicitly tell us what is the exact number, if possible?

Thanks for providing API doc, as always.

**Comment by rgregg** [comment]
The maximum items per page limit is 1000 currently.

**Comment by shuson** [comment]
One more thing ,will this maximum number change according to different releases of new API?

**Comment by rgregg** [comment]
It's certainly possible the hard limit will change in the future. However, it would likely only increase. Decreasing the maximum item limit would probably be a breaking change (at least if we were to change it in such a way that we return an error when trying to request larger than the new limit). You should built your app to not depend on the number of items being returned in the page though, so that in the future if you ask for 1000 items and we only return pages of 600 items, you wouldn't be broken.

We recommend not using a paging value larger than the default size of 200 items per page though for performance and network connectivity reasons, especially for native clients and mobile apps.

**Comment by shuson** [comment]
Great, thanks for your prompt reply and advice. 

Summary:
1. the top's hard limit is 1000 in current version(Mar 2016)
2. this limit number may change in future API
3. don't rely on this limit.
4. think of performance, the default top value 200 is recommended.

Thanks to Ryan again.

Ticket closed.
