### ISSUE TITLE
Trying to create a folder with same name twice does not throw exception

### ISSUE THREAD

**Issue by ginach** [OneDrive/onedrive-api-docs#323]
Reported by @kinex, copied over from [here](https://github.com/OneDrive/onedrive-sdk-csharp/issues/91).

I have an unit test which checks that trying to create the same subfolder twice should throw an exception. Here is the code which creates the folder (I call this twice):

 var folderToCreate = new Item { Name = "1", Folder = new Folder() }; 
 var item = await this.OneDriveClient.Drives[this.DriveId].Items[this.Id].Children.Request().AddAsync(folderToCreate).ConfigureAwait(false); 

Earlier an exception was thrown, now it doesn't throw any exception. The second call doesn't seem to do anything (it doesn't even replace the existing folder if it's not empty). Is this some planned change, SDK issue or server side issue?

**Comment by rgregg** [comment]
This is by design. The first time you POST, we return 201 Created. The second time, we return 200 OK (indicating that the item already existed). In a RESTful API design, you've asked (through POST) that we ensure that a folder named "1" exist. That request didn't change between the first request and the second, the end result (a folder named "1" exists) is still true.

If you want to change the behavior to fail in the second request, you can add a property to the item to control the behavior:
```
{
"name": "1",
"folder": {},
"@name.conflictBehavior": "fail"
}
```

Using this body for the POST message will ensure that you get the result you expected.

**Comment by kinex** [comment]
API documentation here https://dev.onedrive.com/items/create.htm says "fail" is the default, so why should I need to add that property? I think current default behavior is none of the documented values: "fail", "rename" or "replace". It doesn't fail, rename or replace, it just doesn't do anything if the folder already exists. If this is related to some RESTful APIs internal design or behavior, then it is out of my knowledge. Quite confusing anyway, in my opinion.

But have you changed something related to this during last few months? Because earlier it did throw exception, exactly the same code (and I think also the same version of the C# client SDK).

**Comment by rayluo** [comment]
Very interesting discussion.

That changed behavior described by @kinex may be an (unintended?) implementation change.

But the broader topic is, in terms of RESTful semantics, [what @rgregg described](https://github.com/OneDrive/onedrive-api-docs/issues/323#issuecomment-197726190) is named [idempotency, which is generally only observed in HTTP PUT, but not in HTTP POST](https://en.m.wikipedia.org/wiki/Representational_state_transfer#Example). Therefore HTTP infrastructure will automatically retry PUT but not POST (that is the point of idempodency).

Right now, the [OneDrive create item API](https://dev.onedrive.com/items/create.htm) accepts both POST and PUT, but treat them in the same way, the behavior difference is only controlled by that "conflictBehavior" parameter. This is quite unique. By any chance, do we consider to differentiate them in such way in future V2.0 (here version is bumped to contain such a breaking change)?

* `PUT /drive/items/{parent-id}/children/{name}` will always behave the "replace" behavior.
* `PUT /drive/items/{parent-id}:/{name}` same as above
* `POST /drive/items/{parent-id}/children` will behave as "rename" by default, or "fail" if we still maintain that "conflictBehavior" parameter;

Just some food for thought.

**Comment by ificator** [comment]
We've added cleaning up PUT/POST/PATCH to the list of work we want to do the next time version the API, and I've linked it to this GitHub so these comments can be taken into account.
