### ISSUE TITLE
Auth without user/password input

### ISSUE THREAD

**Issue by andriipetrenko** [OneDrive/onedrive-api-docs#325]
Hi, I'm going to use one OneDrive account for storing all clients uploaded files in MVC project. So I'm going to use "internal" OneDrive credentials. The final User wouldn't have to sign in. I have to use my appID, secretID, userName and password from the Web.config to sign in OneDrive, take the list of uploaded files and show them for the final User as a part of one of my MVC pages. Then final User can view/edit/save any document on the OneDrive.
Is it possible? And in what scenario I have to use my credentails to Auth to OneDrive in such "silent" mode (without showing the dialog with User/password)?

**Comment by rayluo** [comment]
If I understand correctly, you will need to use your credential initially
to obtain a refresh token, and then your app will no longer need your
password to interact with onedrive. You will probably still need a way for
your end user to authenticate themselves, though. I would recommend you to
take a look into oauth2, in general.


Regards,
Ray

--
Ray Luo

**Comment by MortenChristiansen** [comment]
We have a similar requirement. We represent multiple customers and for each customer we currently have a single user to store shared documents on. This user does not represent any concrete person, so the system needs to be able to log in as the user without interaction from a person. A person could in theory login once to obtain the refresh token but since the refresh token expires after a maximum of 90 days, this is not a viable solution. Our current code is using the CSOM api which allows the user to be authenticated programmatically using a username/password combination but this does not seem to be possible with the REST api. Is there any way to be able to authenticate as a user permanently without any form of expiration? If not, are there any plans for this - either concrete or potential?

**Comment by rgregg** [comment]
For SharePoint and OneDrive for Business, there are a few options. AAD supports two flows that are not user-interactive: [Service-to-Service calls with Client Credentials](https://msdn.microsoft.com/en-us/library/azure/dn645543.aspx) and [Username / Password](http://www.cloudidentity.com/blog/2014/07/08/using-adal-net-to-authenticate-users-via-usernamepassword/) flow.

I'd also add that using OneDrive or OneDrive for Business in this way is not supported. OneDrive is designed around storing a single user's personal files and sharing them with a small group of people. The scale and expectations for how data is accessed are limited based on these expectations to where allowing hundreds or thousands of users to "proxy" requests through a single user account to a OneDrive will likely exceed the throttle limits of the service.

SharePoint team sites and groups on the other hand are designed to support this scenario and would likely provide a better experience. However, you may find that if you are looking for just a backend system to store data that shouldn't be exposed to users that [Azure Files](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-files/) or [Azure blob storage](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-blobs/) provides a significantly better experience for your scenarios.

**Comment by MortenChristiansen** [comment]
It should be said that the proxy user is a workaround for the fact that we cannot reliably access an arbitrary user's files without them being online. We do not store username/password for every user and since the refresh tokens expire we have been forced to use this model.

**Comment by MortenChristiansen** [comment]
But thank you for the resource, I will look into it and see if it can help us.

**Comment by rgregg** [comment]
@MortenChristiansen Can you elaborate on the expiration of refresh_tokens issue?

**Comment by MortenChristiansen** [comment]
It was my understanding that refresh tokens become invalid after a maximum of 90 days, but your comments on issue #124 indicates that it is 6 months instead. Either way, the problem is that we need the system to access documents in OneDrive (for business) on behalf of the the user so we cannot rely on the user being present for entering his credentials.

Just to put our use case in context, we provide a system for schools that 

Btw, you link to the blog describing how to enable username/password login mentions that it is not supported for websites, so it does not work for us. Also, the relevant method overload has been removed in the ADAL library from version.

**Comment by rgregg** [comment]
Thanks for the details @MortenChristiansen. We've heard this loud and clear and are working with the Azure Active Directory team to find a solution. In the mean time, the expiration time is 90 days for AAD, and 6months for MSA issued refresh tokens. MSA tokens can be infinitely extended by using the new refresh_token provided when redeeming an access_token. AAD also renews the refresh_token when redeeming, but after 90 days the user is forced to sign in again.

I'll update this thread when I have more details about the AAD plans.

**Comment by MortenChristiansen** [comment]
That sounds great.

We have similar integration with Google Drive and they have the Service Account concept which has been really great to work with. Something like that would be perfect ;)

**Comment by ravirajesh** [comment]
Yes, it is possible without any user intervention i.e. user credentials end user can view, can edit and can print.... I hope following links will be helpful...please find the following links...

	https://dev.onedrive.com/auth/aad_oauth.htm
	https://dev.onedrive.com/items/copy.htm 
	https://dev.onedrive.com/items/sharing_createLink.htm
	https://www.youtube.com/watch?v=TjuJE7Zc1Qk

**Comment by MortenChristiansen** [comment]
@ravirajesh Your first link specifically mentions that the user must sign in via the browser, so that does not work.

**Comment by castorix** [comment]
I have a similar application in C/C++ where I access my OneDrive and I simply generate login.live.com & account.live.com requests with user/password (the main url is extracted from "urlPost:'" from login.live.com answer with /oauth20_authorize.srf).
I had posted a [question  on stackoverflow](http://stackoverflow.com/questions/39555612/getting-download-links-from-onedrive-filenames-without-sign-in-with-user-passwor?noredirect=1#comment66437273_39555612)
because I was affraid that my user/password could be decrypted, but apparently not.

**Comment by cyberjoac** [comment]
Hi, do you have ETA for support of service account ? Thanks

**Comment by yusef-ho** [comment]
@rgregg  Hello... how long it gonna take, it's almost two year... since the issue...
thanks
