### ISSUE TITLE
Authentication Cookie for OneDrive for Business API

### ISSUE THREAD

**Issue by youseke** [OneDrive/onedrive-api-docs#327]
Not sure if I can ask the question here but couldn't find another place. For some reasons our product can't use the OAuth token for the authentication, instead we used the FedAuth and rtFa cookies to access to the API and it worked fine until last week, since when a 403 error response with an accessDenied code kept being returned by OneDrive for Business API. My question is that do I have an alternative or have to use the OAuth token in the future. Hope someone can help me please. Thanks a lot in advance.

**Comment by rgregg** [comment]
@youseke: The OneDrive API requires OAuth bearer tokens to work. There was a brief window of time where the API would accept cookies, but that was a bug that has since been fixed.

There are a number of different options for generating OAuth tokens that might be a better fit for your app depending on the scenario. Have you checked out the [ADAL library](https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-libraries/) and the support for the various authentication methods included in it?

**Comment by youseke** [comment]
@rgregg  Many thanks for your answer!! I will check the library. Meanwhile, I wonder if you know whether I could continue to use SharePoint 2013 REST APIs to access to OneDrive for Business. (Right now I could use the cookies for the authentication to access OneDrive for Business through the API)

**Comment by rgregg** [comment]
Yes, you can continue to use the SharePoint REST APIs to access OneDrive for Business.

**Comment by youseke** [comment]
Thank you for the reply. That's a relief!
