### ISSUE TITLE
Hosting a website across multiple user's OneDrive accounts

### ISSUE THREAD

**Issue by dumbledad** [OneDrive/onedrive-api-docs#335]
I'm developing a phone app that involves users sharing collections of enhanced photos. Our original plan was to store the photos ourselves in leased Azure blob storage, but a team member has suggested that we instead save the enhanced photos out to our users' Dropbox / Google Drive / OneDrive accounts. Our website would still allow people to share their collections, but the images on our website would be hosted in each user's Dropbox / Google Drive / OneDrive account.

Is this allowed for OneDrive? The OneDrive SDK has a Thumbnail.Large property which gives me a direct URL to a large thumbnail of an image on OneDrive, but is it OK to use that as the image src in my app's website? It [appears to be OK with Dropbox](https://www.dropboxforum.com/hc/en-us/community/posts/204758803-Hosting-a-website-across-multiple-user-s-Dropbox-accounts), but I wanted to check that this usage scenario—a site whose image assets are spread across all its users' OneDrive accounts—is OK with OneDrive?

**Comment by dumbledad** [comment]
N.B. This is reposted from the OneDrive SDK issues list [here](https://github.com/OneDrive/onedrive-sdk-csharp/issues/82#issuecomment-206024177)

**Comment by rgregg** [comment]
Yes, using the Thumbnail URL in an img src tag would work, however these URLs are short-lived so you would need to pull that data frequently (every time the page loads is too frequently though). Otherwise, you'll end up with broken images when the URLs expire.

The other downside with this approach is that the URL is different every time you request it, which means that this approach won't allow you to get the most benefit from the browser cache.

A more recommended approach would be to download / cache the thumbnail images in your app and stream the image bytes directly from your app. That way you have control over cache lifetime and can ensure a high quality user experience without broken images.
