### ISSUE TITLE
SharePoint /drives request does not include SitePages document library

### ISSUE THREAD

**Issue by desmondyeung** [OneDrive/onedrive-api-docs#337]
Regarding the  ```GET /drives``` request, in the documentation it states: 

```"When using OneDrive API with a SharePoint team site, this API returns the collection of document libraries created in the site."```

When I attempted this, it enumerated the following (user created document libraries omitted):
```
[
  "Shared Documents",
  "FormServerTemplates", 
  "SiteAssets",
  "Style Library"
]
```

This does not include the SitePages document library. Is there a reason this document library is excluded?

The OneDrive API has some great features over the SharePoint 2013 API and I'd like to avoid having to mix the use of both APIs just to access this one document library.

**Comment by expandrive** [comment]
@desmondyeung what endpoint do you hit to get /drives to succeed? tenant.sharepoint.com/_api/drives doesn't work - and tenant-my.sharepoint.com/_api/v2.0/me/drives doesn't seem to work?

**Comment by rgregg** [comment]
@expandrive Can you create a new issue for that? This thread is about a particular document library not be returned from the drives collection.

**Comment by rgregg** [comment]
@desmondyeung I'm investigating why Site Pages is not returned in the list.

**Comment by desmondyeung** [comment]
@rgregg any update on this?

**Comment by rgregg** [comment]
Hi @desmondyeung.

Thanks for the ping. This is "by design" because treating Site Pages like a standard document library causes side effects that will break the way site pages are supposed to work. We're looking into options for how we can provide a comprehensive API story around managing/working with Site Pages in the modern REST API space, but don't have an ETA for when we'll have something more to announce.
