### ISSUE TITLE
Cannot using Javascript picker for Mobile HTML5 application

### ISSUE THREAD

**Issue by minhkte** [OneDrive/onedrive-api-docs#343]
I am trying to use Javascript picker in one of my HTML web application and it's failed. 
My HTML5 application is kind of local HTML run on Webview/webkit.
In the API setting, only one action is Web/Mobile.
1/ If I choose Web, it's require Uri redirect but my app is local HTML so cannot give any public Uri with https, http:/. .. etc.
2/ If I choose Mobile, automatic provide Uri but it's not work at all. 

How to achieve it in the LocalHTML5 so that I can use it in my Mobile Hybrid app.

**Comment by rgregg** [comment]
The JavaScript picker is designed to be used from a hosted web application. I don't believe you can make it work for local HTML files, since as you mentioned you cannot establish a valid redirect URI.

Depending on how you are building your app, you may be able to use the native file picker frameworks for iOS, Android, and Windows to enable selecting files from OneDrive through your app.
