### ISSUE TITLE
Onedrive Js Sdk error

### ISSUE THREAD

**Issue by as247** [OneDrive/onedrive-api-docs#360]
I got this error while trying to setup file picker
[OneDriveSDK Error] invalid format for client id '000000004C18C50E' - AAD: 32 characters (HEX) GUID
Please help, thanks you

**Comment by rgregg** [comment]
@as247: If you are using the v7.0 picker SDK, you need to register a new app ID through the new Microsoft developer portal: https://apps.dev.microsoft.com

**Comment by as247** [comment]
Thank you @rgregg . but it's need url in https, are we able to make it work on non https pages?
![image](https://cloud.githubusercontent.com/assets/2641656/15135824/e49ea2aa-16a4-11e6-800b-e19de1720c4b.png)

**Comment by rgregg** [comment]
The new app portal requires HTTPS redirect URLs unless the URL is localhost. You can continue to use the v6.0 picker SDK if you need a non-HTTPS end point.

**Comment by GeorgeA318** [comment]
@rgregg I'm having the same problem using v7.2. At first I thought it may have been caused because of localhost but the problem continued on a live demo of my site. Generally I get 
> uncaught exception: [OneDriveSDK Error] errorType: unknown, message: invalid format for client id '0000000040xxxxxx' - AAD: 32 characters (HEX) GUID
using v7.0 or higher while the error that 
> The provided value for the input parameter 'redirect_uri is not valid.
for lower. Is there something wrong with my Target or Redirect URLs?

![image](https://user-images.githubusercontent.com/17744621/35090312-f15cb4c6-fc41-11e7-8a2e-d8880615aff6.png)
