### ISSUE TITLE
O365 with federated login

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#361]
Can anyone please provide details for federated login, since for ODB the authentication process is failing.

Cant get code from the very first webservice call, since it is getting redirected to organization page once username and password is provided.

**Comment by rgregg** [comment]
Hi @ankit-ankuagrawal:

While everything should "just work" through OAuth 2, it's best to use a supported ADAL library to handle federated authentication scenarios since there are a number of different paths potentially involved. There are ADAL libraries for all the major app development platforms that make it pretty easy to consume from any app.

However, if you're unable to use ADAL, if you can provide any more details (error message, request-ids, Fiddler trace, etc) we can take a look at what's going on.
