### ISSUE TITLE
OneDrive for Business, App Only Token, marks all uploads as "SharePoint App"

### ISSUE THREAD

**Issue by Deblanko** [OneDrive/onedrive-api-docs#362]
With the OneDrive for Business API I am unable to configure the name of the user uploading the file.
I am using AppOnly token and UPN to perform the upload but there seems no way to configure the user name for the owner of the uploaded file, it is always "SharePoint App".

Ideally it should be the display name of the user associated with the UPN, or settable by an argument in the upload API.  However we cannot event customise it in Azure to use our App's name.

This can cause confusion to users that upload files using our app and then view files in the web interface

**Comment by ificator** [comment]
Unfortunately the only way to create file AS another user is to impersonate them via an app+user token. An app-only token, by its nature, doesn't include any user information and it cannot be provided by a back channel. Our API supports multiple facets of identity, and so in this scenario we just don't return any user information for the creator (I.e. it only has an application).

Unfortunately the UI appears to simply expose `SharePoint App` - we'll follow up with the UI devs to see if there's something we can do here.

**Comment by dtheodor** [comment]
I think both use-cases are valid when using an app-only token. You may want to fully impersonate the user, and upload files so that it appears that the files were uploaded by the user (a user token is not an option as it defeats the whole purpose). Or you may want visibility to the fact that a special application account uploaded the file  (in which case something more descriptive other than `Sharepoint App` is needed, like the application's name).

I think the first use-case could be covered if the API supported modifying the Author/Editor of files and folders. Is this supported already in Sharepoint REST API? I have unsuccessfully attempted to do that, and posted an unanswered question about it at http://sharepoint.stackexchange.com/questions/199366/setting-a-files-author-editor-through-a-rest-api

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
