### ISSUE TITLE
Why is the file size will change

### ISSUE THREAD

**Issue by lilin007007** [OneDrive/onedrive-api-docs#37]
When a PNG file is displayed in win7 operating system disk file size is 158 bytes, and the file is uploaded to onedrive display the file size is 376 bytes, and why?

**Comment by rgregg** [comment]
The OneDrive API returns the size of the largest stream associated with that file that is stored in our system. 99.99% of the time, this is fine, because the file uploaded is larger than thumbnails or other content that we attach to the file. For very small images though, it's possible that our thumbnail logic generates a larger file size than the original image. When this happens, the size returned by the API is different than the size of the image.

We have a bug tracking changing this behavior so that we always return file size, but since the # of occurrences where this happens are low, we've been prioritizing adding new features first.

**Comment by rgregg** [comment]
Please consider adding this to our [OneDrive User Voice](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) page to allow others to vote on this and help us determine the priority of the fixing this.
