### ISSUE TITLE
Thumbnail in Onedrive for Business API

### ISSUE THREAD

**Issue by jepz20** [OneDrive/onedrive-api-docs#396]
I’m using the Onedrive for business Restful API to save image into onedrive.
When I try to retrieve the thumbnails using the following method
 https://dev.onedrive.com/items/thumbnails.htm#retrieve-a-single-thumbnail
I expect to receive the following response, where the url can be put in an image tag directly:
`{
  "width": 100,
  "height": 100,
  "url": "http://onedrive.com/asd123a/asdjlkasjdkasdjlk.jpg"
}`
However the response I'm receiving is as follows:
`{
"@odata.context": "https://laureatelab3-my.sharepoint.com/_api/v2.0/$metadata#oneDrive.thumbnail",
"height": 500,
"url": "https://laureatelab3-my.sharepoint.com/personal/cohort_spain_support-ued_laureatelab_net/_api/v2.0/drive/items/01GXOESSRT6WVEXP2IJ5HK3JRMPDJPTNNR/thumbnails/0/large/thumbnailContent",
"width": 750
}`
And the only way to serve the thumbnail is to request the url in the response  with an authentication header that contains the access token, receive a blob and display the image through it.

**Comment by rgregg** [comment]
Hi @jepz20: This is a *bug* that we're working on fixing. You are correct that the expected behavior is that you can use the returned URL directly in an `img` tag, but that right now the URL returned requires an authorization header. Since this has been broken since we shipped, some developers have worked around it by downloading thumbnails using XHR and loading the data into an `img` tag using data URIs.

We hope to have this resolved over the next few weeks.
