### ISSUE TITLE
How to cancel range download

### ISSUE THREAD

**Issue by testingash** [OneDrive/onedrive-api-docs#398]
Hi,

In https://dev.onedrive.com/items/download.htm range download is possible with response 206. Does there is any specific API to cancel range download as in case of Upload there is cancel Upload session?

Thanks.

**Comment by rgregg** [comment]
There's no need to cancel a range download from the service perspective, since downloading a file range is a stateless operation. However, if you start downloading a range and decide you don't need to continue to download the range, the client can abort the connection using the semantics of your HTTP client. Not all HTTP clients allow cancelling transfers however.

**Comment by testingash** [comment]
ok. Thank you. If I have any further cliarifications, I will come back.
