### ISSUE TITLE
Clarify OAuth Scope Documentation

### ISSUE THREAD

**Issue by AAorris** [OneDrive/onedrive-api-docs#4]
I had a hard time finding information on scope for OAuth token creation.
- I read the [OAuth page](https://github.com/OneDrive/onedrive-api-docs/blob/4475eada2a725b4ba640eec9edde66a58bae5ca6/auth/msa_oauth.md)
- I searched the repository for "scope"

There are actually values posted [here](https://github.com/OneDrive/onedrive-api-docs/blob/4475eada2a725b4ba640eec9edde66a58bae5ca6/auth/msa_oauth.md#authentication-scopes). These don't seem to show up well in the repository search, and the links in the above section skip down to token and code flow, which may cause users to skip over it.

Does this seem like an issue worth starting a conversation on?

**Comment by AAorris** [comment]
In the end, I wanted to give a my app full access to my account for development, and I used something like this with some level of success.
```
https://login.live.com/oauth20_authorize.srf?client_id={id}&scope=wl.offline_access wl.calendars wl.events_create wl.skydrive_update&response_type=token&redirect_uri=https://login.live.com/oauth20_desktop.srf
```

**Comment by AAorris** [comment]
There are actually values posted [here](https://github.com/OneDrive/onedrive-api-docs/blob/4475eada2a725b4ba640eec9edde66a58bae5ca6/auth/msa_oauth.md#authentication-scopes). They don't seem to show up well in the repository search, and the links above skip down to token and code flow, which may cause users to skip over it.

**Comment by rgregg** [comment]
Good question. Do you have any suggestions for how to make it more discoverable?

**Comment by mimisasouvanh** [comment]
Perhaps we can link "scope" in the first paragraph to the Authentication scopes section.

**Comment by AAorris** [comment]
@mimisasouvanh I like that idea.
I think a troubleshooting section lower down will also help users figure things out if they run into trouble.

**Comment by shierabisdak** [comment]
In the Response samples under the Token Flow section:
https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/msa_oauth.md#token-flow

I noticed the following scopes:
- onedrive.full
- onedrive.info

These are not included nor described in the Scopes table, but due to curiosity, I tried them out.
However, the scopes do not exist, based on the responses that I got.

Don't you think it is better not to mention these scopes in the samples?

-----------------------------------------
Here is the response that I got when I tried to use these scopes:

http://myredirecturi.com?error=invalid_scope&error_description=The%20provided%20value%20for%20the%20input%20parameter%20%27scope%27%20is%20not%20valid.%20The%20scope%20%27onedrive.info%27%20does%20not%20exist.

**Comment by rgregg** [comment]
Thanks for all the feedback on the auth topic. I've taken elements of your pull request and incorporated them into the docs directly. I didn't accept your pull request because I reformatted some of what you wrote. I've also tried to organize the topic layout a little better so that you can read the scopes before you jump to the auth flows. Thanks for the help in improving our docs!

**Comment by AAorris** [comment]
Thank you too! I'm glad these docs are here.
