### ISSUE TITLE
[ODB] Simple upload sometimes response 400 with error in html format.

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#400]
Hi there,

I am upload 10K files to onedrive for business and sometimes I got response:
'400 Bad Request' with error in html format:

request:
`PUT /_api/v2.0/me/drive/root:/Mike/24/picture_%20%287%29.jpe:/content HTTP/1.1" 400 311`
response:
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>`

Here are two questions:
1) Why 400 response return.
2) Error format

There is not token expiration or malformed arguments because most files successfully uploaded.
And it's hard to handle response 400 cause we will not retry due to such response and no detailed information further(like which part is bad formed.).
Please help to check this, thanks.

**Comment by ificator** [comment]
Hey @mikechiu1012, do you have a request id from the response headers that you could give us? That'll let us drill in and see how this malformed response was generated.

**Comment by amagliul** [comment]
Just to chime in, I'm just going through some user diagnostic data and I happened to come across a 400 HTML response too. 

I can see the reason why the request failed (file has an end of text char in it for some wacky reason), although the HTML instead of JSON response is unexpected.

![screen shot 2016-06-30 at 9 30 02 am](https://cloud.githubusercontent.com/assets/5349954/16496247/e333262e-3ea5-11e6-9f74-2a2227b5a138.png)

**Comment by ificator** [comment]
@amagliul Do you happen to know what kind of request was being made? If I had to guess, based on the response body you provided, you're probably hitting an issue whereby HTTP.sys is rejecting the request for containing "illegal" characters (I quote it because they aren't actually illegal) before our code is even executed. We're in talks with the HTTP.sys team to see what we can do on that front.

**Comment by amagliul** [comment]
@ificator Somehow missed this too. I believe this was on an upload attempt.

**Comment by daspek** [comment]
Just wanted to provide an update here. The HTTP.SYS team has taken the fix, but because it's in such a deep component, it's not something we're able to patch in the near term. However, we will have the fix in a future upgrade.
