### ISSUE TITLE
Access shared folder in OneDrive for Business

### ISSUE THREAD

**Issue by jdeniau** [OneDrive/onedrive-api-docs#423]
Hi,

I'm using One drive for business. The `/_api/v2.0/drive/view.sharedWithMe` return a folder, and I try to access this folder detail.

I tried several solutions listed [here](https://dev.onedrive.com/misc/working-with-links.htm) but it seems like nothing is working.

When I try to add the folder to the user's drive, I got the following error: 

``` json
{
  "error": {
    "code": "invalidRequest",
    "message": "Either 'folder' or 'file' must be provided, but not both."
  }
}
```

When I try to "enumerate the content of a shared folder", I got the following one: 

``` json
{
  "error": {
    "code": "unauthenticated",
    "message": "The caller is not authenticated."
  }
}
```

I saw #304 and [this uservoice](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7103641-allow-us-to-access-shared-files-on-sharepoint-and) marking this issue as fixed, but apparently it is not :/

Can you help me with this ? 

Thank you

**Comment by lfcgomes** [comment]
+1. It would be great to know. I'm facing the same problem here. I can see the shared folder but I cannot access it. I also tried to create the remote item in the drive's root, but the sharedWithMe request does not return parentID reference. So, I'm running out of ideas.

@jdeniau any luck?

**Comment by jdeniau** [comment]
No, I am waiting for a response here ;-)

**Comment by jdeniau** [comment]
Tried again and when adding the drive to the root folder I got a 403:
```json
{
  "error": {
    "code": "-2147024891, System.UnauthorizedAccessException",
    "message": "Access denied. You do not have permission to perform this action or access this resource."
  }
}
```

**Comment by rgregg** [comment]
When using shared items and OneDrive for Business, you need a different permission scope. The Files.ReadWrite scope provides access to only the content's of a user's OneDrive for Business. To access shared items, you need to request Sites.ReadWrite.All, which shows up in the Azure Portal as "Read and write items in all site collections". Once you have this scope on your app, and the user has consented to the scope, those calls should work.

**Comment by jdeniau** [comment]
Thank a lot @rgregg , I tried to list the shared folder and it's working. 

I tried adding the folder to my root folder and I got the same error, but it's not important for me if I can list the shared folder detail.

Maybe I can open a PR with the tips you gave me on this page if you are OK with it ?

**Comment by rgregg** [comment]
Certainly, I think getting the docs updated is important and I'd love to consider a PR for it.

The ability to add a shared folder to your root folder is limited to OneDrive Personal. OneDrive for Business does not have that capability.

**Comment by anildbest83** [comment]
I want to add a New folder inside a Shared Folder.

OneDrive Api docs says 'A shared folder can only be added to the root of a user's drive.'

Is there any way i can add folder inside a shared folder?

**Comment by ificator** [comment]
The root limitation only applies to the shared items (i.e. remote items that reference items in another drive). It's easiest to think of such items as pointers to another item - you cannot place items under them because they themselves are not folders, but you can place items under the item they're pointing at.

Say you have a shared folder that looks like this:

```
{
  "id": "98765432!12399",
  "name": "Team Documents",
  "remoteItem": {
    "id": "12345abcde!1221",
    "parentReference": {
      "driveId": "12345abcde"
    },
    "folder": { "childCount": 15 }
  },
  "lastModifiedDateTime": "2015-08-10T13:47:11Z",
  "createdDateTime": "2015-08-10T13:47:11Z",
}
```

If you wanted to create a folder within it you'd want to use the `remoteItem.parentReference.driveId` and the `remoteItem.id` values to craft a request against the real folder like so:

```
POST https://api.onedrive.com/v1.0/drives/{remoteItem.parentReference.driveId}/items/{remoteItem.id}/children

{
  "name": "new folder",
  "folder": { }
}
```

**Comment by vishwajeetsonkar** [comment]
I was able to sync the shared folder from web to my drive but it seems that it had created it own drive under  C:\Users\userName\companyName\username-folderName
On the web it was simple just by going to the "shared with me" tab, then open the shared folder and then on the top you could find a sync button.

But the problem is I can find an API which that "sync" button is using

some how i found out an api but it gives me 400 in response
![screenshot 5 _li](https://user-images.githubusercontent.com/17278038/35964473-db29ec62-0cdd-11e8-90e3-643670b33588.jpg)
![screenshot 7 _li](https://user-images.githubusercontent.com/17278038/35964555-15b9ddce-0cde-11e8-898f-7189f907ae04.jpg)

Don't know what's going wrong plz help
