### ISSUE TITLE
received wrong response (wrong parameter) for access_token (request)

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#43]
did the following steps (grant_type=authorization_code)
step1) requested for authorization_code -> received successfully
step2) using the code(from step1) requesting for access_token -> receives the access_token successfully with other parameters

***the json format received was not as been mention in the github page(https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/msa_oauth.md)

eg
{
  "token_type":"bearer",
  "expires_in": 3600,
  "scope":"wl.basic onedrive.readwrite",
  "access_token":"EwCo...AA==",
  "authentication_token":"eyJh...93G4",
  "refresh_token":"eyJh...9323"
}

the problem is with parameter "authentication_user", never received this parameter in response
![response access_token get advanced rest client](https://cloud.githubusercontent.com/assets/11455759/6776118/a39a33a8-d160-11e4-8ab5-2f516ca24339.png)

we are receiving parameter "user_id" which is not mention on github page

![table for response parameters](https://cloud.githubusercontent.com/assets/11455759/6776204/d9765474-d161-11e4-8ea0-26068ed13ac8.png)

**Comment by rgregg** [comment]
The JSON response has been updated to remove the authentication_token and add a user_id. Neither of these values are used in the OneDrive API, so it's safe to ignore them. As a best practice with all JSON responses, you should expect/allow additional properties to be included in the response and ignore them.

In the OAuth response, the important values are access_token and refresh_token, since those are the values you'll need in the future to pass into the API. The other properties in this response are informational and can/should be ignored.

**Comment by ankit-ankuagrawal** [comment]
ty for response...
 if im a new to your API's, and integrating onedrive using this APIs,  i wouldnt be cming to know which are important or which are not...

**Comment by rgregg** [comment]
I'll update the documentation to be more clear about the required properties.

**Comment by ankit-ankuagrawal** [comment]
@rgregg update the docs for above scenario also

thank u for ur response
