### ISSUE TITLE
OneDrive for Business API resumable upload: get a 401 Unauthorized when uploading a file

### ISSUE THREAD

**Issue by imkk** [OneDrive/onedrive-api-docs#452]
I'm so sorry for asking this problem again, but I didn't get a reply for this problem.[https://github.com/OneDrive/onedrive-api-docs/issues/446](https://github.com/OneDrive/onedrive-api-docs/issues/446)
My problem is that I always get a 401 Unauthorized code when uploading a file(I don not know if there are more this kind of files) named after "《鸟哥的Linux私房菜-基础篇》.pdf", this happens in the progress of uploading fragments.

**Comment by jtdiehl** [comment]
Hi,

I was experiencing the same problem and I eventually discovered that the upload url received from creating the upload session needs to be urldecoded before it can be used in the fragment upload requests.

**Comment by ificator** [comment]
My apologies for dropping the ball on your previous issue - I've closed it so we can use this one to delve in deeper. 

I have a few questions:
1. Are you using an `app-only` token, or are your requests being made on behalf of a user?
2. Do you get the 401 when you choose a filename that's entirely ASCII?
3. Can you provide a new `request-id` like you did for the previous issue? Unfortunately since I let that issue sit for so long what you previously provided isn't useful anymore :(

**Comment by imkk** [comment]
Hi @jtdiehl , this problem has been solved for me and you can check if it is normal now for you.
