### ISSUE TITLE
onedrive.readwrite allways granted

### ISSUE THREAD

**Issue by SirLanceLang** [OneDrive/onedrive-api-docs#456]
I have followed some tutorials here and implemented oauth2 in Visual Studio 2015 using xamarin.
I have played around with Scopes when granting access to the app. Now it seems that even though I only set Scope to wl.basic and offline_access I will get all the read.write rights to Onedrive as well.
This even if I do a logout before loggin in again.

Scope:
![image](https://cloud.githubusercontent.com/assets/7024928/19056683/252a9724-89a1-11e6-99c6-6fe584c0ed4d.png)

Rights granted:
![image](https://cloud.githubusercontent.com/assets/7024928/19056797/cbc49b5c-89a1-11e6-9b2b-d525a140f294.png)

Anybody got a clue?

**Comment by rgregg** [comment]
The returned token from the OAuth2 flow includes all of the scopes the user has consented to for the application, and is not filtered to just the scopes that were requested. If you have previously consented to those scopes, this would be by design.

You can [revoke your consent](https://dev.onedrive.com/auth/msa_oauth.htm#revoking-access) to this application and then log in again, and you should see only the requested scopes.

**Comment by SirLanceLang** [comment]
Fantastic! That really helped me out. Thanks a lot! 👍
