### ISSUE TITLE
Setting expirationDateTime for creating a subscription

### ISSUE THREAD

**Issue by hitheshxenovus** [OneDrive/onedrive-api-docs#463]
How to set this in python it is throwing an error
[subscription] Cannot convert the literal '2016-10-20T23:24.606708' to the expected type 'Edm.DateTimeOffset'.
Time is created from  
datetime.utcnow().isoformat()

**Comment by ificator** [comment]
The problem here is that the datetime value doesn't include the timezone (e.g. in this case it should have `Z` on the end since it's UTC). In python you need to make sure your datetime is "aware" - [this stackoverflow question](http://stackoverflow.com/questions/3401428/how-to-get-an-isoformat-datetime-string-including-the-default-timezone) has a few solutions.

**Comment by hitheshxenovus** [comment]
Thank you I was able to solve it using this:- 

dt = datetime.datetime.utcnow()
dt = dt.replace(tzinfo=pytz.utc)
subscription_time = dt.isoformat()

subscription time contains the current time
