### ISSUE TITLE
Album support?

### ISSUE THREAD

**Issue by assassin316** [OneDrive/onedrive-api-docs#468]
I asked a question on the GitHub C#, cdmayer gave me an answer, I wanted to share it here to see if anyone knows roughly when this feature will eventually be supported:

[https://github.com/OneDrive/onedrive-sdk-csharp/issues/191](https://github.com/OneDrive/onedrive-sdk-csharp/issues/191)

Thanks for your time.

**Comment by rgregg** [comment]
It's definitely on our backlog. However, it's taking more work than originally expected because we want to make sure that all the concepts available in the OneDrive API are available with albums (like path-based addressing, delta support, etc). I don't have an ETA for when the feature will be available yet.

**Comment by assassin316** [comment]
Thanks for the info and the quick reply @rgregg   :)
