### ISSUE TITLE
best way to get basic Collaboration event notifications

### ISSUE THREAD

**Issue by vorio** [OneDrive/onedrive-api-docs#477]
Graph APIs lack basic support when they seem to work once in a while. Then there are so called management activity APIs which no one seem to use because they hardly ever work.

Any other choice other than asking customers to migrate away from Onedrive.

**Comment by rgregg** [comment]
What sort of events are you trying to receive? Just basic file create/modified/deleted events, or something more?

**Comment by vorio** [comment]
Pretty basic ones like share/unshare of file/folder and change of
permissions.

**Comment by PaulWoods4422** [comment]
Upvote for this issue!
I can get change events for permission changes in ODB if the user clicks on the share button from within the individual file view and then adds / removes a user. But not if they click on the share button from the folder view. Also there are no change events at all for link creation / edits.  
In general it would be great if we could have different types of  change events on different actions, rather than having to manage loads of state on our side.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
