### ISSUE TITLE
Potential CRC32 value corruption for some files

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-api-docs#493]
So I noticed that in my OneDrive account, there are some (some but not all) files whose CRC32 attribute returned by OneDrive API is not consistent with what my OS (Ubuntu 16.04) computes. However, their SHA-1 hash attributes magically match, which makes me believe that I have correct copies of the files. So I suspect that their CRC32 value was incorrectly computed or saved in the server.

First observation is that for most files the CRC32 attributes match what the OS tells.

Second observation is that downloading or re-uploading doesn't update the CRC32 attribute, so it seemed not caused by some old and fixed API implementation bug.

Also for some files, CRC32 value is missing yet SHA-1 hash is present.

Files with this problem is not the same set of files affected by https://github.com/OneDrive/onedrive-api-docs/issues/492 but a majority of them seem to overlap.

Any ideas why this occurred?

**Comment by ificator** [comment]
Although most files should have a CRC32, it's possible for older files to not have the values. They would have to be a few years old at this point though.

As for the incorrect values, can you provide us with an `id` for one of these files?

**Comment by xybu** [comment]
One example:

File ID: `D781730A6D2C6611!683817`
Size: 2034668
SHA-1 Hash (API): E9CCAFB09050A1925870D20032A03333981895D2
CRC32 Value (API): B28E2471

On Ubuntu 16.04, the command `crc32` gives `71248eb2`, and `sha1sum` command gives `e9ccafb09050a1925870d20032a03333981895d2`.

**Comment by ificator** [comment]
Perfect, thanks @xybu.

It's as I expected - we're looking at a byte order issue. The API is actually returning the CRC32 in its byte form (and little endian at that), which is admittedly not entirely standard when it comes to how CRC32 values are usually advertised (as a hex integer). To do comparisons you'll need to convert the bytes back to an integer number using code similar to this (example is C# but should be easy enough to translate to whatever language you're using):

```
    string hexBytes = "B28E2471";
    UInt32 reversedCrc32 = UInt32.Parse(hexBytes, NumberStyles.HexNumber);

    UInt32 crc32 =
        (reversedCrc32 & 0x000000FFU) << 24 |
        (reversedCrc32 & 0x0000FF00U) << 8  |
        (reversedCrc32 & 0x00FF0000U) >> 8  |
        (reversedCrc32 & 0xFF000000U) >> 24;

    Console.WriteLine($"{crc32:X8}");
```

In hindsight the API should simple return the hex encoded integer value, but unfortunately such a change would now be considered contract breaking. I have, however, done the following to minimize the pain caused by this:
1. Updated the documentation to call out how the CRC32 value is encoded.
2. Taken note so that the next time the API version is incremented we should look at changing how the value is returned.

**Comment by ificator** [comment]
We've updated the documentation - it should be visible the next time we push it.
