### ISSUE TITLE
Redirect url behind login

### ISSUE THREAD

**Issue by jamieholliday** [OneDrive/onedrive-api-docs#503]
I have 2 Onedrive filepickers on my site. One sits on a page where you must be logged in to view and the other does not require being logged in. I have tried using the same setup for both pickers. I am seeing an issue that I have to supply a redirect url for the page which requires being logged in which does not work as when the popup is launched all I see is my site's login page in the popup window instead of the onedrive filepicker UI.
The page which doesn't require a login to view works fine. Is there a way around this issue as each page hosting the picker needs a redirect url for it to work

**Comment by daboxu** [comment]
hi @jamieholliday , the redirect url is redirected after you logined with Microsoft and you mentioned that it redirects to your website's login page, is my understanding correct? In this case, I would recommend you set the redirect uri on your site to a page doesn't require login in and build a communication way between the redirect uri and your app. The filepicker does relies on the url parameters appeneded on the redirect uri.

**Comment by jamieholliday** [comment]
What I am seeing is after triggering the popup via `window.OneDrive.open()` it that the popup shows the login page of our site so we don't ever get to to the Microsoft login page. If I were to implement the communication between the redirect uri and the app is there an example of what this needs to look like?

**Comment by daboxu** [comment]
hi @jamieholliday , the work flow of oauth login looks like:

0. user logged into your web app at uri "https://foo.com/user/123"
1. on page "/user/123" user click a button invoke picker SDK with option.advanced.redirectUri = "https://foo.com/abc"]
2. in popup up window, it redirects to https://login.microsoftonline.com  verified the app and user consent
3. in popup window, it redirects to  https://foo.com/abc#accesstoken=token

then the SDK lives in "https://foo.com/abc" get the token and making API for you talk to Microsoft Graph API, so if my understanding is correct, the "https://foo.com/abc" for you requires your website's auth.

If in this case, I would let "https://foo.com/abc" requires no auth because the SDK on this page only makes ajax request OneDrive with the access_token and will pass the response to "https://foo.com/user/123" which the user has been verified.

Hope this help you better understand how the SDK works.

**Comment by daboxu** [comment]
hope suggestion above work for you, close it for now and if you have any questions, feel free to reopen it.
