### ISSUE TITLE
OneDrive for business: Incorrect Root URL mentioned

### ISSUE THREAD

**Issue by nav-agarwal** [OneDrive/onedrive-api-docs#517]
In [OneDrive Business authentication](https://dev.onedrive.com/auth/aad_oauth.htm#step-5-make-a-request-to-the-onedrive-api) doc, it is mentioned that to request any API one should first fetch its serviceEndPointUri and then hit GET {serviceEndPointUri}/{api_name}.  serviceEndPointUri looks like "https://{tenant}-my.sharepoint.com/_api/v2.0/me".

While on [ getting started guide](https://dev.onedrive.com/getting-started.htm), root URL for "OneDrive for Business" is mentioned as "https://{tenant}-my.sharepoint.com/_api/v2.0". After running few tests with app-only workflow, I found that serviceEndPointUri doesn't works and errors out with message "Call was made to the default drive, which is not supported for apponly tokens.". 

Can someone confirm which root url to use for app-only workflow?

**Comment by rgregg** [comment]
Hi @nav-agarwal,

OneDrive API does not support app-only workflows today. You need to use the SharePoint API for app-only scenarios with OneDrive for Business. If app-only support for OneDrive APi is interesting to you, please consider adding it to our [UserVoice page](https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer)

**Comment by nav-agarwal** [comment]
But on [stackoverflow](http://stackoverflow.com/questions/33755470/onedrive-for-business-api-daemon-tenant-with-app-only-token) you have mentioned that it works with app-only workflow. It worked for me by using url "https://{tenant}-my.sharepoint.com/_api/v2.0/drives/{email_id}". Is it not called OneDrive API? I can see that it is categorized as OneDrive API on[ getting started page](https://dev.onedrive.com/getting-started.htm).

**Comment by rgregg** [comment]
You're correct that some things do work, but we do not officially support using app-only flow with the non-SharePoint REST APIs. We're working on building out support for these scenarios, but we're doing that through Microsoft Graph instead of calling the discovery API and the _api/v2.0 APIs. The biggest thing that doesn't work, and hence why we don't officially support it, is that you are blocked from downloading a file with app-only permissions.

The reason your request doesn't work is that both _api/v2.0/me/drive and _api/v2.0/drive require some user context to know which drive you want to access. In the app-only flow there is no user context, and thus those calls cannot succeed.

**Comment by nav-agarwal** [comment]
Can you point to SharePoint REST APIs doc which supports app-only flow for OneDrive for business?
