### ISSUE TITLE
Is it possible to have no hashes available at all?

### ISSUE THREAD

**Issue by AndrewPashkin** [OneDrive/onedrive-api-docs#527]
[This][1] documentation page says:

> Note: In some cases hash values may not be available. Downloading the item can cause the hash values to be populated, provided the hash is supported in the given context. See remarks for details.
> Remarks
> In OneDrive for Business and SharePoint Server 2016, sha1Hash and crc32Hash are not available.
> In OneDrive Personal, quickXorHash is not available.

I'd like to clarify, is such situation possible, when no hash of any type is available for a file?

[1]: https://github.com/OneDrive/onedrive-api-docs/blob/bede978b6a9c5a107306dd779b878af387a5dcbb/facets/hashes_facet.md#remarks

**Comment by ificator** [comment]
In most scenarios you'd expect to find at least one form of hash being available, however it's not guaranteed due to when various hashes were introduced. Realistically I think OneDrive Consumer should have hashes for all files, however OneDrive Business introduced `quickXorHash` later in the life of the product, and so it's possible for "old" files (I.e. those that were uploaded prior to `quickXorHash` being added) to not have a hash. In those cases, downloading the file will trigger a hash calculation.
