### ISSUE TITLE
Download All Files and Folders From OneDrive

### ISSUE THREAD

**Issue by Srusti-Thakkar** [OneDrive/onedrive-api-docs#537]
Hello, I want to create OneDrive Desktop Client using c#. So can you please tell me how to download Full OneDrive and sync it with specific user account first time.

**Comment by rgregg** [comment]
You can enumerate the full contents of a OneDrive using the [delta](https://dev.onedrive.com/resources/viewDeltaResource.htm) API. From there you can easily download the files as well. To get authenticated, follow the [Getting Started](https://dev.onedrive.com/getting-started.htm) documentation.

In general, this forum is for problems / issue reporting. It sounds like you're just getting started, so please read through the documentation since the answers for what you are trying to do are located within. If you have a specific question or encounter an issue using the API, please post it here. You may also try posting on [Stack Overflow](http://stackoverflow.com/questions/tagged/onedrive) since there is a larger audience there to help you.
