### ISSUE TITLE
Can not upload file larger than 100 MB

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#540]
When I tried to upload a file with more than 100 MB  to my OneDrive with file saver and I got an error "the user has selected a file larger than 100 MB". This might not be a bug and I wonder if there is a way to upload a file with more than 100MB. I do not see any limitation from the official OneDrive API or file picker/saver.

Thanks,
Phuong

**Comment by ificator** [comment]
The 100MiB limit exists only for [single item uploads](https://dev.onedrive.com/items/upload_put.htm). The documentation for that upload explicitly mentions a 4MiB limit, but the true limit depends on the endpoint you're hitting (e.g. Graph vs OneDrive). To upload larger files you'll need to use the [resumable upload](https://dev.onedrive.com/items/upload_large_files.htm) functionality.

Since you called out the picker/saver, is that what you're using to do the upload?

**Comment by neunygph** [comment]
Hi @ificator 

Thanks for the response to my question. I'm actually trying to upload a local file to OneDrive with the saver SDK. The links you provided are for using the REST API which is a different implementation . Is there a way to do resumable upload with the SDK ? 

Thanks,

**Comment by rgregg** [comment]
@neunygph:

The saver SDK is limited to 100MB uploads because it uses the single PUT method to do the upload. If you want to upload a large file, you would need to handle the upload process in your own JavaScript code. There is an example of using the Picker SDK along with the API in JavaScript here: https://github.com/OneDrive/onedrive-texteditor-js/blob/master/js/text-edit.picker.js#L126

However, this sample also uses the simple PUT method. You would need to implement an update using the createUploadSession API to upload larger files.

**Comment by neunygph** [comment]
Hi @rgregg 

Thanks for providing the example, it's really helpful. And I have a few more question about the SDK/API, can you help me out please?
1. Is there a size limit for resumable upload ? 
2. Is there a size limit for single and resumable upload when using "options.sourceUri" instead of "options.sourceInputElementId" ?
3. Is there a size limit for file downloading as well as file sharing, copying with the SDK and/or API ?

Thanks,

**Comment by rgregg** [comment]
Outside of the PUT scenario, the size limits are the same as the whole service. Currently OneDrive has a 10GB maximum file size.

There are some best practices for the [resumable upload API](https://dev.onedrive.com/items/upload_large_files.htm#best-practices) that you should follow.

Using upload from HTTP is only supported for OneDrive personal, but it doesn't have any inherent limitations beyond the basic service limitations.

**Comment by neunygph** [comment]
Ah I see, thanks @rgregg and @ificator for looking into this.

Best,
