### ISSUE TITLE
view.delta for sharedWithMe items?

### ISSUE THREAD

**Issue by johnlilis** [OneDrive/onedrive-api-docs#554]
In order to track changes for sharedWithMe items, I am currently using a call to view.sharedWithMe and then a subsequent view.delta call for each returned item.

However, this way I have to query all sharedWithMe items (even the ones that don't change) every time.
Is there a way to avoid unnecessary delta calls and somehow get a list of only changed sharedWithMe items?

**Comment by sergiorykov** [comment]
It worked previously. See #553
You could use `remoteItem.it` to get `view.delta`

**Comment by johnlilis** [comment]
It works now as well (see my response on your issue),
I'm just asking if there is a more efficient way to do it.

**Comment by ificator** [comment]
There isn't currently a more efficient way, since each of the delta calls is potentially hitting a different user's account. We could potentially look at having a single call in the API that does a fan out behind the scenes so you don't have to, but there isn't a capability we currently have.

If you think such a thing would be useful please feel free to create an idea on our [https://onedrive.uservoice.com/forums/913708/](UserVoice) page.
