### ISSUE TITLE
Are webhooks batched?

### ISSUE THREAD

**Issue by vorio** [OneDrive/onedrive-api-docs#576]
Few weeks ago, it appeared being batched every 2 minute or so for the changes. Now, looks like near real time.

**Comment by rgregg** [comment]
The way webhooks are processed in the system can result in a delay of up to about 5 minutes between a change being triggered and the webhook being delivered. We're working to improve that SLA so that webhooks can be delivered in nearly real time, but that is the reality of the webhooks support today.
