### ISSUE TITLE
User sign out not working properly

### ISSUE THREAD

**Issue by anidotnet** [OneDrive/onedrive-api-docs#58]
How does the user signing out work? According to the API docs I need to make a call to the below url

`GET https://login.live.com/oauth20_logout.srf?client_id={client_id}&redirect_uri={redirect_uri}`

But if I don't pass the access_token/refresh_token, how the end user is supposed to be logged out of the system? What does the above API do actually? Because after making a call to the above API, I can still use the old access_token to make calls; tokens are not getting revoked. So how to sign out/revoke the access for an end user?

**Comment by ankit-ankuagrawal** [comment]
refer for access_token query 
https://github.com/OneDrive/onedrive-api-docs/issues/33

**Comment by anidotnet** [comment]
Not clear though how to logout a user from the system.. Any idea?

**Comment by rgregg** [comment]
The `oauth20_logout.srf` call will delete the browser cookie, so that next time the `oauth20_authorize.srf` request is made, no user will be logged in (we'll prompt for a username and password). This does not invalidate the access_token you have received previously.

To log out of OneDrive in your app, you should:
1. Delete any access_token or refresh_token your application is holding on to.
2. Call the `oauth20_logout.srf` flow to remove any cached cookie data in the browser or web view used for OAuth.
3. When redirected back to your redirect_uri without any parameters, the user has been logged out.

Calling oauth20_logout.srf is mostly important for web applications to make sure the browser cookie is cleared and the user isn't automatically signed in again or if you asked for the `wl.signin` scope in a mobile or desktop application.
