### ISSUE TITLE
OneDrive for business add Shared Folder

### ISSUE THREAD

**Issue by anildbest83** [OneDrive/onedrive-api-docs#591]
I m using OneDrive for Business API to get Shared Folders using REST call

`/_api/v2.0/me/drive/sharedwithme`

which is working fine.

Also getting shared folder child also working fine with REST

`drives/{drive-id}/items/{item-id}/children`

Now i want to add a 'New folder inside a Shared Folder'.

OneDrive Api docs says 'A shared folder can only be added to the root of a user's drive.'

Is there any way i can add folder inside a shared folder?

Please suggest

**Comment by ificator** [comment]
The root limitation only applies to the shared items (i.e. remote items that reference items in another drive). It's easiest to think of such items as pointers to another item - you cannot place items under them because they themselves are not folders, but you can place items under the item they're pointing at.

Say you have a shared folder that looks like this:

```
{
  "id": "98765432!12399",
  "name": "Team Documents",
  "remoteItem": {
    "id": "12345abcde!1221",
    "parentReference": {
      "driveId": "12345abcde"
    },
    "folder": { "childCount": 15 }
  },
  "lastModifiedDateTime": "2015-08-10T13:47:11Z",
  "createdDateTime": "2015-08-10T13:47:11Z",
}
```

If you wanted to create a folder within it you'd want to use the `remoteItem.parentReference.driveId` and the `remoteItem.id` values to craft a request against the real folder like so:

```
POST https://api.onedrive.com/v1.0/drives/{remoteItem.parentReference.driveId}/items/{remoteItem.id}/children

{
  "name": "new folder",
  "folder": { }
}
```

**Comment by anildbest83** [comment]
@ificator this is working great, thanks alot
