### ISSUE TITLE
[ODB] fail to get user drive of new adding user

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#629]
Hi,
It is the situation:
1.  I have an admin account ADMIN_A
2.  now I add a new account with license ACCOUNT_B who can user onedrive for business
3.  ADMIN_A request graph API to get ACCOUNT_B 's drive id, it failed.
4.  However, when I promote ACCOUNT_B  to be an admin and request graph API, it can get all drive id

I want to know what is going wrong, or it is by design

Thank you!

**Comment by katahir** [comment]
Hi @joewutaiwan,
It is by design. Tenant admins don't get to see contents of drives that they don't have access to. They need to be explicitly made site collection admins in order to gain access. However, you can use the app-only flow(a.k.a client credential grant flow) to achieve the desired result. App-only tokens are consented to by the tenant admins, and grant access to all drives. You can read more about it here:

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-client-creds
