### ISSUE TITLE
One drive upload

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#655]
With One drive file saver, we can be able to see the uploading process such as uploaded percent. Is it possible to retrieve this same process (uploaded percent) with upload end point (PUT /drive/items/{parent-id}:/{filename}:/content) ?

Thanks,

**Comment by ificator** [comment]
If you're PUTing directly to /content it would be up to your client to keep track of progress. If, however, you're using the session based uploading you can [query for status](https://dev.onedrive.com/items/upload_large_files.htm#request-upload-status) although that's targeted more for allowing a client to know where to resume and not so much for displaying an accurate upload percent.

**Comment by neunygph** [comment]
Hi,
I also tried to use optional query string parameters to rename a file with the same content but it always returned 200 status for me instead of 201 as expected. Below is the request example, not sure what I missed or anything is wrong.
https://api.onedrive.com/v1.0/drive/items/{myfolderID}:/mytest.pdf:/content?@microsoft.graph.conflictBehavior=rename

**Comment by ificator** [comment]
If you're calling the OneDrive API directly instead of via Graph you'll want to take note of the differences outlined [on this page](https://dev.onedrive.com/direct-endpoint-differences.htm#instance-annotations). In this instance you'll want to use `@name.conflictBehavior` instead of `@Microsoft.graph.conflictBehavior`.

**Comment by neunygph** [comment]
Cool, I got it working. Thank you.
