### ISSUE TITLE
Discovery not works in German cloud?

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#663]
Hi,

According to this article `https://dev.onedrive.com/auth/aad_oauth.htm`, I have to acquire token for `https://api.office.com/discovery/` first in step2. But I get `invalid resource` error after sending request to token endpoint.

Here is my request and response
```
POST https://login.microsoftonline.de/common/oauth2/token
client_id=$clientid&client_secret=$secret&code=$code&grant_type=authorization_code&redirect_uri=http://localhost/&resource=https://api.office.com/discovery/
```
400 Bad Request 
```
{
"error": "invalid_resource",
"error_description": "AADSTS50001: The application named https://api.office.com/discovery/ was not found in the tenant named $tenant. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: bd038e7c-0267-4a32-9fea-7638231d0100 Correlation ID: df856bc9-a516-408b-8e63-7c32b844f8e0 Timestamp: 2017-08-02 06:41:38Z",
"error_codes": [
  50001
],
"timestamp": "2017-08-02 06:41:38Z",
"trace_id": "bd038e7c-0267-4a32-9fea-7638231d0100",
"correlation_id": "df856bc9-a516-408b-8e63-7c32b844f8e0"
}
```

Are there other discovery endpoint for German cloud?

`https://dev.onedrive.com/auth/graph_oauth.htm#code-flow` Graph oauth not works in step2 either,  it also ask resource too

**Comment by verybada** [comment]
Update:
It is a German office 365 account

**Comment by verybada** [comment]
@rgregg @ificator 
any news?

**Comment by tdtran** [comment]
@verybada you closed this issue. Was it resolved somehow?

I can testify that the problem still exists with AAD. I am considering migrating to Microsoft Graph but if that doesn't work either, then I am stuck

**Comment by tdtran** [comment]
@rgregg your thoughts?

**Comment by verybada** [comment]
@tdtran, problem still there I think. I can even get any feedback from official support :(

**Comment by rgregg** [comment]
Reopening this issue until we have a resolution. The discovery API is [now deprecated](https://dev.office.com/blogs/outlook-rest-api-v1-0-office-365-discovery-and-live-connect-api-deprecation), and will stop functioning in about a year. Apps being written today, including for specific national clouds, really should be using Microsoft Graph: https://developer.microsoft.com/en-us/graph/docs/concepts/deployments

You can use the Microsoft Graph API to perform the same steps as the discovery API, or you can use the Graph API to complete your whole scenarios. There are example requests in the deprecation topic I linked above for how to perform a similar discovery action using Microsoft Graph.

**Comment by tdtran** [comment]
@rgregg the problem exists even if you switch to MS Graph. For example I can't login Office 365 Germany account with the official sample app: https://github.com/microsoftgraph/android-java-connect-sample

After several days of HTTP call tracing, trials and errors I think I know what the root problem is.

First let's agree that in most cases the users don't know they are using national MS cloud. They already have hard time telling the difference between OneDrive Personal and OneDrive for Business. The users in Germany probably knows they have an Office 365 account, say from their company but there's no telling of it's a general .com MS cloud or .de cloud.

I take the official doc at its face value https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth and do exactly what it says. Mine is a native (android) app so I use the so called "code flow".

Step 1: Get authorization code

```GET https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id={client_id}&scope={scope}&response_type=code&redirect_uri={redirect_uri}```

This URL is opened in web browser (external or embedded webview).

The user enters their email address helmut@mycompany.com

The web page makes ajax calls and figure out that this user is in fact Office 365 Germany, it redirects `login.microsoft.de`. While doing so I see in my HTTP tracing that the `redirect_uri` param is lost. So no chance `login.microsoft.de` can send the token back to my supplied `redirect_uri`. But I didn't even get that far. The URL above uses `scope` param. Behind the scene it seems `scope` implies `resource=https://graph.microsoft.com`. There's no graph.microsoft.com resource at MS Germany cloud. Authorization fails.

The workaround I found is

Step 0) let user type in their email address
Step 1) find out where Office 365 account corresponding to that email exists, in global .com cloud or in .de cloud. I couldn't find any official API so I use an undocumented `https://login.microsoftonline.com/common/userrealm?user=helmut@mycompany.com` HTTP call.
Step 2) if it's .de account, use `login.microsoftonline.de` instead of `login.microsoftonline.com` **and** use explicit `resource=https://graph.microsoft.de/`

**Comment by tdtran** [comment]
@rgregg we would go a long way if the team responsible for `login.microsoft.com/common/oauth2` also test the sample app https://github.com/microsoftgraph/android-java-connect-sample against national clouds themselves. I bet they'll see it doesn't work.

**Comment by rgregg** [comment]
Thanks for the feedback, this is definitely harder than it should be, and being dependent on an undocumented API is not cool. Let me pass this feedback along to the identity team and see if we can come up with a better set of gudience for how to build out national cloud account discovery.

**Comment by tdtran** [comment]
@rgregg @ificator did you fix this issue? If not IMO we should keep it open for tracking

**Comment by pmbaldha** [comment]
@rgregg @ificator @tdtran I am still facing same issue.


When I am trying to get access token for Office 365 Germany by API call as described on the 
https://docs.microsoft.com/en-in/azure/active-directory/develop/active-directory-v2-protocols-oauth-code#request-an-access-token, but it display irrelevant error like below:




    {
        "error": "invalid_client",
        "error_description": "AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: 978ed68d-e8b5-419d-8f5c-a25df8f01200\r\nCorrelation ID: 45ee8bb8-b3a1-4d6f-8499-816739f6d118\r\nTimestamp: 2018-07-05 05:39:29Z",
        "error_codes": [
            70002,
            50012
        ],
        "timestamp": "2018-07-05 05:39:29Z",
        "trace_id": "978ed68d-e8b5-419d-8f5c-a25df8f01200",
        "correlation_id": "45ee8bb8-b3a1-4d6f-8499-816739f6d118"
    }


Screenshot: http://funkyimg.com/i/2JcXj.png


I have tried after url encoding client secret and making new secret, but I was failed. I have tried many times. 

However, Same flow working fine with Office 365 worldwide account.
