### ISSUE TITLE
Resumable Upload can not complete

### ISSUE THREAD

**Issue by lilin007007** [OneDrive/onedrive-api-docs#71]
when I Upload a large file(bigger than 1G), a error occured, and the server returned this "{"error":{"code":"generalException","message":"Assertion Failure While Processing"}}".when I am ready to continue to upload and Request upload status, get a nextExpectedRanges, but the server's  return is this  "{"expirationDateTime":"2015-04-16T01:34:54.1264728+00:00","nextExpectedRanges":[]}",why?

**Comment by ificator** [comment]
Can you provide the HTTP headers associated with that error response? Also, could you tell us what fragment size you're using? In https://github.com/OneDrive/onedrive-api-docs/issues/70 we found that it needs to be a multiple of 320KiB, which would suggest a size of something like 5MiB and not the 4MiB that we'd originally recommended (docs have since been updated)

**Comment by lilin007007** [comment]
Thanks for your reply.According to your suggestion， I tried to Upload file using a lot of fragment size, and I found if I used a fragment size bigger than 256KiB, the Error I described did not appeared. and if the fragment size equal to 256KiB, the Error will be occur.

**Comment by ificator** [comment]
We've made some changes recently that we believe will help with this kind of problem, so hopefully you won't see the mysterious "generalException" anymore.
