### ISSUE TITLE
Unable to retrieve shared folder - Onedrive IOS sdk

### ISSUE THREAD

**Issue by janaraj** [OneDrive/onedrive-api-docs#725]
Hello,

I'm trying to retrieve list of items from a shared folder but always getting 404 not found error. Have added the permission "Read and Write items in all site collections" under Office 365 sharepoint online in Azure portal. Below is final URL that gets framed. I went through all the documents but still no luck. Could someone please help ?

https://{tenant}-my.sharepoint.com/_api/v2.0/me/drives/{driveid}/items/{itemid}/children

Regards,
Jana

**Comment by ificator** [comment]
My general rule is to only use `me` if you're going to use `drive` (i.e. you're wanting to access the drive for the current caller. For any other scenarios I'd drop the `me` and use `drives`.

In your case, since you're hitting SharePoint directly, technically `me` isn't even valid (although it does work). If you can craft a URL that looks like this I'd expect it to work (assuming the ids provided reference a valid item):

```
https://{tenant}-my.sharepoint.com/_api/v2.0/drives/{driveid}/items/{itemid}/children
```

**Comment by janaraj** [comment]
Thanks much for the quick response. Let me try and post back here. 

regards,
Jana

**Comment by janaraj** [comment]
I was able to craft the URL using SDK without "me" and it works cool. Glad that it was resolved. Thanks again.
