### ISSUE TITLE
/drive API giving inconsisent results

### ISSUE THREAD

**Issue by santhoshml** [OneDrive/onedrive-api-docs#727]
When I shoot a request to 
https://api.onedrive.com/v1.0/drive endpoint with token, I get a response object.

This response object sometimes has a displayName and empty other times.

request
curl -X GET \
  https://api.onedrive.com/v1.0/drive \
  -H 'authorization: bearer AUTH_TOKEN' \
  -H 'cache-control: no-cache'

response 

{
    "@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives/$entity",
    "id": "79a9fce55c493155",
    "driveType": "personal",
    "owner": {
        "user": {
            "displayName": "", <--- EMPTY
            "id": "79a9fce55c493155"
        }
    },
    "quota": {
        "deleted": 0,
        "remaining": 5368311037,
        "state": "normal",
        "total": 5368709120,
        "used": 398083,
        "storagePlans": {
            "upgradeAvailable": true
        }
    },
    "status": {
        "state": "active"
    }
}

**Comment by osmogar** [comment]
Some users of the Duplicati application (a c# backup application that can use OneDrive as storage) are suffering this problem since the monday or tuesday of the last week with some accounts.

The application try to get the list of files with the REST API in the backup folder and in the iteration to get it, appears inconsitencies and duplicate files that makes the application to fail.

We are discussing it here: https://forum.duplicati.com/t/backup-failing-with-key-already-exists-exception-on-onedrive/

**Comment by ificator** [comment]
@osmogar Duplicati appears to be using Live Connect, which is in the process of being deprecated. You can get details from the [Office Developer Blog](https://dev.office.com/blogs/outlook-rest-api-v1-0-office-365-discovery-and-live-connect-api-deprecation).

@santhoshml Are you still seeing this issue? The display name needs to come from another service, and so it's possible there was an issue at the time. If it's still occurring I can track down someone to take a look.

**Comment by osmogar** [comment]
@ificator Yes, duplicati uses the old API, and that's what I though at first, but it only happens on some accounts, and the malfunctioning accounts have problems in the OneDrive website too: it's impossible to short or scroll the list, the files disappears and appears randomly, like the bug affects it, and I suppouse the OneDrive website uses the Graph API.

Debugging the issue I saw that when we retrieve the json list of objects with the same offset we get a random list, not the same like it must be.

**Comment by ificator** [comment]
@osmogar it's possible that what you're seeing is an artifact of the paging system. When you start paging through the children of a folder there's no way to do so in a transacted manner, and so changes made to items while paging is in progress can result in some "interesting" responses. For example, if a page consisted of files a, b, and c, and before you requested a new page someone created an a2 the next page could conceivably look something like c, d, and e. So even though your client already "saw" c it'll get it again since another item was created ahead of it.

The only way to enumerate in a manner guaranteed to result in a consistent view of is to use `delta`, however it will return a lot more than just the immediate children.

**Comment by ificator** [comment]
As for the original issue - unfortunately the population of the display name is best effort. The vast majority of the times we should have a value, but since we do not store that information (it's actually part of the user's profile) there can be situations where we simply don't have it. In those cases we'll return the data that we do have, and leave the display name empty.

**Comment by osmogar** [comment]
Hi @ificator, maybe this is the problem in the onedrive web frontend. The weird thing is that in another account with the same amount of files (more or less) the pagination is ok, and the search too (search of items by date is impossible in the "failing" account).
I have solved the problem with the api with a workaround: I know the total number of items, and I keep requesting items until I have this total number of different items. Normally, in seven or eight iterations I get all the items (but the time of the request is seven or eight times greater than normal)

**Comment by osmogar** [comment]
I don´t know what has been done yesterday or today, but the failing account have started to work right again "magically".
Thanks!
