### ISSUE TITLE
OneDrive File picker - can not select files shared with me

### ISSUE THREAD

**Issue by kryltsov** [OneDrive/onedrive-api-docs#733]
We use OneDrive files picker to allow Freedcamp users to link OneDrive files to their items in our application, however we found that while users can see folders and files shared with them in file picker they can not select them.

Is it supported? I would truly appreciate any hints as to how this can be done.

Thank you

**Comment by daboxu** [comment]
hi @kryltsov you are not the only person asked about that behavior. I would say currently that's expected, sorry we haven't supported select folder and files at the same time yet. While you can select folder and file separately because we regarded selecting a file seems like download a file and selecting a folder indicates you want to save something to it when we designed the scenario. The way you can select folder is with the config:

```javascript
onedrive.save({
    action: "query"
    //...other configs...
});
```

while for select file it is:

```javascript
onedrive.open({
    action: "query"
    //...other configs...
});
```

The request actually is on our backlog and we will prioritize it. Thanks for your feedback.

**Comment by kryltsov** [comment]
Sorry for a confusion - I am not interested in selecting folders+files. Only in one or more files in the same folder. People see shared files and folders via OneDrive file picker and can navigate (open those shared folders and see files inside) but can NOT select those shared with them files.

In our case integration is very simply. You create a task or a comment in Freedcamp and you can upload a file from your PC or link OneDrive file to it. Once linked in Freedcamp, you and other users can click and file on OneDrive will open up - https://freedcamp.com/Freedcamp_LxR/Freedcamp_Devel_yOf/wiki/wiki_public/view/iSbab

**Comment by daboxu** [comment]
@kryltsov thanks for clarifying that, unfortunately we cannot support the shared folder under OneDrive for selecting items under it. Probably we will add a clear indicate on these folders.

**Comment by kryltsov** [comment]
Thanks. May be update OneDrive file picker docs so at least we can point clients saying it is not supported by Microsoft. Will be handy for developers to know about this limitation too.

Just FYI - there is NO such issues with GDrive file picker, I guess a competitor of yours in this space ;)

**Comment by daboxu** [comment]
@kryltsov thanks, I will do the updates in the doc. I totally agree the scenario should be in our radar, I will add backlog for it. Close it for now.
