### ISSUE TITLE
OneDrive file picker never finishes loading on IE11 and Edge

### ISSUE THREAD

**Issue by gloriacruz** [OneDrive/onedrive-api-docs#755]
Hi, I'm a developer working integrating OneDrive in an a large app. I'm using SDK 7.2 for JS. 
Background: In my app each client can have a custom URL (client1.domain.com, client2.domain.com...) and multiple pages are using the picker. 
I created an iframe that loads my secure.domain.com/pickerpage.jsp, this page has the OneDrive.js library and the call OneDrive.open(options). From there the oAuth flow begins and I can see and pick the files I need. It all works well in all browsers except IE11 and Edge. For those browsers, I go throughout the oAuth flow with no problems but then the picker never finishes loading and shows the spinning wheel forever. I never get to the see the files. The address bar shows https://secure.domain.com/pickerpage.jsp#access_token=eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFC....
I tried switching my embedded iframe for a popup window and it's the same problem. The console is not showing any error.
Thanks!

**Comment by daboxu** [comment]
hi @gloriacruz thanks for the background info. Based on the info it seems like your client will invoke a page, ex:

client1.domain.com (client page)

and there is an iframe named:

secure.domain.com/pickerpage.jsp (secure page)

which holds the onedrive.js, and you have the invocation of the picker on the secure page. So an oauth popup was invoked and later it was stuck on the url 

https://secure.domain.com/pickerpage.jsp#access_token=eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFC....

Does my understanding correct? Correct me if I am wrong at some point.

**Comment by gloriacruz** [comment]
Yes, the understanding is correct. It gets stuck when loading the picker after getting the token in the url. Only for IE and Edge.

**Comment by daboxu** [comment]
@gloriacruz thanks for confirming that. Is there any log on the iframe page (secure page) or the popup window in IE/Edge?

**Comment by gloriacruz** [comment]
@daboxu This is all I get in IE11 (attached image). Another thing I noticed is that when the app runs from the secure url: secure.domain.com (same as picker page), it works fine in IE/Edge. If it runs from the custom url: clientx.domain.com, it doesn't work on IE/Edge but it does in any other browser.

<img width="801" alt="console ie11" src="https://user-images.githubusercontent.com/1839036/34145507-3a2b5c20-e44b-11e7-9e74-1b34b047bf78.png">

**Comment by daboxu** [comment]
thanks for the screenshot. It seems familiar for me. I am guessing you are logined as ODB user? If so the reason for IE/Edge not working is because SharePoint/ODB is regarded as intranet which it has higher security than normal websites so the postMessage actually is not working well. You can read the previous thread about #550 . And what's wired about this is the IE setting actually impacts Edge browser. You can give it a try by customizing the security setting.

**Comment by gloriacruz** [comment]
Hi @daboxu thanks for your reply. I've been playing around with the security settings all day as indicated in #550. 
1. Making sure 'Enable Protected Mode' is checked for all zones
2. Remove all websites from 'Trusted sites'
Also, after any change I close all browser windows and reopen.
The behavior is not consistent, sometimes it works, sometimes it doesn't. Sometimes it works the second time I open the picker but not the first. 
Is there any other thing I can do to fix this? Any other setting? or adding meta tags o other elements to my html?
Thanks!

**Comment by daboxu** [comment]
hi @gloriacruz thanks for the info. sorry as far as I know that's the only setting I know which made my testing machine work. I will add a backlog for this IE/Edge capability issue.

**Comment by gloriacruz** [comment]
hi @daboxu, 
Is the SDK 7.0 version still supported? do you think my issue will be resolved if I switch to this version?
Thanks

**Comment by daboxu** [comment]
hi @gloriacruz we do support v7.0, The good thing for v7.0 is it does not use postMessaging for multi-window messaging but your problem could be still there because it is caused by the IE settings for SharePoint. I would suggest give it a shot. Let me know if it does not work, I will try set up a virtual machine with the same OS version and IE version and try to reproduce that.

**Comment by gloriacruz** [comment]
Hi @zachzi, 
I have an update regarding this issue. I have downgraded the SDK version to 7.0 and some versions of IE11 and Edge are working but some other are not. Last time I talked to @daboxu, he offered to try to reproduce my error. Do you think you will be able to help me out? 
I really want to make this work, right now, I have a label in my app saying 'OneDrive Integration is not supported in IE/Edge', which is confusing for my users. 
Thanks!

**Comment by zachzi** [comment]
Hi gloriacruz,

Sorry for the late response - are you still experiencing this problem?  Which versions of IE11 / Edge are not working for you with the 7.0 version of the SDK?

Thanks,
zachzi

**Comment by moos** [comment]
Running into same issue -- disabling "Protect Mode" for Internet zone resolves the issue.  Isn't it odd that OneDrive works in all browsers except _Microsoft's_!! 

There is a slew of issues related on OneDrive Picker and IE/Edge.  Rather than giving devs the run-around for over a year, MS should commit to fixing it so it just works, as it does with other browsers.

**Comment by KevinTCoughlin** [comment]
The File Picker is an AAD backed application which authenticates using redirect URLs as per spec. This issue seems related to the specific IT policy put in-place i.e security zones / restricted sites.

Please see https://github.com/OneDrive/onedrive-api-docs/issues/874 which is related. Also https://support.microsoft.com/en-us/help/17479/windows-internet-explorer-11-change-security-privacy-settings.

To confirm this as the cause, we would need to see which domains are being blocked and if they are being blocked because of an IT policy. If so, your IT policy would need to be modified.

**Comment by hazem3500** [comment]
I have the same issue on v7.2 but now it happens on chrome
