### ISSUE TITLE
Filepicker.js and existing accessToken

### ISSUE THREAD

**Issue by sandermak** [OneDrive/onedrive-api-docs#789]
We're using the JS filepicker (7.2), with the following advanced config:

```
advanced: {
        accessToken: someExistingToken,
        , endpointHint: 'https://graph.microsoft.com/v1.0/'
        , isConsumerAccount:false
    }
```

Another (non-file picker related) flow ensures there's a token available in `someExistingToken`. This is a valid token, as we can confirm by calling the Graph API directly using a tool like Postman with the same token.

Filepicker.js sees the `accessToken` and `endpointHint` and (rightly) concludes no oAuth login flow is necessary. It then opens an iFrame with the following URL: `https://graph.microsoft.com/v1.0/?p=2&picker=<snipped>` where `<snipped>` constitutes some JSON configuration created by Filepicker.js. However, opening this URL in the iFrame fails (error response from the Graph API) because there's no Authorization header with a bearer token (nor is the `accessToken` passed in the config I talked about earlier, though it does include the clientId).

What's more, if I call this URL from Postman *with* a valid Authorization header, it tells me the request is not valid (it does recognize the `accessToken` passed in the Authorization header thoug). So somehow, the filepicker constructs a Graph API call that's not correct.

How can we make this scenario work? From a config perspective it looked so straightforward: just provide an existing, valid `accessToken` and all should be well. However, in practice, it doesn't work. What am I missing?

**Comment by Ecostack** [comment]
I am facing the same issue right now. The 'graph.microsoft.com' endpointHint leads me to same issue.
If the endpointHint points towards the users sharepoint instance, it works flawlessly.

@sandermak Were you able to come around this issue?

**Comment by sandermak** [comment]
> @sandermak Were you able to come around this issue?

I'm afraid not :(

**Comment by etyp** [comment]
@Ecostack when you have `endpointHint` pointed to the sharepoint instance, does it work even if you attempt from an incognito window?

I found that even with an `accessToken`, it asks the user to log in again which is not expected.

**Comment by knmr** [comment]
I'm having the same issue. I compared the accessTokens I requested myself and the one that is created using the Filepicker on https://jwt.ms and found that the content is slightly different. I'm going to dig a little deeper.

| Claim Type  | My value | Filepicker Value| Conclusion|
| ------------- | ------------- | ------------- |------------- |
| aud  | 00000003-0000-0000-c000-000000000000  |https://graph.microsoft.com| Turns out my UID and graph URL have the same meaning. Both say the graph API is the audience |
| appidacr | 1| 0 | I don't know exactly why this would be an issue.|
| scp | Files.Read.All Files.ReadWrite.All openid profile Sites.ReadWrite.All User.Read email  | profile openid email User.Read Files.Read.All  | I don't see a reason why more scopes would be an issue.|


| Claim Type  | Claim Description |
| ------------- | ------------- |
| aud  | Identifies the intended recipient of the token. In id_tokens, the audience is your app's Application ID, assigned to your app in the Azure portal. Your app should validate this value, and reject the token if the value does not match.  |
| appidacr | Indicates how the client was authenticated. For a public client, the value is "0". If client ID and client secret are used, the value is "1". If a client certificate was used for authentication, the value is "2". |
| scp | The set of scopes exposed by your application for which the client application has requested (and received) consent. Your app should verify that these scopes are valid ones exposed by your app, and make authorization decisions based on the value of these scopes. Only included for user tokens.  |

**Comment by knmr** [comment]
unfortunately I was not able to solve this issue myself. There is only limited time I can spent on this. I'm working around this by using the advanced settings isConsumerAccount and loginHint to specify which user it is. If the user has already granted the needed scopes, he will see the OneDrive to pick a file. This is fine for me and I hope it's enough for others too.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
