### ISSUE TITLE
[Question] Is it correct behavior to return "content-encoding: gzip" and "content-length: 0" together?

### ISSUE THREAD

**Issue by igokoro** [OneDrive/onedrive-api-docs#80]
For [action.copy](http://onedrive.github.io/items/copy.htm) I send request
```
Accept-Encoding: gzip
...
```
And OneDrive server returns
```
202 Accepted
Content-Encoding: gzip
Content-Length: 0
```

But minimum length for a gzip stream is 10 bytes (http://en.wikipedia.org/wiki/Gzip#File_format) - this is gzip header length, without which stream can't be decompressed. So I wonder if this is both meaningful and valid response from server? Some networking libs fail to handle such situation and (legitimately) treat empty gzip stream as invalid.

**Comment by ificator** [comment]
This is an interesting issue and probably one we should look at fixing to make sure developers don't need to do magic special handling for the libraries that fail on such a response. It would also save us 22-bytes on the wire by not including an unnecessary Content-Encoding header :).

Having said that, my interpretation of the [gzip RFC] (http://tools.ietf.org/html/rfc1952) is that the header is required per "member" and since a file (or stream in this case) is a series of members it seems as though 0 members is also acceptable (it wasn't called out as being disallowed). If that interpretation is indeed correct then for a 0 member scenario a 0-byte response would be considered valid.

**Comment by igokoro** [comment]
@ificator, great to hear OneDrive developers care for such seemingly minor, but still quite annoying issues!

**Comment by igokoro** [comment]
I wonder if there are updates on this issue? Now it bugs me also on item details request with ```if-none-match``` header when server responds with ```304 Not Modified```.

I can still completely disable gzip compression for a call, but this time client is supposed to receive data (potentially large amount) and disabled gzip might hurt performance.

**Comment by ificator** [comment]
We've made a change that we believe will help the situation, but unfortunately it's not available for you yet. My estimate is a couple of weeks from now, but I'll update once it's deployed.

**Comment by ificator** [comment]
This should now be deployed. Hopefully you won't see 0-byte responses being gzipped anymore!

**Comment by igokoro** [comment]
I can confirm that 0-byte responses does not include content-encoding: gzip anymore. Thank you!
