### ISSUE TITLE
I can not get the remaining requests from the response header.

### ISSUE THREAD

**Issue by imkk** [OneDrive/onedrive-api-docs#808]
Recently, my OneDrive for Business app always gets the 429 Too many requests error, and I checked the article: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits. However, I can not get the remaining requests from the response header.

**Comment by imkk** [comment]
Yes, I'm using the Graph API to connect to OneDrive for Business and I'm not very clear about the authentication ways you mean, I'm using the OAuth 2.0 authorization code grant flow to get an access token from the Azure AD v2.0 endpoint. 
So, do you have any idea on how can I test and process the 429 error from a localhost environment?

**Comment by ificator** [comment]
Thanks @imkk. There is a known issue with "app-only" scenarios that can cause some excessive throttling, which is why I asked. Such tokens are used for daemon scenarios where there is no user information available, and so a certificate is normally required to get such a token. If you aren't doing that it's probably just a user scenario. [This link](https://msdn.microsoft.com/en-us/Library/Azure/Ad/Graph/howto/azure-ad-graph-api-permission-scopes#app-only-vs-delegated-scopes) has a good summary.

Testing 429 behavior isn't easy - as you'd essentially have to generate enough load against the system that it takes notice and applies some throttling.

**Comment by imkk** [comment]
Ok, so my app should be using the delegated scopes. 

It can only be like that. Thank you anyway.
