### ISSUE TITLE
@nameConflictBehaviour option while creating new file

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#81]
while creating new folder we have option for @nameConflictBehaviour, but this option is not available while creating new file and also for when we move the file/folder.

**Comment by rgregg** [comment]
You can use @name.conflictBehavior with the [multipart upload](http://onedrive.github.io/items/upload_post.htm) and [large file upload](http://onedrive.github.io/items/upload_large_files.htm) and [upload from URL](http://onedrive.github.io/items/upload_url.htm) methods. The behavior isn't supported for simple upload because you're explicitly putting to the content of a file, which we interpret as a desire to replace the existing content of that file.

**Comment by ankit-ankuagrawal** [comment]
ty for the response
