### ISSUE TITLE
Issues with picker redirecting to App and back to browser on mobile

### ISSUE THREAD

**Issue by Peekee** [OneDrive/onedrive-api-docs#836]
I have the picker (v7.2) working nicely from desktop browsers. However, when using it on from an android phone where the app is installed I see the following happen :

1. A popup opens as normal
2. The popup redirects to the app
3. The app refuses to open the link and displays an error offering to redirect to a browser
4. Opening in the browser will then show the picker. However, the "success" callback is then broken, and is not called when a file is selected. (even cancelling just leaves the picker hanging there)

App error message : 
![screenshot_20180416-111053](https://user-images.githubusercontent.com/16252482/38803669-d39bbb2e-4167-11e8-86ec-5b1a0664e245.png)

Options for the picker :

`        clientId: oneDriveInit.clientId,
        action: "download",
        multiSelect: false,
        openInNewWindow: true,
        advanced: {
            redirectUri: oneDriveInit.uri,
        },
`

**Comment by ooboobay** [comment]
I have a similar issue with the File Picker (v7.2) in my web app running on an Android device, and that is, the javascript version of the File Picker doesn't work on an Android device.

The issue I'm experiencing is the following (on an Android phone with OneDrive native app installed):
1. Click on the button on a web app that opens the javascript version of the File Picker
2. The pop-up appears letting the user authenticates with OneDrive normally
3. OneDrive app opens and there is no way to communicate back to the web app

I can go to "Default Apps" settings on the Android device to change the App Links setting for "Go to supported URLs" in OneDrive to "Always Ask" so that I can choose to open File Picker on the browser from my web app, but that's not desirable.  I've also looked through the settings and advanced options in OneDrive javascript api to see if there is a way to always open the picker on a browser but can't find anything.

Is there a way to always open the picker on a browser on an Android device?

Thanks!
PS.: iOS doesn't have this issue.

**Comment by KevinTCoughlin** [comment]
>Is there a way to always open the picker on a browser on an Android device?

This is due to how Android intercepts URIs redirecting to the application. Unfortunately there is not a workaround from the library POV. The user would need to modify their settings as @ooboobay mentioned above.

The lookup is based on the URL used and since we are using OneDrive URLs the OS redirects to the application which says in its manifest file that it understands those URLs.

**Comment by Peekee** [comment]
Is it possible to have an alternative URL other than the defaults that basically just proxies to the main ones? -------- Original Message --------Subject: Re: [OneDrive/onedrive-api-docs] Issues with picker redirecting to App and back to browser on mobile (#836)From: Kevin Coughlin <notifications@github.com>To: OneDrive/onedrive-api-docs <onedrive-api-docs@noreply.github.com>CC: Peekee <a.riddell@daxtra.com>,Author <author@noreply.github.com>
Is there a way to always open the picker on a browser on an Android device?

This is due to how Android intercepts URIs redirecting to the application. Unfortunately there is not a workaround from the library POV. The user would need to modify their settings as @ooboobay mentioned above.
The lookup is based on the URL used and since we are using OneDrive URLs the OS redirects to the application which says in its manifest file that it understands those URLs.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
