### ISSUE TITLE
Deleting items

### ISSUE THREAD

**Issue by paya-cz** [OneDrive/onedrive-api-docs#84]
Is there any way to conditionally delete a folder as long as it is empty? I want to use a request combining ID+path, like:

> DELETE /drive/items/{item-id}:{path-to-some-folder}/{folder}:

But delete {folder} if and only if it is empty. The key here is the atomicity of the operation, as opposed to using 2 requests to query for contents and delete the folder.

---

Also, is there any parameter to specify to ensure the file/folder is permanently deleted, and not moved to recycle bin? For my particular application, recycle bin is pretty much useless, so I don't want to pollute that folder with a ton of files that are obsolete.

**Comment by rgregg** [comment]
There isn't a way to delete a folder only if it's empty. You can however confirm that the folder is empty, and then use the eTag from that metadata in the delete operation (If-Match: etag) to ensure that you only delete the folder if it hasn't changed from what you previously saw, so that you can avoid the race condition around deleting the folder just as something is added to it. This helps avoid some common reasons why you would need an atomic operation.

There isn't a way to delete permanently in the API right now. We're looking at ways to enable recycling bin management from the API, but one of the key elements of OneDrive is that your data is safe with us. Providing apps a way to destroy a file forever, while useful in some benign scenarios also enables it for destructive scenarios, so we have a balance to work through.

**Comment by paya-cz** [comment]
Well I don't know what I'm doing wrong, but if I upload files and create folders in a {folder} using web interface, that {folder}'s eTag does not change when I poll for the metadata after uploading. Not even if I rename the {folder}.

**Comment by rgregg** [comment]
We're looking into what's going on here. I was able to confirm the behavior you mentioned where the etag does not change when the contents of the folder are changed.

**Comment by rgregg** [comment]
Still don't have an answer about etag not changing, but you can use the "ctag" value which does change in the If-Match header as well, and ctag is only changed when the contents of the folder are changed, which is actually a better choice for your given scenario.

**Comment by paya-cz** [comment]
@rgregg This seems to be [undocumented](https://dev.onedrive.com/items/delete.htm). Can I really count on this feature to be fixed?

**Comment by rgregg** [comment]
You can count on using ctag values. I'll make sure that gets added to the documentation for the various etag headers.

We're investigating the issue with etag and may make a change to how the etag behavior works, but that won't affect the use of ctag.
