### ISSUE TITLE
UnknownError when uploading file or requesting drive resource

### ISSUE THREAD

**Issue by DanHopkins-TGI** [OneDrive/onedrive-api-docs#847]
I am intermittently experiencing unusual errors when attempting to upload a file via `UploadSession` or request a drive resource.  They started occurring shortly after this [issue](https://github.com/OneDrive/onedrive-api-docs/issues/838) was resolved.  I was wondering if they could somehow be related because I have yet to be able to reproduce the issue using the Graph Explorer to send the exact same request that originally returned an error--suggesting that my app-only authorization might be to blame.

Here is an example request and error response:

Request - `GET /drives/{driveId}`
Response - `Bad Request - Invalid Hostname`
```
{
    date: 4/24/2018 9:36:28 PM
    request-id: a8dc25e7-c8b3-4fd4-b03d-fdf60fb9000c
}

```

**Comment by DanHopkins-TGI** [comment]
Thank you for looking into it!  Here are a few more recent request ids from similar failures:  `655239de-d32d-46b4-8258-df0ea5ba1e11, ae3bcc66-3821-4a90-afdf-36ca7159823b, dc601249-11bb-44bf-ac57-ac7aee872c6c, and 271dda62-6560-4aa2-bc2a-4db83d44cfe5`. We are continuing to experience them on a regular basis, so we'd be happy to supply any additional information that might be helpful for resolving the issue.  

Thank you again for your time!

**Comment by ificator** [comment]
Hi @DanHopkins-TGI, do you still see this issue? It sound like a change may have been made towards the end of May that theoretically resolved things. But we've also heard rumors that it has started reproducing again so we're trying to figure out what state we're in.

If you have any newer request ids that would be good as well, but please make sure to provide the `date` value associated with each one so that we can pull the appropriate logs.

**Comment by DanHopkins-TGI** [comment]
Looking at our logs, the most recent exception was thrown the 23rd of May, so it seems the change may have resolved things, for us at least.  I will continue to keep an eye out for similar exceptions and provide the date and request ids accordingly.  Thank you!

**Comment by ificator** [comment]
Thanks @DanHopkins-TGI, I'm going to mark this as resolved for now but I'll leave it open for another week or so just in case you do see a blip.

**Comment by AnnieChmarak** [comment]
We've experienced the same issue yesterday.

While obtaining an upload url and lately while setting file metadata we recieved the following error:
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">`
`<HTML><HEAD><TITLE>Bad Request</TITLE>`
`<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>`
`<BODY><h2>Bad Request - Invalid Hostname</h2>`
`<hr><p>HTTP Error 400. The request hostname is invalid.</p>`
`</BODY></HTML>`

Unfortunately we do not have full logs of what happened because the issue occured in release version of our product. If needed, we can try to reproduce it using Fiddler and then put the log here.

**Comment by ificator** [comment]
Thanks for letting us know @AnnieChmarak - this issue is very intermittent and we haven't been able to get a repro. That's made it hard to track down, but I believe we made another change on Wednesday evening (PST) that seems to have fix things as far as our telemetry is concerned. Please let us know if you're still seeing the issue from now on.
