### ISSUE TITLE
How to properly open the Javascript file picker?

### ISSUE THREAD

**Issue by frapell** [OneDrive/onedrive-api-docs#850]
I am following this guide: https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file

What I need to get after clicking "Open" in the filepicker, is the file UID and the file name. That's it.

This is what I'm trying:

1) 
```
  function launchOneDrivePicker(){
    var odOptions = {
      clientId: c_onedrive_client_id,
      action: "query",
      multiSelect: false,
      advanced: {
        redirectUri: c_onedrive_redirect_uri,
        endpointHint: c_onedrive_endpoint_hint,
        navigation: {
          disable: true
        }
      },
      success: onedriveSuccess,
      cancel: onedriveCancel,
      error: onedriveError
    };
    OneDrive.open(odOptions);
  }
```

When the ```launchOneDrivePicker()``` is called, the filepicker popup comes up, I am requested to login with my microsoft credentials, there is no request back to the ```redirectUri```, no oauth token, etc.
After I select a file and click "Open" in the file picker, the ```onedriveSuccess``` function is called with a ```files``` argument, and only the file UID.
So, this works fine, however, I also need the file name, so I try this:

2) 
```
  function launchOneDrivePicker(){
    var odOptions = {
      clientId: c_onedrive_client_id,
      action: "query",
      multiSelect: false,
      advanced: {
        queryParameters: "select=id,name",
        redirectUri: c_onedrive_redirect_uri,
        endpointHint: c_onedrive_endpoint_hint,
        navigation: {
          disable: true
        }
      },
      success: onedriveSuccess,
      cancel: onedriveCancel,
      error: onedriveError
    };
    OneDrive.open(odOptions);
  }
```

Once I add the ```queryParameters```, calling ```launchOneDrivePicker()``` will now start an oauth negotiation by issuing a request to ```redirectUri```. After authorizing and getting an access token, I have this:

```
  function launchOneDrivePicker(){
    var odOptions = {
      clientId: c_onedrive_client_id,
      action: "query",
      multiSelect: false,
      advanced: {
        queryParameters: "select=id,name",
        accessToken: "ACCESS-TOKEN-HERE",
        redirectUri: c_onedrive_redirect_uri,
        endpointHint: c_onedrive_endpoint_hint,
        navigation: {
          disable: true
        }
      },
      success: onedriveSuccess,
      cancel: onedriveCancel,
      error: onedriveError
    };
    OneDrive.open(odOptions);
  }
```

And when calling ```launchOneDrivePicker()``` opens the file picker just fine. However, after selecting a file, and clicking "Open", the ```onedriveSuccess``` function gets called, but the first argument says "HTTP error status: 401"
Also, in the browser dev tools console, I'm seeing:
```
[OneDriveSDK] calling xhr failure callback, status: 401 
[OneDriveSDK] Received ajax error.
```

I also tried adding ```scopes```, so the full code would look like this:
```
  function launchOneDrivePicker(){
    var odOptions = {
      clientId: c_onedrive_client_id,
      action: "query",
      multiSelect: false,
      scopes: "user.read files.read files.read.all sites.read.all",
      advanced: {
        queryParameters: "select=id,name",
        accessToken: "ACCESS-TOKEN-HERE",
        redirectUri: c_onedrive_redirect_uri,
        endpointHint: c_onedrive_endpoint_hint,
        navigation: {
          disable: true
        }
      },
      success: onedriveSuccess,
      cancel: onedriveCancel,
      error: onedriveError
    };
    OneDrive.open(odOptions);
  }
```

however this doesn't seem to make any difference...

Am I doing something wrong here? Any help would be appreciated

**Comment by brownbl1** [comment]
I'm getting the same thing. I also want to return the filename so that I don't have to make an additional request to the graph API. But as soon as I add `queryParameters`, everything breaks.

Here is my code:
```js
window.OneDrive.open({
  clientId,
  action: 'query',
  advanced: {
    queryParameters: 'select=id,name,size,file,folder,photo',
    accessToken: user.access_token,
    endpointHint: `${drive.webUrl}/App Folder`,
    navigation: {
      disable: true,
    },
  },
  success: resolve,
  cancel: () => reject('cancelled'),
  error: reject,
})
```

Also worth noting that I'm targeting Sharepoint sites here. I ensure that the `App Folder` is already created at the root of the drive/document library in question. Using endpointHint allows the me to open the picker in that folder directly. But it only returns the file id, and I need the name as well. It seems like it using the `endpointHint` as the base url to make a separate request from my user agent, which is what I'm actually trying to avoid.

**Comment by matfricker** [comment]
I know this is a bit of an old issue. After tinkering for some time. As @brownbl1 mentioned queryParameters with custom properties seems to break things. If you were to remove queryParameters the only properties returned are 'endpoint','id','parentReference' & 'sharepoint'. So the issue lies in the other properties 'name','size','file','folder','photo'. Even thought the [docs](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#using-the-picker-and-api-together) suggest otherwise. I too am in favour of avoiding a seperate request.

If you were to use the 'download' action instead more properties are returned. Although I am not sure that is what download is intended for?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
