### ISSUE TITLE
monitor URL of AsyncJob returns inconsistent HTTP code

### ISSUE THREAD

**Issue by isac322** [OneDrive/onedrive-api-docs#852]
I tested [file copy](https://docs.microsoft.com/ko-kr/onedrive/developer/rest-api/api/driveitem_copy) on 1 personal drive and 2 business drives.

```http
POST /drive/items/{folder-item-id}/copy
Content-Type: application/json
Prefer: respond-async

{
  "parentReference": {
    "path": "/drive/root:/Documents"
  },
  "name": "Copy of LargeFolder1"
}
```

All tests returns `Location` with `202`. but on the next step (GET the `Location`), two Business drives return `200` constantly, and one Personal drive returns `202` as response code __only__ for first HTTP request and `200` for subsequent request.

**Comment by ificator** [comment]
The asynchronous operation flow generally makes no statements on how many subsequent `202` responses you'll get before completion, since the operations being executed can take a non-deterministic time to complete (e.g. copying larger files will take longer, resulting in more `202` responses dependant on the polling interval).

Business is a little misleading at the moment only because it's not a true asynchronous copy, but that will be changing in the near future. You'll want to make sure you handle the intermediate `202` responses, and use the status within those to provide appropriate feedback to your users.
