### ISSUE TITLE
Synchronization fails with 'Key not found: parentReference' (API change or regression?)

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#907]
It appears that potentially there is a regression in the OneDrive API for shared folders.

Previously, shared folders would present a 'parentReference' item when performing a `GET /drives/{drive-id}/root/delta`

Has there been an API change in regards to this, or is this a regression?

**Comment by abraunegg** [comment]
@ificator 
This is with OneDrive Personal accounts.

**Comment by abraunegg** [comment]
Correct.

I replicated the issue myself, can do a WebEx if needed & show json queries / responses etc

**Comment by ificator** [comment]
I think I see what's going on - it appears to be related to whether the shared folder is at the root of the drive or in a subfolder. It doesn't look like their have been any recent changes in this area though so I'm not sure how to explain it only occurring recently (unless the folders were originally at the root and were moved to a subfolder not long ago).

Out of curiosity, what properties are you expecting to exist in the parent reference? In this case I'd imagine we'd end up populating it with `driveId` and `driveType`.

**Comment by abraunegg** [comment]
It certainly was providing different information ~ June 17 this year when this was resolved for the linux client (see: https://github.com/abraunegg/onedrive/commit/17e5138b5a7aeb00e856e85b81818af6bfe0ddb9) 

The properties that are now missing for shared items which were previously provided are:
```
item["parentReference"]["id"].str
item["parentReference"]["driveId"].str
item["parentReference"]["path"].str
```

**Comment by ificator** [comment]
Strange - I don't see any changes that would explain getting back the `id` and `path` of the parent of the shared folder when the parent is inaccessible to the caller.

It was a bug that you were seeing no `parentReference` as that was inconsistent with what you got when you did a direct `GET` of the shared folder, but it's not possible for us to return any item information for the parent in this case because the caller does not have permission to it, and so doing so would expose information that shouldn't be visible. Instead you'd expect to see a `parentReference` with only the `driveId` and `driveType` populated.

**Comment by abraunegg** [comment]
Just to clarify:

Previously (before the submission of this case) when a call was being made to `/drives/{drive-id}/root/delta` for the shared users folder, it certainly was returning `parentReference` where parent reference contained the id, driveId and even the path of the object.

Since ~5 days ago now - calls to `/drives/{drive-id}/root/delta` does not return `parentReference` at all.

In my comment above I was responding to your ask as "what properties are you expecting to exist in the parent reference"

**Comment by abraunegg** [comment]
@ificator
Any update on this issue?

**Comment by ificator** [comment]
We've deployed a change that should add the `parentReference` for the one scenario where we found it could be missing. However, in that scenario you will not get back a path or id because it's not available due to either hierarchy or permissions (e.g. "root" has no parent so won't return id/path, same for the unshared parent of a shared item as doing so would disclose information about an item not shared to the caller).

I'm curious to see if this fixed your issue, or if there's another variation at play that we have yet to discover.

**Comment by abraunegg** [comment]
@ificator 
Thanks - will run through some tests today

**Comment by abraunegg** [comment]
@ificator 
The change now presents the `parentReference` which went missing but the response still lacks the all details which were previously returned by the query prior to June 17th this year when I know this was successfully working.

Below is a call and the applicable response - however 'id' is missing from the 'root' shared folder (it used to be there), but it is there / present for the file inside the folder.

```
GET /v1.0/drives/bc7d88ec1f539dcf/items/BC7D88EC1F539DCF!107/delta?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference

OneDrive Response: {
						"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#Collection(driveItem)",
						"@odata.deltaLink":"https:\/\/graph.microsoft.com\/v1.0\/drives\/bc7d88ec1f539dcf\/items\/BC7D88EC1F539DCF!107\/delta?select=id%2cname%2ceTag%2ccTag%2cdeleted%2cfile%2cfolder%2croot%2cfileSystemInfo%2cremoteItem%2cparentReference&token=<redacted>",
						"value":[
							{
								"@odata.type":"#microsoft.graph.driveItem",
								"cTag":"adDpCQzdEODhFQzFGNTM5RENGITEwNy42MzY3MTA0MDkxODEwMDAwMDA",
								"eTag":"aQkM3RDg4RUMxRjUzOURDRiExMDcuMg",
								"fileSystemInfo":{"createdDateTime":"2018-08-28T08:10:03.573Z","lastModifiedDateTime":"2018-08-28T08:10:03.573Z"},
								"folder":{"childCount":0,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},
								"id":"BC7D88EC1F539DCF!107",
								"name":"3A",
								"parentReference":{"driveId":"bc7d88ec1f539dcf","driveType":"personal"}
							},
							{
								"@odata.type":"#microsoft.graph.driveItem",
								"cTag":"aYzpCQzdEODhFQzFGNTM5RENGITEwOC4zODc",
								"eTag":"aQkM3RDg4RUMxRjUzOURDRiExMDguMTA",
								"file":{"hashes":{"sha1Hash":"08F2BBF52E13FCBAF168AA93B778DB9FE125114D"},
								"mimeType":"application\/vnd.openxmlformats-officedocument.wordprocessingml.document"},
								"fileSystemInfo":{"createdDateTime":"2018-08-28T08:10:11.356Z","lastModifiedDateTime":"2018-08-28T08:10:37.67Z"},
								"id":"BC7D88EC1F539DCF!108",
								"name":"3A-doc-initial.docx",
								"parentReference":{"driveId":"bc7d88ec1f539dcf","driveType":"personal","id":"BC7D88EC1F539DCF!107","name":"3A","path":"\/drives\/bc7d88ec1f539dcf\/items\/BC7D88EC1F539DCF!107:"}
							}
						]}

Drive Item: {
					"@odata.type":"#microsoft.graph.driveItem",
					"cTag":"adDpCQzdEODhFQzFGNTM5RENGITEwNy42MzY3MTA0MDkxODEwMDAwMDA",
					"eTag":"aQkM3RDg4RUMxRjUzOURDRiExMDcuMg",
					"fileSystemInfo":{"createdDateTime":"2018-08-28T08:10:03.573Z","lastModifiedDateTime":"2018-08-28T08:10:03.573Z"},
					"folder":{"childCount":0,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},
					"id":"BC7D88EC1F539DCF!107",
					"name":"3A",
					"parentReference":{"driveId":"bc7d88ec1f539dcf","driveType":"personal"}
			}
```

**Comment by ificator** [comment]
That's unfortunately to be expected, and if it ever worked as you outlined that was bug.

Consider the following hierarchy:
![image](https://user-images.githubusercontent.com/8387253/46693136-da81d780-cbbd-11e8-9fd8-a4f8f916c3be.png)

As a user that has access to the "shared" folder, the owner has granted me access to "shared" and "child" and so for those I can see all of their attributes, including their ids and paths. However, since I do not have access to "unshared" I should not be able to see any of its attributes, including the id and the path. Normally that's clear cut, but when the `parentReference` comes into the picture it can be a little confusing. What do we return for the `parentReference` for "shared" when the user does not have access to the parent? The answer is we can only return information about the drive - anything else would be disclosing information that the user should not see.

The `parentReference` for "child" can be fully populated because the user has access to "shared", but in this case you'll not that the path returned is relative to the highest accessible item in the hierarchy, which in this case would be "shared".

**Comment by abraunegg** [comment]
@ificator 
yes - totally get that the permissions of root / unshared would not be available - except that it used to be - but when added as a shared folder, the 'id' of 'shared' was the parent id of the folder in my OneDrive where I had placed the shared folder within my structure.

Anyways - I have worked around the issue in code - it 'seems' to work as expected now, so hopefully this can stay resolved :)
