### ISSUE TITLE
Copy request to 2.0 API endpoint returns status monitoring URL to 2.1 API endpoint

### ISSUE THREAD

**Issue by AndreiPashkin** [OneDrive/onedrive-api-docs#919]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
I expect `POST /me/drive/items/{item-id}/copy` return status monitoring URL to the same version of API.

#### Observed Behavior
`POST /me/drive/items/{item-id}/copy` returns status monitoring URL that belongs to a different API version (2.1 in this case). It creates problems because operation status-checking URL differ between 2.0 and 2.1 API versions.

#### Steps to Reproduce
Real-life example.

*Request*
```
POST /_api/v2.0/drive/items/<REDACTED>/copy/ HTTP/1.1
Host: <REDACTED>
User-Agent: python-requests/2.18.4
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: Bearer <REDACTED>
Content-Length: 125
Content-Type: application/json

{"parentReference": {"driveId": "<REDACTED>", "path": "test_folder"}}
```
*Response (some headers are omitted for brevity)*
```
HTTP/1.1 202 Accepted
Expires: -1
Location: https://<REDACTED>/_api/v2.1/drive/operations/<REDACTED>
```

**Comment by ificator** [comment]
Thanks @AndrewPashkin. What kind of issues do you encounter with the swap? Theoretically the monitor URL should be opaque, and the final redirect (if appropriate auth is provided) should still hit the v2.0 endpoint.

**Comment by AndrewPashkin** [comment]
@ificator 
For example instead of `percentageComplete` key 2.1 uses `percentComplete`. And also 2.1 omits this key when `status` equals `complete`.

**Comment by AndrewPashkin** [comment]
@ificator, also `resourceId` is absent when `status` is not `complete` in 2.1 unlike in 2.0.

**Comment by ificator** [comment]
Thanks for pointers! The `percentageComplete` vs `percentComplete` discrepancy is a bug, so we'll discuss internally about what to do for that - it obviously should not have changed with this switch.

The other two issues are an artifact of the change that drove the switch to v2.1 for the monitor URLs - in the past the copy was never truly asynchronous, which is why v2.0 always returned `percentageComplete=100.0`, `status=complete`, and `resourceId=<something>` on the first request. We have since made the copy truly asynchronous, which means the `resourceId` value is not known until `status=complete` (which may require numerous polls to encounter) and so there isn't much we can do on that front.

In regards to the lack of percentage when `status=complete` the thinking was that complete implies 100% so we could save bytes on the wire by not including it. That's something we can look at changing if it's useful for your scenario.

**Comment by AndrewPashkin** [comment]
@ificator,  
> The percentageComplete vs percentComplete discrepancy is a bug, so we'll discuss internally about what to do for that - it obviously should not have changed with this switch.

Alright. 

> We have since made the copy truly asynchronous, which means the resourceId value is not known until status=complete

That makes sense.

> In regards to the lack of percentage when status=complete the thinking was that complete implies 100% so we could save bytes on the wire by not including it.    

For me it's more a backwards-compatibility issue, because my old code ceased to work and I had to make some adjustments.

**Comment by ificator** [comment]
To close this out - we have fixed the compatibility issues you pointed out. Unfortuantely that means we now have `percentageComplete` and `percentComplete` to avoid breaking people that took a dependency what the API returned during the time in which we were returning the wrong field name. I'd suggest you use `select` to only grab the fields you care about to avoid duplicate data in the response, and we'll clean it up the next time we version the API.
