### ISSUE TITLE
[Question] Reuse authorization codes in Azure Active Directory authentication

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#959]
Hi all,

Recently, Azure AD apps make some updates:

https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#october-2018

It might follows: 
https://openid.net/specs/openid-connect-core-1_0.html#TokenRequestValidation

- 3.1.3.2.  Token Request Validation
- **If possible, verify that the Authorization Code has not been previously used.**

But according to this article:
https://docs.microsoft.com/zh-tw/onedrive/developer/rest-api/getting-started/aad-oauth?view=odsp-graph-online

In most cases, the OneDrive for Business API endpoint URL will not be known. To discovery the endpoint URL, you need to make a call to the Office 365 Discovery API.

In my understanding, I have to use the same code to request two resources:
1.https://api.office.com/discovery/
2.https://XXX-my.sharepoint.com/

If I want to finish this oath flow in one user authentication.

Do you have any idea and suggestion with this? or I just misunderstand the updates.

Thank you for help.

**Comment by JeremyKelley** [comment]
Hi,

The documentation is out of date now unfortunately and we'll get it updated, thank you for bringing it to our attention.  

The best thing to do now would be to use the Microsoft Graph APIs rather than the direct OneDrive API, that way you won't have to worry about which endpoint to use.  You can get started at https://graph.microsoft.com to find out more, in that scenario you'll only need to request access to the Microsoft Graph resource.

Unfortunately, even if you want to use the direct OneDrive API you would now need to use Microsoft Graph to get the direct OneDrive for Business endpoint you want to use.

**Comment by joewutaiwan** [comment]
Hi @JeremyKelley 

Thank you for reply,

More points need to be clarified:

1. Would old granted direct OneDrive API access token be affected? or we could keep it rather than migrating to graph API?

2. According to last paragraph in your response, I do not find any clue about onedrive end point in graph drive document, do you have any recommended document path?

Thanks a lot.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
