### ISSUE TITLE
Recursive children expanding

### ISSUE THREAD

**Issue by paya-cz** [OneDrive/onedrive-api-docs#97]
So according to the documentation ([ref1](https://dev.onedrive.com/items/get.htm), [ref2](https://dev.onedrive.com/odata/optional-query-parameters.htm)), I can get `Item` and its children in a single call:

> GET /drive/root?expand=children

And I can also apply `select` query onto the children only (and maybe `orderby` too? haven't tested it)

> GET /drive/root?expand=children(select=name)

I am not sure if this is by design, or if this is a bug, but the following statement does not work as expected:

> GET /drive/root?expand=children(expand=children)

I would expect to get a response with the item's children also expanded.

**Comment by peternied** [comment]
The OneDrive API does not support multi-level relationships at this time, as defined in the [OData specification](http://www.odata.org/documentation/odata-version-2-0/uri-conventions#ExpandSystemQueryOption)

If you are looking at getting the entire contexts of a users OneDrive, or a specific subfolder I would recommend using the [view.changes](https://dev.onedrive.com/items/view_changes.htm) API as it will offer you a reference point to retrieve only the items that have been modified since your last request.  Making it much easier to cache and manage the data that you get back from the service.
